jme3-examples/src/main/java/jme3test/niftygui/TestNiftyGui.java, jme3-niftygui/build.gradle, jme3-niftygui/src/main/java/com/jme3/cinematic/events/GuiEvent.java, jme3-niftygui/src/main/java/com/jme3/cinematic/events/GuiTrack.java, jme3-niftygui/src/main/java/com/jme3/niftygui/InputSystemJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/JmeBatchRenderBackend.java, jme3-niftygui/src/main/java/com/jme3/niftygui/NiftyJmeDisplay.java, jme3-niftygui/src/main/java/com/jme3/niftygui/RenderDeviceJme.java
This commit updates Nifty to version 1.4.1 and makes all
the necessary changes to the JME-Nifty integration to be
compatible with this version of Nifty (manily support of multiple
texture atlases in the batch renderer and some minor changes
like the removal of some *Null classes).
Most User code should still be able to compile with this change.
However, the NiftyJmeDisplay constructor that requires the
width and height of the texture atlas has been deprecated in
favour of the newly added static factory methods:
NiftyJmeDisplay.newNiftyJmeDisplay(). The new methods
add support for the Nifty BatchRenderConfiguration class that
allow further configuration of some rendering details.
The testcase jme3test.niftygui.TestNiftyGui has been modified
to use the new methods and seems to render fine …
=> feature: Update Nifty GUI to version 1.4.1

jme3-core/src/main/java/com/jme3/renderer/RenderManager.java, jme3-core/src/main/java/com/jme3/renderer/queue/RenderQueue.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/BasicShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/DirectionalLightShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/PointLightShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/PssmShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/ShadowUtil.java, jme3-core/src/main/java/com/jme3/shadow/SpotLightShadowRenderer.java
Shadow rendering was using the flattened list of all scene geometries to check culling. This optimization traverses the scene hierarchy recursively from `rootNode` and tries to cull the whole `Node` whenever possible.
When the scene is constructed carefully to take advantage of hierarchical culling the optimization is significant.
The optimization tries to maintain the jME `public interface`. Some shadow related `RenderManager` or `RenderQueue` members were marked `@Deprecated`, mainly the flattened lists of shadow occluders and receivers, which are no longer used.
Two deprecated renderers, `BasicShadowRenderer` and `PssmShadowRenderer` were updated too, as these would not work with flattened occluders and receivers missing.
We are not aware of any other dependencies to be addressed.
=> Optimize RenderShadow to use scene hierarchy for culling

jme3-networking/src/main/java/com/jme3/network/serializing/serializers/SavableSerializer.java
Fixed the exception occurring when using this serializer. More commented here:
http://hub.jmonkeyengine.org/t/savableserializer-and-client-bufferunderflowexception/31774
=> Fixed BufferUnderflowException

jme3-core/src/main/java/com/jme3/renderer/RenderManager.java
Fixed an issue where viewport sizes could be a pixel smaller in either
dimension in certain situations.  This caused gaps to appear between
adjacent viewports at certain resolutions.
Forum Reference:
http://hub.jmonkeyengine.org/t/fix-for-rounding-errors-in-viewport-dimensions/31751
=> Fix for incorrect viewport sizes

jme3-bullet/src/main/java/com/jme3/bullet/objects/VehicleWheel.java, jme3-jbullet/src/main/java/com/jme3/bullet/objects/VehicleWheel.java
These are necessary if jme's bullet wrapper is used in a non Scenegraph enviroment,
for example a ES based server. As without this there is no clean way to get the values of these two variables.
-> wheelspat being null in this case, normally the rotation and position is set to the Wheel Spatial.
In the case of a Scenegraphless Server it makes no sense to have a dummy spatial just for this, especially if all logic necessary already exist, and only the getters are missing.
Signed-off-by: Kai Börnert <kai-boernert@visiongamestudios.de>
=> A very small change that creates two getters in VehicleWheel,,

jme3-core/src/main/java/com/jme3/renderer/queue/RenderQueue.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/DirectionalLightShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/PointLightShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/SpotLightShadowRenderer.java
During tweaking [Optimize RenderShadow to use scene hierarchy for culling](https://github.com/jMonkeyEngine/jmonkeyengine/pull/211) there was the statement:
> Bebul: The reason why there is still `RenderQueue.shadowRecv` left is to possibly reuse the collected receivers, as having the list of receivers in the camera frustum can become handy. So it is not necessarily empty! It is also used in our next to come push request...
The PR mentioned is [Fix shadow disappearing for Spot and Point Lights](https://github.com/jMonkeyEngine/jmonkeyengine/pull/218) which @shadowislord  and @Nehon has recognized to be more hack / workaround for an issue that shouldn't be there in the first place.
If so, the reason to keep recv shadow bucket in `RenderQueue` has vanished and there is no need to have both …
=> Obsolete shadowRecv and sceneReceivers code cleanup

sdk/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/ComposerCameraController.java
- Now you can't use scenecomposer tool while overiding the camera control
- Fixed a case where a tool modificaton isn't undo/redo able.
=> Fix issue #255 - scenecomposer : forcedCamera

jme3-bullet/src/common/java/com/jme3/bullet/control/RigidBodyControl.java
=> Fixed typo #258

sdk/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/tools/PickManager.java, sdk/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/tools/RotateTool.java
=> SDK SceneComposer : fixed the rotate tool, now all works fine.

jme3-core/src/plugins/java/com/jme3/asset/plugins/ZipLocator.java
While for the FileLocator "/path/x.png" and "path/x.png" are the same location, the ZipLocator (since they are passed directly to ZipFile.getEntry) treats them as two different location, as it should be on a zip archive, but since there is no need of this for the asset manager I think it's reasonable to make both FileLocator and ZipLocator work in the same way.
I noticed this problem after I load a blend model from a zip file and its textures were missed because all path were starting with a slash. I'm not sure if the HttpZipLoader is affected too.
=> Fix for ZipLocator and path with the root slash

jme3-niftygui/src/main/java/com/jme3/cinematic/events/GuiEvent.java
Replaced call to System.out.println() with proper logging call.
=> [Nifty-GUI] Using java logger, instead of stdout

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/resources/Common/MatDefs/Misc/Unshaded.frag, jme3-core/src/main/resources/Common/MatDefs/Misc/Unshaded.j3md, jme3-core/src/main/resources/Common/MatDefs/Misc/Unshaded.vert, jme3-core/src/main/resources/Common/ShaderLib/GLSL150Compat.glsllib
I remade the PR #288 to have a cleaner diff and history (commit log).
The PR include a fix for  GLSL150Compat  (the version + auto-injection of the define XXXX_SHADER).
=> add GL3 support for Unshaded and MRT (v2)

jme3-bullet-native/src/native/cpp/com_jme3_bullet_objects_PhysicsRigidBody.cpp, jme3-bullet-native/src/native/cpp/com_jme3_bullet_objects_PhysicsRigidBody.h, jme3-bullet/src/main/java/com/jme3/bullet/objects/PhysicsRigidBody.java
This modification allow to "lock" a degree of freedom of one rigidBody, without joint. This ability is only available with native bullet. 
This can be useful for using bullet for 2D game (maybe not the best option), this can be done like so : 
```java
body.setAngularFactor(new Vector3f(0,0,1)); // <-- only rotate on Z axis
body.setLinearFactor(new Vector3f(1,1,0)); // <-- only move on a 2D plane (X-Y)
```
You can also set a value between [0;1] to "reduce" the movement / rotation. 
Using angular/linear factor do not preserve the conservation of energy. (the factor only scale the "forces")
=> Bullet RigidBody : added support to vector3f based AngularFactor & LinearFactor

jme3-core/src/main/java/com/jme3/bounding/BoundingBox.java
I'm using jMonkeyEngine to display content, that was created for DirectX, and therefore I have to use a negative scaled z axis.
The bounding box of a rotated and negative scaled object, is totally messed up.
Using the absolute value of scale, when calculating the scaled bounding box extent, eliminates the problem.
=> Fixed wrong BoundingBox transformation, when using negative scaling values

jme3-bullet-native/src/native/cpp/com_jme3_bullet_collision_shapes_GImpactCollisionShape.cpp
I hope this will fix the issue #188 , i didn't have a test case : /
( added a call to updateBound() just after creating the shape )
=> GImpactCollisionShape : fix for #188, added updateBound()

jme3-desktop/src/main/java/com/jme3/app/state/MjpegFileWriter.java
According to the Oracle's [docummentation](http://docs.oracle.com/javase/7/docs/api/java/io/ByteArrayOutputStream.html#close()): "Closing a ```ByteArrayOutputStream``` has no effect. The methods in this class can be called after the stream has been closed without generating an ```IOException```."
=> Delete close() of ByteArrayOutputStream type objecs

jme3-jogl/src/main/java/com/jme3/input/jogl/NewtMouseInput.java
* Y hotspot is top in jogl, and bottom in jme
* in jme when mouse is invisible it should be confined into the window (on mac it could go out of the window)
* when window doesn't has the focus the mouse should not behave like when has the focus like 
* trying to re-center
* stay invisible
=> jogl: some fixes about mouse handler

jme3-bullet/src/common/java/com/jme3/bullet/control/BetterCharacterControl.java
Sometimes, when the BetterCharacterControl is not moving, it flickers due it physics being always active. The reason for it being always active is that on the prePhysicsTick method it always set the rigidBody's linear velocity (and the method PhysicsRigidBody.setLinearVelocity(Vector3f) reactivates the physics each time is called).
The fix consist on just comparing if the current velocity and the setting one aren't the same and, thus, not setting it (using ZERO_TOLERANCE instead 0 to best results).
=> Fixed BetterCharacterControl "flickering" when not moving.

jme3-core/src/tools/java/jme3tools/optimize/TextureAtlas.java
It seems that the variable was the wrong one when adding the normal texture to the atlas.
Link to the post where this is talked: http://hub.jmonkeyengine.org/t/fixed-a-possible-bug-in-textureatlas-java/34653
=> Fixed a possible bug in TextureAtlas.java

jme3-core/src/main/java/com/jme3/app/Application.java, jme3-examples/src/main/java/jme3test/app/TestEnqueueRunnable.java
This commit adds a new enqueue() method to Application that accepts a Runnable object rather than a callable to allow for the following cleaner syntax when using Java 8 lambda expressions.
callable-only enqueue:
```
enqueue(() -> {
doSomething();
return null;
});
```
runnable enqueue:
`enqueue(() -> doSomething());`
=> Added enqueue runnable

jme3-core/src/main/java/com/jme3/light/DirectionalLight.java, jme3-core/src/main/java/com/jme3/light/Light.java, jme3-core/src/main/java/com/jme3/light/PointLight.java, jme3-core/src/main/java/com/jme3/light/SpotLight.java
Soo this PR requires a bit of explanation I think.
I did **not** use "throws CloneNotSupportedException" even though NetBeans suggests it.
I simply don't since we already consume that exception in Class "Light" and we currently have no reason to throw it (XYZLight will always be Clonable)
Casting super.clone(); is valid because Object.clone() will clone the runtime implementation so in DirectionalLight we will really have a DirectionalLight (see http://stackoverflow.com/a/12213417)
The last thing: I hope it's okay that DirectionalLight.clone() returns a DirectionalLight? This saves us from useless "instanceof" and cloning on the user-level since "covariant returns" are allowed since Java 5 (returning a subclass of the overriden method's return type)
=> Fixes the bug of shallow copies when cloning lights

sdk/jme3-terrain-editor/src/com/jme3/gde/terraineditor/sky/SkyboxWizardPanel2.java
In Issue #81, we simply passed the User Input to the SkyFactory which threw an Exception  in multiple cases:
a) When a User didn't specify all Textures
b) When they weren't a Square.
This is now fixed so you can't even proceed in the Wizard with these faults.
For this, only small changes to the Panel were needed.
This is how it looks like: (This is only the Netbeans example)
=> Validate SkyboxWizard's Input (#81)

sdk/jme3-materialeditor/src/com/jme3/gde/materialdefinition/editor/MatDefEditorToolBar.java, sdk/jme3-materialeditor/src/com/jme3/gde/materialdefinition/fileStructure/TechniqueBlock.java
So whilst playing around with MatDefs I found this two issues:
a) When you only have one technique, you couldn't click into the ComboBox without a crash.
The reason behind this is that you cannot select the same item itself, so closing the box will lead to selected == null.
We fix this by simply taking the first item. If there are multiple available techniques we also print a warning regarding this.
b) When you have an incomplete MatDef, we had a few NPE's which crashed the sdk and hence made switching to another MatDef impossible.
I don't know if Exceptions on a broken (and hence user edited) MatDef are intentional but since the other code checks for null's, I assume it was simply missing :) 
BTW: Example MatDef for b
```
Technique Test {
}
```
=> Two small ShaderNodes fixes

jme3-core/src/main/java/com/jme3/effect/ParticleEmitter.java
Currently there is a problem with ParticleEmitter. It doesn't take into account the the distance it has travelled between updates. Or at least this is my interpretation - I didn't invent this solution. methusalah did. Please see the following threads for more information:
http://hub.jmonkeyengine.org/t/interpolation-of-particle-spawning-point/30385/9
http://hub.jmonkeyengine.org/t/interpolation-of-particle-spawning-point-when-emitter-has-moved/30400
The following images are from my game. FPS is 60 and the emitter emits 2000 particles per second. Projectile's linear speed is 200 world units / s (it uses RigidBodyControl).
Without interpolation
With interpolation
=> Interpolate particle positions

.travis.yml, bintray.gradle, build.gradle, common.gradle, gradle.properties, sdk/build.gradle, version.gradle
The commit will allow to publish (in dry mode) from travis to bintray in repository https://bintray.com/jmonkeyengine/org.jmonkeyengine when a tag (starting with jmeMainVersion) is pushed.
* On bintray
* create account on bintray (eg using github identity provider )
* ask me or Erlend to register the account as member of the organization jmonkeyengine to be able to upload artifacts
* On travis
* register 2 env variables (I prefer to setup in the settings'panel, but I guess using secure in .travis.yml should work)
* `ORG_GRADLE_PROJECT_bintray_user` with the bintray account name, could be displayed in build.log
* `ORG_GRADLE_PROJECT_bintray_api_key` with the bintray api key of the account (from https://bintray.com/profile/edit), could NOT be displayed in build.log 
* On desktop
set a git …
=> build: upload on bintray from travis when a git tag is set

sdk/jme3-welcome-screen/src/com/jme3/gde/welcome/Bundle.properties
Updated welcome screen to say "You are running the latest preview version of the SDK (jMonkeyEngine SDK 3.1-alpha1)" instead of SDK 3.0.
It gets data from the website like before (literally I just changed one character :smile:)
It fixes one of the bugs described in issue #329
=> Update Bundle.propreties to jME3.1

jme3-core/src/main/java/com/jme3/audio/AudioNode.java
Yeah, I just tried to implement #342.
I was uncertain on how the "jme-style" would be for that enum, so I took an inner-class enum, however moving it out it just a matter of two key presses :)
I did not remove the constructors but only deprecated them to not break existing code.
I was also unsure about deprecating ```AudioNode(AssetManager assetManager, String name)```, simply because it's a constructor where one doesn't have to think about types at all.
When merged/alpha 2 drops, I will add the Wiki accordingly :)
=> Simplified the AudioNode constructors (#342)

jme3-core/src/main/java/com/jme3/scene/BatchNode.java
- Clarified in the JavaDoc that CullHint is not used for batched geometries.
- Added collideWith method that takes care of ignoring batched geometries.
- Removed some commented and not used code.
- Changed signature of isBatch method to be public final - to allow users to check the children if they are batched geometries or not.
- Corrected spelling mistake for gatherGeometries method.
=> Batch node improvements

sdk/jme3-materialeditor/src/com/jme3/gde/materialdefinition/EditableMatDefFile.java, sdk/jme3-materialeditor/src/com/jme3/gde/materialdefinition/MatDefDataObject.java, sdk/jme3-materialeditor/src/com/jme3/gde/materials/MaterialPreviewRenderer.java
* Fixed a NPE when trying to select a Node. Now you can properly remove/edit nodes
* "smartLog" now compares the hash across different instances (Two Material Previews led to duplicate log messages)
* Using smartLog for CompilationErrors now to not spam the log with 60 FPS
The Lookup failed because there was no Instance of ```MatDefNavigatorPanel```.
Now everything works as intended (You can remove Nodes, change their properties, or at least select them without a crash.)
When you produce a shader compilation error, you have the same error printed three times (wireframe (geometry), solid (color) and a third). This doesn't happen anymore, since the hash is now static.
However I am uncertain because of such an example:
When you have two instances, one constantly printing a and one constantly …
=> Improved ShaderNodes

jme3-core/src/main/java/com/jme3/asset/AssetKey.java
See [here](http://hub.jmonkeyengine.org/t/blender-trouble-with-multi-part-character-model-how-to-do-it-right/35121/9)
This is essential for importing models (as you then don't know which assetKey triggered the error)
=> Be more verbose when the Asset Path is outside of the root.

sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeAnimControl.java, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeCharacterControl.java, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeControl.java, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeGenericControl.java, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeGhostControl.java, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeRigidBodyControl.java, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeSkeletonControl.java, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeTerrainLodControl.java, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/nodes/JmeVehicleControl.java
See http://hub.jmonkeyengine.org/t/dirty-flag-not-set-when-deleting-model-controls/35216
btw: Fix Imports removed some unused imports and the "fireSave" Override is lent from JmeLight.java
=> Fixed the Issue where removing a Control didn't set the dirty flag

jme3-core/src/main/java/com/jme3/scene/shape/Cylinder.java
Removed the modification of the input parameter that lead to a wrong axisSamples member when the cylinder is closed.
=> Cylinder: removed the modification ofaxisSamples parameter

jme3-examples/src/main/java/jme3test/bullet/PhysicsHoverControl.java, jme3-examples/src/main/java/jme3test/bullet/TestHoveringTank.java
A NPE is throw when running hovering tank test with native bullet.
```
java.lang.NullPointerException: The vehicle object does not exist.
at com.jme3.bullet.PhysicsSpace.addVehicle(Native Method)
at com.jme3.bullet.PhysicsSpace.addRigidBody(PhysicsSpace.java:627)
at com.jme3.bullet.PhysicsSpace.addCollisionObject(PhysicsSpace.java:426)
at jme3test.bullet.PhysicsHoverControl.setPhysicsSpace(PhysicsHoverControl.java:189)
at com.jme3.bullet.PhysicsSpace.add(PhysicsSpace.java:405)
at jme3test.bullet.TestHoveringTank.buildPlayer(TestHoveringTank.java:156)
at jme3test.bullet.TestHoveringTank.simpleInitApp(TestHoveringTank.java:128)
```
Because the native vehicle wasn't created in the setPhysicsSpace methode (in PhysicsHoverControl)
---
The collision group must be set after the creation of the …
=> fix NPE in hovering tank test, running with native bullet

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.vert
With the new Mikk Tangent Space generator this fix in the shader should produce correct shading results.
BiNormal/biTangent needs to be calculated in the fragment shader and the final normal has to be normalized.
http://i.imgur.com/gz9pRUP.png
https://hub.jmonkeyengine.org/t/normal-map-shading-problems/34947/91
=> Fix incorrect normal map shading in PBRLighting.

jme3-core/src/main/java/com/jme3/cinematic/events/MotionEvent.java
Long story short:
Even though you are about to overhaul the cloning system you could still be effected by this:
Since `lookAt` and `rotation` had no initial values, they were serialized as null leading to a NPE in the cloneForSpatial:
```
at com.jme3.cinematic.events.MotionEvent.cloneForSpatial(MotionEvent.java:284)
```
Line 284 is `control.lookAt = lookAt.clone();` (it's still alpha-3)
The thing which first caught me is the behavior of BinaryOutputCapsule's defValue:
It's purpose is NOT to write `defVal` when the `value == null` but rather to simply not serialize, when `value` is already `defVal`
I don't know if it'd be a good addition to serialize defVal when value is null (since serializing null is mostly pointless, and if not, you'd have that as defVal), but that's a different story.
=> Allow MotionEvents to be cloned (NPE)

jme3-core/src/main/java/com/jme3/light/Light.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL3.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLDebugDesktop.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/shader/Glsl100ShaderGenerator.java, jme3-core/src/main/java/com/jme3/shader/VarType.java, jme3-core/src/main/java/com/jme3/texture/FrameBuffer.java, jme3-core/src/plugins/java/com/jme3/material/plugins/ShaderNodeLoaderDelegate.java, jme3-jogl/src/main/java/com/jme3/renderer/jogl/JoglGL.java, jme3-lwjgl/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java
These are necessary changes to implement improved shadow rendering.
Recreation of this pull request: [old pull request](https://github.com/jMonkeyEngine/jmonkeyengine/pull/452) for master branch instead of PBR branch.
Texture arrays can now be set as render targets for color and depth buffers.
Also fixed an issue with the shader node generation, when using array variables the multiplicity was missing.
Added getters and setters in the Light class for frustumCheckNeeded and intersectsFrustum, to be able to implement a custom light filter.
Forum: http://hub.jmonkeyengine.org/t/improved-shadow-renderer/33496/50
=> Texture arrays as render targets, bugfix for shader nodes and new getter and setter in Light class

jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglCanvas.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglDisplay.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglOffscreenBuffer.java
lwjgl now respects `AppSettings.getAlphaBits()` when creating its PixelFormat.
=> Let lwjgl respect the AlphaBits setting

jme3-bullet-native/src/native/cpp/jmeClasses.cpp, jme3-bullet-native/src/native/cpp/jmeClasses.h, jme3-bullet-native/src/native/cpp/jmePhysicsSpace.cpp, jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java, jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java
In native bullet, group collision listeners we're never notified when a collision occurred for a group. This fixes the issue.
See http://hub.jmonkeyengine.org/t/physicscollisiongrouplistener-possibly-broken-in-native-bullet/35277/7
=> Fixed collision group listeners not being notified

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.vert, jme3-core/src/main/resources/Common/ShaderLib/Instancing.glsllib
The normal maps calculated in mikk tangent space expect unnormalized (interpolated) tangent and world normals in the fragment shader, because of this they have to be normalized in the vertex shader.
=> Get normals and tangent synced with mikk tangent space.

jme3-core/src/main/java/com/jme3/input/JoystickCompatibilityMappings.java, jme3-core/src/main/resources/joystick-mapping.properties, jme3-examples/src/main/java/jme3test/input/TestJoystick.java, jme3-lwjgl/src/main/java/com/jme3/input/lwjgl/JInputJoyInput.java
This pull request attempt to fix issue on linux where joystick/gamepad are detected whit the wrong logicalId (button name on linux instead of button number on windows).
- add missing .trim() in JoystickCompatibilityMappings.java
- fix some minor logging issue in JInputJoyInput
- add mapping for two gamepad : "GASIA CORP. PLAYSTATION(R)3 Controller", "DragonRise Inc.   Generic   USB  Joystick"
- add a easier way to create a custom joystick mapping in TestJoystick : "push a joystick button and click on the expected mapped button to print the entry for remapping the button"
for more info see the topic on the forum [here](https://hub.jmonkeyengine.org/t/joysticks-detected-with-wrong-logicalid-on-linux/35712)
=> Joystick detection on linux and more... (v3.1)

jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/RotationOrder.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/SceneLoader.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxAnimCurve.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxAnimNode.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxBindPose.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxCluster.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxImage.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxMaterial.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxMesh.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxNode.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxObject.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxSkin.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/objects/FbxTexture.java
Forum thread: https://hub.jmonkeyengine.org/t/fbx-importer/30309/39?u=eirenliel
Changes from original version:
* Load animations without any additional data (no SceneKeys or fba files) — animations are loaded from separate animation layers (currently not supported by Maya)
* Huge code refactoring. It is possible to work with now and add new features (looks like @shadowislord 's :))
* Added support for not baked transformations (like pre/post-rotations/translation/scale and pivots), all euler rotation orders are implemented too
* More accurate bone animation
* Up to 8 UV-layers
* ByPolygon material data is loaded correctly (without buffer overhead too)
* Textures are loaded by name from the same folder, if present and no better way found
* Added support of FaceCullMode.Off
* Support of …
=> Reworked original FBX importer

jme3-bullet-native/src/native/cpp/jmePhysicsSpace.cpp, jme3-bullet-native/src/native/cpp/jmePhysicsSpace.h
btGImpactCollisionAlgorithm hasn't been registered for physics spaces, causing Gimpact collisions to not be detected.
This pr solves it.
=> Fix GImpact passing through other shapes.

jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/SceneLoader.java, jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/SceneMeshLoader.java
Fix for the issue reported here: https://hub.jmonkeyengine.org/t/ogre-importer-materials-are-not-shared/35663
**Short description of the problem:**
We have an Ogre's .scene with two spatials that share the same material. 
When this scene is imported in the engine, the two spatials no longer share the material but, instead, they own a new instanced of it.
This happens because the SceneLoader loads the objects through the assetManager as if they were unrelated, the assetManager calls _clone(true)_ on the cached models before returning them, this cause the issue.
This patch loads the models directly with an instance of MeshLoader opportunely extended to have an internal cache that is preserved until the scene is fully loaded.
=> Ogre importer: Fix for material sharing

jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java
Continuing the discussion in the pull request: https://github.com/jMonkeyEngine/jmonkeyengine/pull/471, made the requested changes.
=> Ordering + raw methods instead of reversing.

jme3-core/src/main/java/com/jme3/scene/Geometry.java, jme3-core/src/main/java/com/jme3/scene/Node.java, jme3-core/src/main/java/com/jme3/scene/Spatial.java
This is a clean rework of an older pull request #170 .
This time with an enum to specify pre-order or post-order and without merge conflicts.
=> added a pre-order traversal of the scene graph

jme3-bullet/src/main/java/com/jme3/bullet/collision/shapes/CylinderCollisionShape.java, jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/CylinderCollisionShape.java
<strike>That method just prints a warning, so from my point of view there is no reason to leave the call there.
EDIT: I want to point out that this is an issue because when cylinder shapes are created frequently the logs are polluted with warnings about scaling when the developer isn't actually trying to scale the shape.</strike>
See below.
=> Removed warning if scale=1,1,1 in CylinderCollisionShape

jme3-bullet-native/src/native/cpp/com_jme3_bullet_objects_PhysicsRigidBody.cpp
Long overdue fix for: 
(in short calculating inertia on mass=0 objects can cause NAN depending on compiler parameters, these NAN will contaminate every other float they come in contact with, resulting in suddenly vanishing objects on jme side, as the nan position/rotation cannot be rendered and is outside frustum.
https://hub.jmonkeyengine.org/t/jmonkey-3-1-native-bullet-bug/33595/3
http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?p=12158&f=9&t=
Signed-off-by: Kai Boernert <kai-boernert@visiongamestudios.de>
=> Finally fixing this

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/main/java/com/jme3/material/Technique.java, jme3-core/src/main/java/com/jme3/renderer/RenderManager.java, jme3-core/src/main/java/com/jme3/scene/Spatial.java, jme3-core/src/main/java/com/jme3/util/SafeArrayList.java
Same as https://github.com/jMonkeyEngine/jmonkeyengine/pull/515, but for v3.1.
=> Garbage collection and list iteration improvements for v3.1

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/main/java/com/jme3/material/Technique.java, jme3-core/src/main/java/com/jme3/renderer/RenderManager.java, jme3-core/src/main/java/com/jme3/scene/Spatial.java, jme3-core/src/main/java/com/jme3/util/SafeArrayList.java
For-Each loop creates Iterator object and uses hasNext and next methods, which are slower, than manual iteration. Also allocating Iterator object increases work for GC.
Forum post: https://hub.jmonkeyengine.org/t/iteration-over-list-performance-improvement/36250
See test 9 for more details: http://www.devahead.com/blog/2011/12/coding-for-performance-and-avoiding-garbage-collection-in-android/
=> Garbage collection and list iteration improvements

jme3-core/src/main/java/com/jme3/animation/SkeletonControl.java, jme3-core/src/main/java/com/jme3/material/MatParam.java
... by implementing proper Array Serialization for MatParams and making the Shared Materials Check only a warning (it would pop up once each time you load the j3o and if you really use Shared Materials you have weird animations and some log spamming)
=> Fixes #499: Fix Hardware Skinning in 3.1 

jme3-core/src/main/java/com/jme3/opencl/AbstractOpenCLObject.java, jme3-core/src/main/java/com/jme3/opencl/Buffer.java, jme3-core/src/main/java/com/jme3/opencl/CommandQueue.java, jme3-core/src/main/java/com/jme3/opencl/Context.java, jme3-core/src/main/java/com/jme3/opencl/Event.java, jme3-core/src/main/java/com/jme3/opencl/Image.java, jme3-core/src/main/java/com/jme3/opencl/Kernel.java, jme3-core/src/main/java/com/jme3/opencl/OpenCLObject.java, jme3-core/src/main/java/com/jme3/opencl/Program.java, jme3-examples/src/main/java/jme3test/opencl/TestContextSwitching.java, jme3-examples/src/main/java/jme3test/opencl/TestVertexBufferSharing.java, jme3-examples/src/main/java/jme3test/opencl/TestWriteToTexture.java, jme3-jogl/src/main/java/com/jme3/opencl/jocl/JoclCommandQueue.java, jme3-jogl/src/main/java/com/jme3/opencl/jocl/JoclContext.java, jme3-jogl/src/main/java/com/jme3/opencl/jocl/JoclPlatform.java, jme3-lwjgl/src/main/java/com/jme3/opencl/lwjgl/LwjglCommandQueue.java, jme3-lwjgl/src/main/java/com/jme3/opencl/lwjgl/LwjglContext.java, jme3-lwjgl/src/main/java/com/jme3/opencl/lwjgl/LwjglPlatform.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglCommandQueue.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglPlatform.java
Hi,
after working some time with the wrapper, I found three important missing features that improved the workflow once implemented.
- missing `toString()` methods, useful for debugging
- added getter method for the device in the command queue, necessary e.g. to query the work group size
-  the `register()` methods for the automatic garbage collection of OpenCL objects now returns `this`. This is important so that e.g. `Buffer b = clContext.createBuffer(1).register();` can be written in one line
=> OpenCL for jME3 - some missing features

jme3-bullet-native/src/native/cpp/com_jme3_bullet_joints_Point2PointJoint.cpp
The rest of the native methods cast jointId to btPoint2PointConstraint so I've changed createJoint() to allocate a btPoint2PointConstraint.
Forum link: https://hub.jmonkeyengine.org/t/bugfix-for-point2pointjoints-native-createjoint/36147
=> Bugfix: Native Point2PointJoint.createJoint() incorrectly allocates btHingeConstraint

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
The problem: Happens with two MTR framebuffers with same number of color attachements.
If we set a frame buffer frame1, then later frame2.
r.setFrameBuffer(frame1);
r.setFrameBuffer(frame2);
Frame2 buffer will not output to multiple targets. Only its first target will be rendered.
This patch fixes that problem.
=> Fix for MTR Framebuffers

jme3-core/src/main/java/com/jme3/texture/FrameBuffer.java
RenderBuffer.getColorBuffer() returns now the color buffer at the index set by setTargetIndex(int), if multiple buffers are available.
This allows Renderer.readFrameBufferWithFormat to read all color buffers, not only the first one.
=> #503 fixed

jme3-core/src/main/java/com/jme3/renderer/Caps.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL3.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/texture/Image.java
Introduces integer texture types.
=> Integer Texture Support

.travis.yml, settings.gradle
LWJGL3 is only included int he build process, if the jdk is at least of version 1.8.
The travis build is edited so that it tests against Java7 and Java8.
This is the followup to pull request #549.
=> Followup to #549: conditional compilation of LWJGL3

jme3-plugins/src/xml/java/com/jme3/export/xml/DOMOutputCapsule.java
In DOMOutputCapsule Line 765 we're removing the last character (the space).
When we have an empty buffer, the last character isn't present.
- There already were some checks for empty buffers, but not for every buffer. They were implemented as `Math.max(0, buf.length() - 1);`. I changed that to `if (buf.length() > 0)` since that's more easy to understand. 
- I've added `@Override` to any Override.
- I've added the `//remove last space` comment where it was missing so it is consistent and obvious
- I've enclosed the if condition for the IOException in brackets so it's a bit more easily readable. (Since the long exception message looked like a block of multiple lines)
When this PR is approved/merged I will cherry pick this commit to v3.1
=> Fixes #566 - XML Serialization handles empty buffers properly now.

jme3-core/src/main/java/com/jme3/input/ChaseCamera.java
Added function cleanupWithInput() which does the opposite than registerWithInput(), like said [here](https://hub.jmonkeyengine.org/t/properly-unregister-chasecamera-from-inputmanager/36813).
=> Added cleanup for ChaseCamera

jme3-core/src/main/java/com/jme3/scene/shape/Quad.java
Write the width and height of a quad on serialization. Otherwise getWidth() and getHeight() always return 0 when a quad was created from de-serialization.
=> Write/read the width and height of a quad (3.1)

jme3-core/src/main/java/com/jme3/util/BufferAllocatorFactory.java, jme3-core/src/main/java/com/jme3/util/BufferUtils.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/util/LWJGLBufferAllocator.java
Implemented LWJGLBufferAllocator.
=> implemented LWJGL3 BufferAllocator

jme3-bullet/src/main/java/com/jme3/bullet/collision/shapes/CylinderCollisionShape.java, jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/CylinderCollisionShape.java
same diff riccardobl committed to 'master' on Jun 20, 2016
Without this change, a warning is generated every time you construct a CylinderCollisionShape.
=> CapsuleCollisionShape: warn about scaling only if it's not identity

jme3-core/src/main/java/com/jme3/material/MatParam.java
Some blender materials have null Material Param keys. This shouldn't
throw an exception in a toString method. So rather than throwing a
OperaitonNotSupported exception a string is returned informative of the
null state of the key.
=> Fixed a exception in Material toString with blender materials.

jme3-bullet/src/main/java/com/jme3/bullet/collision/shapes/CompoundCollisionShape.java
There is no explanation why this should be required, and NemesisMate says he tested it, and could not reproduce some of the older issues. It might have been solved with changes since then.
=> Removed the override that avoided a CompoundCollisionShape to be scaled

jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java
LWJGL3 / GLFW expects images for cursors in a different format: RGBA instead of ARGB and vertically flipped. Putting the fix in GlfwMouseInput rather than JmeCursor to preserve compatibility with LWJGL 2.
[Forum Thread](https://hub.jmonkeyengine.org/t/mouse-cursor-flipped-and-wrong-colors/37484)
=> Fixes mouse cursor format for LWJGL3

jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainPatch.java
I had a problem with direct memory cost when I very often make some changes of terrain heightmap(terrain editor). It took a lot of direct memory(8GB). So I have found a place on code where we can see, that we re-create a position buffer for each change. I have replaced it to reusing current position buffer.
=> added reusing position buffer on heightmap changing.

jme3-core/src/main/java/com/jme3/scene/debug/SkeletonInterBoneWire.java, jme3-core/src/main/java/com/jme3/scene/debug/SkeletonPoints.java, jme3-core/src/main/resources/Common/MatDefs/Misc/Unshaded.j3md, jme3-core/src/main/resources/Common/MatDefs/Misc/Unshaded.vert, jme3-examples/src/main/java/jme3test/model/anim/TestAnimBlendBug.java, jme3-examples/src/main/java/jme3test/model/anim/TestOgreComplexAnim.java
In 3.0, SkeletonDebugger used Mesh.setPointSize() to highlight the joints. Now that setPointSize() is disabled, users of SkeletonDebugger need materials that set gl_PointSize. In JmeTests, SkeletonDebugger is always used with Unshaded.j3md, so that seems the logical place for it.
=> add PointSize to Unshaded matdef, test with SkeletonDebugger

jme3-core/src/main/java/com/jme3/animation/Bone.java, jme3-core/src/main/java/com/jme3/animation/SkeletonControl.java, jme3-core/src/main/java/com/jme3/math/Transform.java, jme3-core/src/main/java/com/jme3/scene/Mesh.java, jme3-examples/src/main/java/jme3test/model/anim/TestAttachmentsNode.java
Formerly, getAttachmentsNode() assumed no local transform on any geometry with an animated mesh. However, Jaime violates this assumption. To make attachment nodes work more generally, each bone with attachments needs a target geometry. When the bone updates its transforms, it checks to see whether (1) the target geometry has the same parent as the attachments node and (2) whether its local transform is IDENTITY. If both these conditions are met (most models) the bone applies model transforms directly to the attachments node as before. If not, it adjusts the transform. My code assumes the parent of the attachment node is an ancestor of the target geometry. It also assumes all geometries with animated meshes have the same world transform. Formerly, getAttachmentsNode() failed if the spatial …
=> fix SkeletonControl.getAttachmentsNode() for odd models (such as Jaime)

README.md
Now that 3.1.0 is stable, the master README.md can stop pointing people toward the 3.0.10 release.
=> Version 3.1.0 is now stable, both for the SDK and the Engine itself.

jme3-core/src/main/java/com/jme3/font/BitmapFont.java, jme3-core/src/main/java/com/jme3/font/BitmapText.java, jme3-core/src/main/java/com/jme3/font/LetterQuad.java, jme3-core/src/main/java/com/jme3/font/StringBlock.java
The first explicitly set tab stop was always skipped. For all non-explicitly set tab stops it inserted a fixed spacing. This commit changes the behaviour so tabs are aligned to columns.
It also adds handling of tabs to BitmapFont.getLineWidth() which ignored tabs before.
[This was discussed in the forum.](https://hub.jmonkeyengine.org/t/tabs-in-bitmaptext/37495).
I made a pull request so this isn't forgotten.
Explanation of changes:
- BitmapFont: Added a constant DEFAULT_TAB_WIDTH. It is package private to not pollute namespace. Also added handling of tabs to getLineWidth().
- BitmapText: Only changed Javadoc. An important precondition is that the tab positions are sorted. I refrained from adding an Arrays.sort() call because the user shouldn't pay for what he doesn't need.
- LetterQuad: …
=> Fixes tab stops in BitmapText / BitmapFont (3.1)

jme3-core/src/plugins/java/com/jme3/texture/plugins/DDSLoader.java
Certain dds texture lack the DDSCAPS_TEXTURE-flag, but are still recognized by programs like IrfanView and can also be loaded in the engine.
This commit weakens the check for this flag: Instead of throwing an exception, a warning is logged.
See the attached dds file in the zip for an example of a dds texture that lacks that flag.
With this change, this texture can be loaded normally.
[tiles3.dds.zip](https://github.com/jMonkeyEngine/jmonkeyengine/files/907751/tiles3.dds.zip)
=> Weakens the flag tests in DDSLoader: some textures lack the DDSCAPS_TEXTURE flag

jme3-core/src/main/java/com/jme3/system/NullContext.java
The fields `timeThen` and  `timeLate` are static. If multiple Applications are launched in different threads in headless mode, sync fails. This can be fixed removing the static modifier of the fields.
=> NullContext thread safety

jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java, jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java
The current implementation of addAll / removeAll doesn't remove rest of the PhysicsControls if the spatial has a RigidBodyControl.
This pull request removes the else-branch so that add / remove is always called for the spatial. Add / remove is no longer present in the `if (spatial.getControl(RigidBodyControl.class) != null)` -branch to prevent the RigidBodyControl from being added / removed twice, thus it only handles joints.
=> Add/remove all PhysicsControls even when a RigidBodyControl is present

jme3-core/src/main/resources/joystick-mapping.properties
Note that it has only been tested on linux.
=> Added Xbox One S controller mappings

jme3-effects/src/main/java/com/jme3/water/WaterFilter.java
The original link was to a blog post that was turned into a wiki page. The blog post is no longer valid so pointed it to wiki instead.
=> Updated broken link to point to wiki.

jme3-core/src/main/java/com/jme3/scene/Geometry.java, jme3-core/src/main/java/com/jme3/scene/Mesh.java
Reflecting the updated Mesh.setPointSize() documentation in other parts of the class.
=> Mesh point doc fix

jme3-desktop/src/main/resources/com/jme3/app/SettingsDialog_zh_CN.properties, jme3-effects/src/main/java/com/jme3/water/WaterFilter.java
=> Fix issue #654

jme3-core/src/main/java/com/jme3/scene/control/LodControl.java
LodControl throws an exception when the spatial being added to isn't a geometry, however, when the controls is removed it calls setSpatial with a null value triggering the exception throw. Now checking for this null value case.
=> Fixed IllegalArgumentException when removing a LodControl from a spatial

jme3-effects/src/main/java/com/jme3/post/filters/BloomFilter.java
Noticed that this javadoc points to web documentation page that is not existing (probably from before migration), so I changed it to point to correct one.
=> fixing documentation link

jme3-core/src/main/java/com/jme3/renderer/Caps.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/system/AppSettings.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
I think we need to have a possibility to set core profile of most GL version, not only 3.2. Some drivers work correctly only in the case when you use a core profile, but when we use a core profile, we have limits to use features from higher versions. For example Intel Graphics on Linux, which can't use features from 3+ Open GL without a core profile. At this moment, we can use only core profile for the version 3.2, it isn't enough for example if you want to use geometry/tesselation shaders.
=> Added missed gl versions

jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/util/LWJGLBufferAllocator.java
I see java crashes from time to time with jemalloc when I have high concurrency with memory allocations, so I have added thread-safe implementation of the allocator by default, but if your application doesn't have high concurrency, you can disable thread-safe allocator using a system property to improve performance with it.
=> added support multi-threading allocations for LWJGL Buffer Allocator.

jme3-core/src/main/java/com/jme3/opencl/OpenCLObjectManager.java
This is the pull request that tries to fix issue #695.
- The call to Runtime.getRuntime().gc() every few frames is removed. The user should be forced to clear the native handles manually. But the automatic cleanup by the gc is still there.
- Added calls to Reference.clear() when an object is manually deleted.
=> Fix for OpenCLObjectManager

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
When the pbr material was introduced someone forgot to keep the instancing in mind which uses :
ViewProjectionMatrix
ViewMatrix
I added these.
=> Fixed: If Instancing is activated you only see shadows

jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java
Fixes `Format.Depth` support in OpenGL ES 2.0. The spec does not allow usage of `GL_DEPTH_COMPONENT` in `glRenderbufferStorage`:
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glRenderbufferStorage.xml
>internalformat
>Specifies the color-renderable, depth-renderable, or stencil-renderable format of the renderbuffer. Must be one of the following symbolic constants: 
GL_RGBA4, 
GL_RGB565, 
GL_RGB5_A1, 
GL_DEPTH_COMPONENT16, or
GL_STENCIL_INDEX8.
=> Fix FBO depth support in OpenGL ES 2.0

jme3-core/src/main/java/com/jme3/animation/Skeleton.java, jme3-core/src/main/java/com/jme3/animation/SkeletonControl.java
Fixes the annoying "Material instances cannot be shared when hardware skinning is used" error
=> Use MPOs for skinning

jme3-core/src/main/resources/Common/MatDefs/Misc/Sky.j3md, jme3-core/src/main/resources/Common/MatDefs/Misc/Sky.vert, jme3-examples/src/main/java/jme3test/texture/TestSkyRotation.java
The fix is simple: use WorldMatrixInverse instead of WorldMatrix to transform the normal vector in the vertex shader.
=> test and fix for issue #651 (inverted rotation in Sky.vert)

jme3-core/src/main/java/com/jme3/material/MatParam.java
Fixed NPE during saving MatParamOverride. I found that MatParamOverride can have a null value in some cases. For example, if you look at the constructor of SkeletonControl, you can see that this control creates two MPO with null values by default.
```
this.numberOfBonesParam = new MatParamOverride(VarType.Int, "NumberOfBones", null);
this.boneMatricesParam = new MatParamOverride(VarType.Matrix4Array, "BoneMatrices", null);
```
=> fixed NPE.

jme3-android/src/main/java/com/jme3/input/android/AndroidInputHandler14.java
More info can be [found here](https://hub.jmonkeyengine.org/t/some-keys-not-registering-keyinputevent-on-android/36747).
=> Fixed softkeyboard's (simulated) backspace not being recognized

jme3-core/src/plugins/java/com/jme3/shader/plugins/GLSLLoader.java
We didn't close readers of shader streams in the GLSLLoader. It provided some file lock leaks and then I couldn't change these files on windows without restarting jME application.
=> Fixed file lock leaks in GLSLLoader.

jme3-core/src/main/java/com/jme3/scene/Geometry.java, jme3-core/src/test/java/com/jme3/collision/CollideIgnoreTransformTest.java
Since there's a simple fix, it seems worth fixing.
This will change the behavior of Spatial.worldToLocal() and Spatial.localToWorld() when the Spatial is an  ignoreTransforms Geometry, but this strikes me as a positive change, making these methods' behavior more intuitive.
=> testcase & fix for issue #744: collideWith() versus setIgnoreTransform()

jme3-core/src/main/java/com/jme3/scene/Geometry.java
This PR changes the semantics of localToWorld() and worldToLocal() to identities in the case that ignoreTransform is set to true on the Geometry. I think this is more useful than applying a transform that isn't actually used in visualization. Also getWorldRotation(), getWorldScale(), getWorldTransform() and getWorldRotation() will return identities if ignoreTransform is set, which is consistent with localToWorld() if not perfectly intuitive.
I've confirmed that this change doesn't break CollideIgnoreTransformTest.  By itself, it doesn't fix issue #742 nor issue #743, though it should make both those issues slightly easier to fix.
=> Geometry: set worldTransform to identity if ignoreTranform is true

jme3-core/src/main/java/com/jme3/scene/AssetLinkNode.java, jme3-core/src/main/resources/com/jme3/asset/General.cfg, jme3-core/src/plugins/java/com/jme3/export/binary/BinaryLoader.java
I looked at the problem more deeply which was described by @NemesisMate here:
https://hub.jmonkeyengine.org/t/linkedassets-arent-sharing-meshes-when-imported/38494?u=nemesismate
So I think we need to use asset manager to load children of the asset linked node, but at this moment, BinaryImporter doesn't process correctly recursive loading models in this case, because the importer has a state which was inconsistent in my tests. I offer one of some solutions of this problem, of course, core team can have more correctly vision of this.
=> fixed asset linked node to reuse shared data between loaded models.

jme3-vr/src/main/java/com/jme3/input/vr/OpenVR.java
This allows apps to use the front mounted camera on the htc vive.
It's fairly unstable. It (the camera) can break down, in which case, disabling it in SteamVR, restarting SteamVR and enabling the camera again usually works.
I also get a crash first time I use it after SteamVR is launched. Error 113 (no frame available).
=> added functionality to use front mounted vive camera. 2nd try

jme3-vr/src/main/java/com/jme3/app/VRAppState.java
Currently, due to some changes I made while getting the GUI to work on the Rift, the main scene is being updated twice per frame while in VR, both on the Rift and SteamVR.
The loop used to iterate over `application.getViewPort().getScenes()`, and reverting to this fixed the issue on SteamVR.
On SteamVR, the main viewport is always empty while in VR, so removing the original version of the loop does not change anything. However, the main scene remained in the appliation viewport on the Rift, and as such removing the loop entirely fixes the issue.
See: [jME Forum post](https://hub.jmonkeyengine.org/t/jme3-vr-duplicate-calls-to-update/39479).
=> Prevent double-updating the main scene in VR

jme3-core/src/main/java/com/jme3/material/TechniqueDef.java, jme3-core/src/main/java/com/jme3/shader/Glsl100ShaderGenerator.java, jme3-core/src/main/java/com/jme3/shader/ShaderNodeVariable.java, jme3-core/src/plugins/java/com/jme3/material/plugins/ShaderNodeLoaderDelegate.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/materialdef/J3mdTechniqueDefWriter.java
1. Added default values for shader node variables.
2. Fixed using texture uniforms in vertex shader nodes.
3. Other small changes.
It's a branch from the PR https://github.com/jMonkeyEngine/jmonkeyengine/pull/759 without temp commits.
=> extended some things from shader node system.

jme3-core/src/plugins/java/com/jme3/material/plugins/ShaderNodeLoaderDelegate.java
Fixed detecting varyings during loading shader nodes in the case, when we have several output parameters with the same name but with different namespaces.
=> Fixed detecting varyings during loading shader nodes.

jme3-core/src/main/java/com/jme3/scene/control/LightControl.java
Fixed the problem with the reference to light, when we had incorrect reference to the light after loading/cloning spatial of this control.
Example:
I have a node with a point light and a light control with the reference to the light. When I load the node late, I have a cloned version of the node with a cloned version of the light and a cloned version of the light control, but the cloned control related to original light.
=> Fixed the problem with LightControl.

jme3-blender/src/main/java/com/jme3/scene/plugins/blender/textures/blending/TextureBlenderAWT.java
The issue was due to the texture blending with the object material. By default the material is gray (hence, a gray border). If the material color in blender is set to another color this is being the artifact's color. It can bee seen where the alpha in the texture isn't totally 0 or 1.
The current implementation weren't taking in account the material transparency when blending, so the fix is basically to use it just like blender does.
https://hub.jmonkeyengine.org/t/multiple-blender-importer-changes-fixes/38568
=> Fixed #652

jme3-blender/src/main/java/com/jme3/scene/plugins/blender/textures/TextureHelper.java
So there is a little bug in the blender importer:
When there is a texture which couldn't be loaded (in my case it was a hdr file which wasn't supported yet), the whole import procedure crashed with a NullPointerException (loadImage() returned null).
Judging by 0e340416fdf399aec25da9711b501f081232abd9 and the general intention it would be better to import a model without that texture then (The code was already prepared for result being null), so we just don't throw an Exception when the Texture Loading failed.
=> Blender Importer: Don't crash when a packed texture couldn't be loaded

jme3-core/src/main/java/com/jme3/scene/Geometry.java
Based on recent forum discussion at 
https://hub.jmonkeyengine.org/t/3-2-0-alpha-phase/39711/36
I'm rolling back PR 746. With this change, the emitter in TestMovingParticle appears to move again. I'm optimistic that this will also resolve glh3586's issue.
=> roll back PR 746 (worldTransform to identity) in master branch

jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java
Resolves #784 
I also changed the LinkedLists to ArrayDeques as they should be "faster", anyway somewhat more recommended. Minor formattings :( But only minor.
This is also not discussed in the forums.
=> Animated cursor support for LWJGL 3

jme3-blender/src/main/java/com/jme3/scene/plugins/blender/textures/ImageLoader.java, jme3-blender/src/main/java/com/jme3/scene/plugins/blender/textures/TextureHelper.java
See jMonkeyEngine/jmonkeyengine#727
When a blender file contained a hdr image, for example, the engine is able to load that as a texture, however the blender importer didn't do so.
This was because it didn't rely on the AssetManager to load images but instead called some Loaders directly.
This pull request fixes this by using the AM, which means any (even user-) registered AssetLoader can be used to load textures from blender files now.
I've made an API Change though: ImageLoader is now more of a TextureLoader. The AssetManager can only hand back Texture objects and since there is no point in converting: Texture->Image->Texture, I added loadTexture() and deprecated loadImage.
Technically loadImage could be removed as well since it's never called, but I kept it in for now.
=> Blender ImageLoader: Support Loading of HDR Files and many other

jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java, jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java
This pull request fixes the typo in the assert statement in the class PhysicSpace.
The typo is contained in both packages: jme3-bullet and jme3-jbullet but note that in first the whole method is commented out anyway.
=> Fixed typo in PhysicSpace described in issue #538

jme3-core/src/main/java/com/jme3/input/InputManager.java, jme3-lwjgl/src/main/java/com/jme3/input/lwjgl/LwjglMouseInput.java
It's not pretty code, but it improves the behavior of InputManager when LWJGL is in use and shouldn't break anything (that isn't already broken) when it isn't.
For the longer term, a cleaner solution might be to modify MouseInput.setInputListener() so that it returns the current mouse position.
Let me know what you think!
=> initialize InputManager.cursorPos to fix issue #792 (if using LWJGL)

jme3-core/src/main/java/com/jme3/input/KeyInput.java, jme3-desktop/src/main/java/com/jme3/input/awt/AwtKeyInput.java
This pull request adds the missing key code for the Print Screen key. 
However, LWJGL will interpret this key as SYSRQ unless the buttons are separated.
=> Adds missing key code for Print Screen (#682)

jme3-core/src/main/java/com/jme3/effect/shapes/EmitterSphereShape.java, jme3-plugins/src/xml/java/com/jme3/export/xml/DOMInputCapsule.java
=> [Taken]Fix issue #783 & #764

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java
This is added functionality for convenience, not a bug fix.
=> add getters to shadow renderers/filters for number of maps and sizes

jme3-core/src/main/java/com/jme3/audio/openal/AL.java, jme3-core/src/main/java/com/jme3/audio/openal/ALC.java, jme3-core/src/main/java/com/jme3/audio/openal/EFX.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL2.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL3.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL4.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLExt.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLFbo.java, jme3-lwjgl3/build.gradle, jme3-lwjgl3/src/main/java/com/jme3/audio/lwjgl/LwjglAL.java, jme3-lwjgl3/src/main/java/com/jme3/audio/lwjgl/LwjglALC.java, jme3-lwjgl3/src/main/java/com/jme3/audio/lwjgl/LwjglEFX.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwJoystickInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyMap.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java, jme3-lwjgl3/src/main/java/com/jme3/lwjgl3/utils/APIUtil.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGLExt.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGLFboEXT.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGLFboGL3.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglRender.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglGLDebugOutputHandler.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
A compacted version of this PR:
https://github.com/jMonkeyEngine/jmonkeyengine/pull/790
=> Refactoring upgrading lwjgl3 v.3

jme3-examples/src/main/java/jme3test/terrain/TerrainTestCollision.java
+ Change the initial camera position so that the terrain is visible.
+ Display a hint about the T key.
+ Fix a bug where the T key had to be pressed twice before it would work.
=> make TerrainTestCollision more user-friendly

jme3-core/src/main/java/com/jme3/animation/BoneTrack.java, jme3-core/src/main/java/com/jme3/animation/CompactArray.java, jme3-core/src/main/java/com/jme3/animation/SpatialTrack.java
This PR resolves issue #829 ("BoneTrack.clone() adds scales") and also cleans up a design issue that Paul raised in the wake of commit ce871d8.
=> simplify track cloning

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag
There was a singe s in glossiness which makes the whole shader not compile if you have a glossiness map set.
=> Fix a typo which makes pbr shader fail to compile when glossiness is enabled

jme3-core/src/main/java/com/jme3/util/MaterialDebugAppState.java
Reason:
If a shader-file has changed the application recognizes correctly the change, but the reload of the material actually reloads the old shader code instead of loading the new code. This is caused by the TechniqueDefault deep in the MaterialDefiniton.
Solution:
Instead of reuse the old MaterialDefinition let the AssetManager reload the MaterialDefinition.
=> fix JME issue 843 - Update MaterialDebugAppState.java

jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java
As stated at forum topic https://hub.jmonkeyengine.org/t/illegalstateexception-framebuffer-has-erronous-attachment-if-using-filterpostprocessor-or-shadows/40463 there's an error in the depth format defined for opengl ES 2.0 which should be GL.GL_UNSIGNED_SHORT instead of GL.GL_UNSIGNED_BYTE solving "Framebuffer has erronous attachment" IllegalStateException
=> Update GLImageFormats to fix framebuffer exceptions in android

jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java, jme3-core/src/main/java/com/jme3/texture/Image.java
Added texture formats R16F, R32F, RG16F, RG32F.
Added documentation for Format.Image elements.
=> Added Texture Formats

jme3-lwjgl3/build.gradle, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
=> Feature 871

.travis.yml
Currently the default OS X Build Environment at Travis has JDK10. However, it's tricky to make our build work with both JDK7 and JDK10 because 'javah' was replaced by 'javac -h'. Specifying "osx_image: xcode9.3" bypasses this issue for now.
=> avoid JDK10 so Travis CI can succeed on OSX

jme3-core/src/main/java/com/jme3/audio/AudioNode.java
This PR fixes some issues in the AudioNode that caused wrong velocity calculation when using velocityFromTranslation.
In short, when cloning the node, previousWorldTranslation wasn't reset to its initial value but cloned as reference, and the first velocity update was a subtraction with a NaN.
I've also modified the cloneFields method to reset the velocity to 0 if velocityFromTranslation is set, to prevent cloned nodes from preserving the velocity of the original in case they are never moved.
=> Fix AudioNode issues when using velocityFromTranslation and small refactoring

jme3-bullet/src/common/java/com/jme3/bullet/control/AbstractPhysicsControl.java, jme3-bullet/src/common/java/com/jme3/bullet/control/CharacterControl.java, jme3-bullet/src/common/java/com/jme3/bullet/control/GhostControl.java, jme3-bullet/src/common/java/com/jme3/bullet/control/RigidBodyControl.java, jme3-bullet/src/common/java/com/jme3/bullet/control/VehicleControl.java, jme3-examples/src/main/java/jme3test/bullet/TestIssue889.java
A cleaner setPhysicsSpace() method fixes the issue.
Applied the change to AbstractPhysicsControl, CharacterControl, GhostControl, RigidBodyControl, and VehicleControl (though only AbstractPhysicsControl and GhostControl were affected by the issue) in order to increase clarity and reduce the amount of unique code.
At some point in the past, the issue probably affected all physics controls. Whoever fixed RigidBodyControl somehow missed fixing AbstractPhysicsControl and GhostControl.
If all physics controls were based on AbstractPhysicsControl, there'd be a lot less cut-and-paste, and issues like this one would be easier to catch and fix globally. But such a change would break code that assumes certain physics controls are based on PhysicsCollisionObject.
=> test case and fix for issue #889

jme3-examples/src/main/java/jme3test/bullet/TestPhysicsRayCast.java
Increased the ray length from 1 to 50.
Rewrote the ray test for clarity.
Also provided prompt feedback in case no collision object was hit. Formerly there was a lag of up to 1 second before removal of the collision indication.
=> fix for issue #886

jme3-examples/build.gradle
The examples won't run on OSX with `-Djava.awt.headless=true` added as a JVM argument.
```
> Task :jme3-examples:run FAILED
Exception in thread "main" java.awt.HeadlessException
at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
at java.awt.Window.<init>(Window.java:536)
at java.awt.Frame.<init>(Frame.java:420)
at java.awt.Frame.<init>(Frame.java:385)
at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1758)
at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1833)
at javax.swing.JDialog.<init>(JDialog.java:272)
at javax.swing.JDialog.<init>(JDialog.java:233)
at jme3test.TestChooser.<init>(TestChooser.java:86)
at jme3test.TestChooser.main(TestChooser.java:451)
FAILURE: Build failed with an exception.
* What went wrong: …
```
=> Remove JVM arguments for OSX when running examples

jme3-core/src/main/java/com/jme3/effect/ParticlePointMesh.java, jme3-core/src/main/java/com/jme3/effect/ParticleTriMesh.java
Particles with a non random animation set currently only work for image sets with rows and columns equal, though you can set them separately and make them unequal. 3x4, 8x2 and so on give incorrect values for imgY. 
Forum link: https://hub.jmonkeyengine.org/t/particle-emitter-possible-bug/40971/2
Small change means you can have any number of rows and columns.
=> Particle tile number/UV calculation change

jme3-core/src/main/java/com/jme3/input/FlyByCamera.java
Changed riseCamera to use the up vector set with 'setUpVector(Vector3f upVec)' when pressing Q and Z which should make it go up/down.
Previously it was still travelling along the default up vector when pressing Q or W, despite rotating around the new up vector.
jMonkeyEngine/jmonkeyengine#617
=> FlyByCamera rise/fall behaviour (issue #617)

jme3-core/src/main/java/com/jme3/light/OrientedBoxProbeArea.java
The copy constructor of the OrientedBoxProbeArea wouldn't take the given transform into account. Now it does.
=> OrientedBoxProbeArea copy constructor fixed

jme3-bullet/src/common/java/com/jme3/bullet/debug/BulletCharacterDebugControl.java, jme3-bullet/src/common/java/com/jme3/bullet/debug/BulletGhostObjectDebugControl.java, jme3-bullet/src/common/java/com/jme3/bullet/debug/BulletRigidBodyDebugControl.java, jme3-bullet/src/main/java/com/jme3/bullet/util/DebugShapeFactory.java
The trick is to re-generate the debug mesh each time the scale of the collision shape changes.
=> fix for JME issue #887 (debug mesh ignores scaling)

.gitignore, appveyor.yml, gradle.properties, jme3-bullet-native/build.gradle, jme3-bullet-native/src/native/cpp/com_jme3_bullet_joints_HingeJoint.cpp
Found one incompatibility between v2.86.1 and v2.87: `btHingeConstraint::getMotorTargetVelosity()` was renamed to `getMotorTargetVelocity`.
Excluded 4 Bullet3 folders from the C++ compile. These are not needed for 2.87; excluding them should result in smaller libraries.
Added a `cleanZipFile` task to `jme3-bullet-native/build.gradle`. Unsure what should depend on it, but it'll be useful when someone wants to rebuild after changing Bullet versions, as I just did.
=> upgrade native Bullet to v2.87, which should fix issue #877

gradle.properties, jme3-bullet-native/src/native/cpp/com_jme3_bullet_PhysicsSpace.cpp
It looks like the AppVeyor build only happens when there are changes in the jme3-bullet-native directory. This PR will test that theory.
=>  PhysicsSpace.cpp: whitespace changes to trigger an AppVeyor build

jme3-core/src/main/java/com/jme3/app/state/AppStateManager.java, jme3-core/src/main/java/com/jme3/app/state/BaseAppState.java
that can optionally throw an exception if the state does not exist.
Inspired from @pspeed42  SiO2 GameSystemManager
https://github.com/Simsilica/SiO2/blob/df02d9dd08943744e6633e476dec38eb6eb44dd7/src/main/java/com/simsilica/sim/GameSystemManager.java#L264
=> Added AppStateManager.getState(class, failOnMiss) 

jme3-bullet-native/src/native/cpp/com_jme3_bullet_collision_PhysicsCollisionObject.cpp, jme3-bullet/src/common/java/com/jme3/bullet/control/RigidBodyControl.java, jme3-bullet/src/common/java/com/jme3/bullet/control/VehicleControl.java, jme3-bullet/src/main/java/com/jme3/bullet/collision/CollisionFlag.java, jme3-bullet/src/main/java/com/jme3/bullet/collision/PhysicsCollisionObject.java, jme3-bullet/src/main/java/com/jme3/bullet/objects/PhysicsRigidBody.java, jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsRigidBody.java
Implementation for PhysicsCharacter will be a separate PR.
=> implement setContactResponse(boolean) for PhysicsRigidBody (issue #964)

jme3-niftygui/build.gradle
Resolves #981 
The JME Nifty examples work. So does our project which uses Nifty quite heavily.
=> Updated Nifty to 1.4.3 and cleaned up the build

jme3-core/src/main/resources/Common/MatDefs/ShaderNodes/Common/Billboard.j3sn
I encountered the problem when trying to use the ArmatureDebugger on Android.
The shader compilation fails with a `cannot convert from 'int' to 'highp float'` error and this fixes it.
=> Fix Billboard ShaderNode cannot compile on Android

jme3-blender/src/main/java/com/jme3/scene/plugins/blender/BlenderLoader.java
The light is still being added, however, to the scene root node as this is the blender behavior and a wysiwyg is desired.
=> Fix #324. Blender importer now respects the lightNode pos in the graph

jme3-core/src/main/java/com/jme3/scene/Node.java, jme3-core/src/test/java/com/jme3/scene/SceneGraphTraversalTest.java
Calling `Node.depthFirstTraversal()` with `DFSMode.PRE_ORDER` doesn't produce the expected order of traversal.
It doesn’t pass the DFSMode to the recursive calls. Thus, the `PRE_ORDER` mode is only applied in the first call and will default to `POST_ORDER` further down the scenegraph.
Test code: https://pastebin.com/XCbwLSAS
The snipped also includes expected and actual results.
I've been told to also create an issue for this so others who encounter this problem will know about it, even if this expected behaviour.
But if this is expected behaviour, I think it should be mentioned in the Java Doc.
=> Fixes depth-first-traversal order in Node.

jme3-core/src/main/java/com/jme3/scene/UserData.java
Test case
src/test/java/unit/TestUserData.java
```java
package unit;
import com.jme3.scene.Node;
import com.jme3.scene.Spatial;
import org.junit.Test;
import junit.framework.TestCase;
public class TestUserData extends TestCase {
public static void userDataTest(Spatial sp, Object v) {
sp.setUserData("test",v);
assertTrue("UserData is null",sp.getUserData("test")!=null);
assertEquals("UserData value is different than input value",sp.getUserData("test"),v);
sp.setUserData("test",null);
}
@Test
public void testLong() throws Exception {
Spatial sp=new Node("TestSpatial");
userDataTest(sp,(Long)(long)(Math.random()*Long.MAX_VALUE));
}
@Test
public void testInt() throws Exception {
Spatial sp=new Node("TestSpatial");
userDataTest(sp,(Integer)(int)(Math.random()*Integer.MAX_VALUE));
}
@Test …
```
=> Add double short and byte support to UserData

jme3-core/src/test/java/com/jme3/math/Vector3fTest.java
Hi, 
In reference to a PR I made 3 days ago, it was mentioned that you might be interested in receiving additional tests for classes in jmonkeyengine. One such class was `com.jme3.mathVector3f`. This PR contains a suite of tests, again using  [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/datasheet) to assist with writing, that brings this class up to 97% coverage according the IntelliJ's internal coverage runner. 
I wasn't able to find any behaviours that struck me as obviously bugs, however. 
If you're still interested in such, i'll be taking a look at the other suggested classes in the coming days and writing some tests to increase their coverage, too.
=> Add tests for com.jme3.math.Vector3f

jme3-bullet/src/main/java/com/jme3/bullet/collision/shapes/CollisionShape.java, jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/CollisionShape.java
This adds a new public static method to set the default collision margin.
I'm unsure whether `jme3-jbullet` has any issue with 0 collision margin. To maintain consistency between libraries I modified both `jme3-bullet` and `jme3-jbullet`.
I ran all the physics tests in `jme3-examples` with both physics libraries and didn't notice any changes, except that `TestCcd` now works with `jme3-bullet`. Refer to issue #1043 for details.
=> fix issue #901 (collision margins initialized to 0)

jme3-core/src/main/java/com/jme3/material/MaterialDef.java, jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java
In j3md you should be allowed to define default textures like this
```        
Texture2D Texture -LINEAR: MinTrilinear MagBilinear /path/to/my/texture.dds
```
But the j3md loaded actually didn't set the default value for texture params. 
This pr fixes that.
=> J3MLoader Fix for default textures for j3md

jme3-core/src/test/java/com/jme3/scene/mesh/VirtualIndexBufferTest.java
This PR contains a suite of tests for `com.jme3.scene.mesh.VirtualIndexBuffer`, once again utilising [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/datasheet) to assist with the testing workflow. 
The rest of the requested classes and packages are on my radar; i'll be looking into them next. 
Specifically, `com.jme3.renderer.Camera` is the next class i'll be writing tests for. I hope these tests help!
=> Add tests for com.jme3.scene.mesh.VirtualIndexBuffer

jme3-core/src/main/java/com/jme3/renderer/opengl/GL3.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java, jme3-core/src/main/java/com/jme3/texture/Image.java, jme3-core/src/plugins/java/com/jme3/texture/plugins/DDSLoader.java, jme3-core/src/plugins/java/com/jme3/texture/plugins/DXTFlipper.java
From https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_compression_rgtc.txt
```
These formats are designed to reduce the storage requirements
and memory bandwidth required for red and red-green textures by
a factor of 2-to-1 over conventional uncompressed luminance and
luminance-alpha textures with 8-bit components (GL_LUMINANCE8 and
GL_LUMINANCE8_ALPHA8).
The compressed signed red-green format is reasonably suited for
storing compressed normal maps.
```
=> Add RGTC compressed formats

jme3-vr/src/main/java/com/jme3/input/vr/AbstractVRMouseManager.java, jme3-vr/src/main/java/com/jme3/input/vr/VRMouseManager.java
**Adds option to disable VR mouse cursor and thus enable the cursor on the desktop:**
Usecase: We need the cursor on the desktop because the application is operated by a different user who doesn't wear the VR goggles. Using the VRAppState would always disable the desktop-cursor. I added `VRMouseManager.setVRMouseEnabled()`. Default value for `vrMouseEnabled` is true, so it will behave the same by default.
**Fixes repeated attachment of mouseImage as scene to gui viewport (because its parent was always null):**
`AbstractVRMouseManager.update()` used `mouseImage.getParent()` to check if it's already attached. `mouseImage` is added as a scene to the gui viewport and will never have a parent, hence it was attached on every update call.
=> Adds option to disable VR mouse cursor

jme3-core/src/main/java/com/jme3/font/Letters.java, jme3-examples/src/main/java/jme3test/gui/TestBitmapFontAlignment.java
This PR fixes: #363 
The `totalHeight` was calculated using this line:
```java
totalHeight = Math.max(totalHeight, -l.getY1());
```
This always resulted in `totalHeight = 0`. I changed the calculation to using the lineHeight of the font and multiplying it by the line count.
```java
totalHeight = font.getLineHeight(block) * block.getLineCount();
```
Since the new height calculation needs the proper line count, I inversed the order of calling the methods in the `update()` method. First the line count is set, then the alignment is calculated.
I also added a test case with some different alignment settings: `TestBitmapFontAlignment`.
=> Calculate the total line height of a text

jme3-android-native/decode.gradle, jme3-android-native/openalsoft.gradle, jme3-bullet/build.gradle
This PR fixes the issue of class files being placed in the source tree during native binary builds. 
See #1072 for more info.
=> Fixed classes location while building natives (JDK11 Support)

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java, jme3-core/src/test/java/com/jme3/anim/AnimComposerTest.java
Returns an unmodifiable set when retrieving the available animation names and available animation clips instead of an unmodifiable collection. fixes: #1070
=> returns unmodifiable sets

jme3-android/src/main/java/com/jme3/app/DefaultAndroidProfiler.java, jme3-core/src/main/java/com/jme3/app/BasicProfiler.java, jme3-core/src/main/java/com/jme3/app/DetailedProfiler.java, jme3-core/src/main/java/com/jme3/app/state/AppStateManager.java, jme3-core/src/main/java/com/jme3/profile/AppProfiler.java, jme3-examples/src/main/java/jme3test/stress/TestShaderNodesStress.java
This is the implementation I use in spoxel to dig into performance within app states. The default profiler only gives timings for the App State Manager, but this code automatically profiles each of the app states added to the App State Manager. You can set further breakpoints within the update methods of an app state by calling:
`profiler.appSubStep("EffectState", "Run Client Effects");`
In this case "EffectState" is an app state and "Run Client Effects" is one of the profiling points i've set.
=> Added an easy way to add sub steps to the profiler

jme3-core/src/main/java/com/jme3/material/logic/SinglePassAndImageBasedLightingLogic.java, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
to control the brightness and color of the light probe. Very useful for simulating day/night light and any use case where you don't rebake the probes every time the ambient color needs to change.
=> Added ambient light support in PBR shader

jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.j3md, jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.vert, jme3-core/src/main/resources/Common/MatDefs/Light/SPLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/SPLighting.vert, jme3-core/src/main/resources/Common/ShaderLib/MaterialFog.glsllib, jme3-examples/src/main/java/jme3test/light/TestLightingFog.java
As per thread: https://hub.jmonkeyengine.org/t/add-fog-to-lighting-j3md/41873/6
I have added fog to multi-pass lighting.j3md/lighting.vert/lighting.frag for consideration.
I have not made any changes to SPLighting.vert/.frag or PBRLighting yet because the implementation would be the same, so once this has been approved, it can be ported to the rest of the materials.
I have also included a TestLightingFog in the jme-examples to test the three available fog-modes.
- Linear (simple, lightweight, useful on low-end and android devices)
- Exponential (medium - prettier but slightly more expensive than linear)
- ExponentialSquared (expensive compared to the previous two, but the best looking).
The user sets the parameter "UseFog" to enable fog, and must set a FogColor. 
- setBoolean("UseFog", …
=> Add support for fog in materials.

jme3-core/src/main/java/com/jme3/math/FastMath.java
As per discussion: https://hub.jmonkeyengine.org/t/map-range-function/41906/19
=> Add unInterpolateLinear to FastMath class

jme3-core/src/main/java/com/jme3/bounding/BoundingBox.java, jme3-core/src/main/java/com/jme3/bounding/BoundingSphere.java, jme3-core/src/main/java/com/jme3/cinematic/events/CameraEvent.java, jme3-core/src/main/java/com/jme3/light/LightProbe.java, jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/main/java/com/jme3/material/Technique.java, jme3-core/src/main/java/com/jme3/math/FastMath.java, jme3-core/src/main/java/com/jme3/math/Ray.java, jme3-core/src/main/java/com/jme3/renderer/Caps.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL.java, jme3-core/src/main/java/com/jme3/system/SystemListener.java, jme3-core/src/main/java/com/jme3/texture/Texture.java, jme3-core/src/main/java/com/jme3/texture/TextureCubeMap.java, jme3-core/src/main/java/com/jme3/util/ListSort.java, jme3-core/src/main/java/com/jme3/util/SortUtil.java, jme3-core/src/plugins/java/com/jme3/export/binary/ByteUtils.java, jme3-core/src/plugins/java/com/jme3/material/plugins/ConditionParser.java, jme3-core/src/plugins/java/com/jme3/material/plugins/ShaderNodeLoaderDelegate.java, jme3-networking/src/main/java/com/jme3/network/serializing/Serializer.java
Took way longer than I thought it would for "core" so I didn't get to "vr" yet, but OpenJDK 11 builds produce far fewer warnings after this cleanup. (OpenJDK 8 also tested to make sure new warnings don't appear...) I took the time to understand & preserve comment _intent_ as best I could, and test JavaDoc rendering in NB 11 to ensure doc is readable (before fixes some comments were showing completely misleading text in autocomplete help!). Also fixed a few broken links. 
Also here "ContextListener" was changed to SystemListener - I can't find any "ContextListener" other than in some comments (possibly also outdated), so I think this was a typo/mistake? 
If not and there is some "ContextListener" concept I'm unaware of, let me know and I'll correct. 
```java
/**
* The …
```
=> #1107-Fix Javadoc warnings in OpenJDK 9+ (jme3-core)

jme3-core/src/main/java/com/jme3/scene/shape/PQTorus.java, jme3-core/src/test/java/com/jme3/scene/shape/ShapeBoundsTest.java
Proposed fix for issue #1121. Since it's visual not sure if there's any good options for a test, but we'll have at least one which uses this shape when I update the pending physics GImpact shape test.
=> #1121-updateBound() call for PQTorus geometry updates

jme3-core/src/main/java/com/jme3/audio/AudioNode.java, jme3-core/src/main/java/com/jme3/input/AbstractJoystick.java, jme3-core/src/main/java/com/jme3/input/InputManager.java, jme3-core/src/main/java/com/jme3/input/Joystick.java, jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/main/java/com/jme3/texture/Texture.java, jme3-vr/src/main/java/com/jme3/input/vr/VRInputAPI.java, jme3-vr/src/main/java/com/jme3/input/vr/oculus/OculusVR.java, jme3-vr/src/main/java/com/jme3/input/vr/oculus/OculusViewManager.java, jme3-vr/src/main/java/com/jme3/post/CartoonSSAO.java, jme3-vr/src/main/java/com/jme3/system/jopenvr/CameraVideoStreamFrameHeader_t.java, jme3-vr/src/main/java/com/jme3/system/jopenvr/Texture_t.java, jme3-vr/src/main/java/com/jme3/system/jopenvr/TrackedDevicePose_t.java, jme3-vr/src/main/java/com/jme3/system/jopenvr/VREvent_DualAnalog_t.java, jme3-vr/src/main/java/com/jme3/system/jopenvr/VREvent_Property_t.java, jme3-vr/src/main/java/com/jme3/system/jopenvr/VROverlayIntersectionMaskPrimitive_t.java, jme3-vr/src/main/java/com/jme3/system/jopenvr/VROverlayIntersectionParams_t.java, jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanager/OSVR_ProjectionMatrix.java, jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanager/OSVR_RenderParams.java, jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanager/OSVR_ViewportDescription.java, jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanageropengl/OSVR_OpenResultsOpenGL.java, jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanageropengl/OSVR_ProjectionMatrix.java, jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanageropengl/OSVR_RenderParams.java, jme3-vr/src/main/java/com/jme3/system/osvr/osvrrendermanageropengl/OSVR_ViewportDescription.java, jme3-vr/src/main/java/com/jme3/system/osvr/osvrtimevalue/OsvrTimeValueLibrary.java, jme3-vr/src/main/java/test/TestInitHmd.java
Fixes 100+ Javadoc warnings in JDK 11 and this Javadoc NPE: 
```
> Task :jme3-vr:compileJava
Note: /home/lou/git/jmonkeyengine/jme3-vr/src/main/java/com/jme3/input/vr/openvr/OpenVR.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :jme3-vr:processResources
> Task :jme3-vr:classes
> Task :jme3-vr:jar
> Task :jme3-vr:javadoc
javadoc: error - An internal exception has occurred. 
(java.lang.NullPointerException)
Please file a bug against the javadoc tool via the Java bug reporting page
(http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
for duplicates. Include error messages and the following diagnostic in your report. Thank you.
java.lang.NullPointerException
at …
```
=> #1107 - Javadoc warning cleanup & Fix for JDK 11 Javadoc NPE

jme3-blender/src/main/java/com/jme3/scene/plugins/blender/textures/blending/TextureBlenderAWT.java, jme3-core/src/main/java/com/jme3/material/Material.java
when the image object has a ColorSpace value we pass it on, else we leave it at the default value.
=> fix for #1106

jme3-examples/src/main/java/jme3test/bullet/PhysicsTestHelper.java, jme3-examples/src/main/java/jme3test/bullet/shape/TestGimpactShape.java
As requested, here's a physics test using GImpactShapes. For the left side "floor" I used a MeshCollisionShape, the right side is a GImpactCollisionShape. All the dropping objects are GImpact. 
What's interesting is how different the floors behave. The mesh shape sometimes allows objects to fall through. For me it's _always_ on the 1st, 2nd, and 5th tests, and it's always the same objects at the same places. The GImpact floor never drops anything, and things seem to settle a little better. :neutral_face: 
It's actually 6 slightly different tests which repeat: 
* 1st Test: 10 solver iterations, large pot
* 2nd Test: 20 solver iterations, large pot
* 3rd Test: 30 solver iterations, large pot
* 4th Test: 10 solver iterations, small pot
* 5th Test: 20 solver iterations, small pot
* 6th Test: …
=> GImpactShape Test Added

jme3-core/src/main/java/com/jme3/scene/mesh/IndexBuffer.java, jme3-core/src/main/java/com/jme3/scene/mesh/IndexByteBuffer.java, jme3-core/src/main/java/com/jme3/scene/mesh/IndexIntBuffer.java, jme3-core/src/main/java/com/jme3/scene/mesh/IndexShortBuffer.java, jme3-core/src/main/java/com/jme3/scene/mesh/VirtualIndexBuffer.java, jme3-core/src/main/java/com/jme3/scene/mesh/WrappedIndexBuffer.java
As discussed in:
https://hub.jmonkeyengine.org/t/indexbuffer-suggestions-improvements-consistency/42022/4
* [Fix] createIndexBuffer(int, int): return IndexByteBuffer as well for
vertexCount < 128
* [Enhancement] Make put(int i, int value) fluid interface
* [Enhancement] Add relative put(int i) to allow easier chaining (parity
with other buffer implementations)
* [Enhancement] Add getFormat() to allow setting an IndexBuffer to a
Mesh directly without type inspection.
* [Fix] Fix WrappedIndexBuffer
API changes make it possible that IndexByteBuffer is now a valid  type
for outBuf, leverage the new getFormat() method to set the buffer to the
mesh regardless of its type.
=> jme-core: IndexBuffer fixes & API improvements

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/test/java/com/jme3/material/MaterialTest.java
When you have forced colorspace (-LINEAR) in the matdef and you set a texture param, it will work as expected, but if the value of the matparam is replaced with a different texture, the code that takes care of the colorspace switching will be skipped all together.
The unit test shows the issue in detail.
=> Fix forced colorspace in matdefs working only once.

jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java
When extracting native files (.dll), if an IOException of any kind is thrown, the Exception details were being lost. Instead this PR wraps the original Exception into the new (unchecked) one being created, so that a "Caused by" (IOException) is also reported.
=> Wrap potential IOExceptions during native file extraction

jme3-blender/src/main/java/com/jme3/scene/plugins/blender/textures/blending/TextureBlenderAWT.java
The CombinedTexture calls TextureBlenderAWT with null baseTexture,
the colorspacehandling of this is not null safe (but prior code is) this adds the missing if to prevent NPE in this case.
```
com.jme3.asset.AssetLoadException: An exception has occurred while loading asset: models/space/asteroids/asteroid_006_003.blend
at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:261)
at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:373)
at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:416)
at de.visiongamestudios.compiler.CompileApplication.internalcompile(CompileApplication.java:252)
at de.visiongamestudios.compiler.CompileApplication.lambda$1(CompileApplication.java:208)
at com.jme3.app.AppTask.invoke(AppTask.java:142) …
```
=> fix for NPE when being called from CombinedTexture with null baseImage

jme3-examples/src/main/java/jme3test/bullet/shape/TestGimpactShape.java
This just fixes an NPE for this physics test when it's being run by the jme3-examples app rather than directly executed.
=> Fix for NPE when running TestGImpactShape via TestChooser

README.md
The old link leads to the site for adults.
=> Update the link of the "Lightspeed Frontier".

jme3-examples/src/main/java/jme3test/gui/TestRTLBitmapText.java
The expected result  should be: 
```
to right test a is This
.text left 
```
but it displays: 
```
.text left to right test 
a is This 
```
=> Added TestRTLBitmapText for issue #1158

jme3-vr/build.gradle, jme3-vr/src/main/java/com/jme3/app/VREnvironment.java, jme3-vr/src/main/java/com/jme3/input/vr/HmdType.java, jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVR.java, jme3-vr/src/main/java/com/jme3/input/vr/openvr/OpenVR.java
This PR:
- Adds Valve Index to the list of recognized HMDs
- Brings the overall lwjgl version of the jme-vr module up to speed with the rest of the engine. This fixes OpenVR lwjgl backend.
- Removes Linux from the list of blacklisted OSes when lwjgl backend is used. In my testing, I got a picture inside the HMD on Linux, but it's cropped to be only the top half of the rendered view for some reason. Debugging this issue led me to believe that the version of OpenVR lwjgl 3.2.1 ships with is bugged on Linux, so this is unlikely to be fixed until we update lwjgl. On Windows it works fine.
_Also, is it just me or does git really think I deleted the whole files and then created them again?_
=> Some fixes in jme-vr

jme3-core/src/plugins/java/com/jme3/shader/plugins/GLSLLoader.java, jme3-core/src/test/java/com/jme3/asset/LoadShaderSourceTest.java, jme3-core/src/tools/java/jme3tools/shadercheck/ShaderCheck.java
glsllib is generally not recognized as proper glsl extension by editors.
=> Add .glsl extension to be used as a replacement for glsllib. 

jme3-examples/src/main/java/jme3test/terrain/TerrainTestCollision.java, jme3-terrain/build.gradle, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/picking/BresenhamTerrainPicker.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/picking/TerrainPicker.java, jme3-terrain/src/test/java/com/jme3/terrain/collision/BaseAWTTest.java, jme3-terrain/src/test/java/com/jme3/terrain/collision/BaseTest.java, jme3-terrain/src/test/java/com/jme3/terrain/collision/TerrainCollisionTest.java
by not adding "ghost" collisions to the CollisionResults (which weren't removed).
Improve TerrainPicking by allowing to do more ray tracing (previously, it stopped on the first hit, now it will stop on the first hit within range).
So: I got the report that terrain picking yields collision results even when no collision has happened. This was due to the way the code was structured: The user had to check the result of collideWith to know if a collision happened or not. This is wrong however, because the passed collisionResults struct could already contain results from previous operations (e.g. when picking the scenegraph recursively) and thus the limit check was wrong (it just picked the "closest" collision, which in that scenario makes no sense) and especially the desired result cannot be …
=> Fix and Improve TerrainPicking

jme3-niftygui/src/main/java/com/jme3/niftygui/JmeBatchRenderBackend.java, jme3-niftygui/src/main/java/com/jme3/niftygui/RenderDeviceJme.java
I tried various ways of rendering blendMode=”multiply” in NiftyGUI, and this is the one that worked best. This PR will need considerable testing to ensure it doesn't break anything.
=> fix for issue #99

jme3-core/src/main/java/com/jme3/system/JmeSystemDelegate.java, jme3-core/src/main/java/com/jme3/system/Platform.java, jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java
Add 2 new values to the `com.jme3.system.Platform` enum (and logic to `com.jme3.system.JmeSystemDelegate`) in order to distinguish Linux-on-ARM platforms. (LWJGL3 already supports such platforms.) Define paths to hypothetical BulletJme native libraries built for such platforms.
This is just a first step toward supporting Linux-on-ARM.
=> define 2 new Platform values for Linux ARM, register BulletJme lib paths

build.gradle, common.gradle
I also updated the "mockito-core" version for better compatibility with java11. 
The older version had some issues with java 11 and was preventing the "mergedJavadoc" task to succeed.
For anyone curious, here is the error with older mockito-core version:
```
mockito-core-1.10.19.jar(/org/mockito/internal/stubbing/answers/ThrowsExceptionClass.java):11: error: package org.objenesis does not exist
import org.objenesis.ObjenesisHelper;
1 error
> Task :mergedJavadoc FAILED
```
=> Fix issue #1176: mergedJavadoc task fails on java 11 

jme3-networking/src/main/java/com/jme3/network/service/rmi/RmiRegistry.java
jME's RMI registry uses an internal SharedObject class to track
metadata about objects that have been shared. The problem is that when
you retrieve the shared object, the RMI implementation mistakenly
attempts to cast the SharedObject holder to the class of the actual
shared object. This PR fixes that bug by casting the actual shared
object instead of the SharedObject holder.
=> Fixed ClassCastException in RMI implementation.

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java
=> AnimComposer: added getTime() and setTime() methods

build.gradle
Hello
This commit fixes the task `getPrebuiltNatives`.
Currently, this task is manually implemented as incremental. However, this implementation has some faults, because when the contents of one of the natives is changed, the task does not update the contents of the files properly.
So this commit fixes this task and splits it into two incremental tasks (i.e., `getNativesZipFile`, and `extractPrebuiltNatives`) that use the inputs and ouputs properties provided by gradle.
This commit removes a lot of custom logic (as it is already implemented by gradle).
=> Build: Fix the task 'getPrebuiltNatives'

.github/workflows/main.yml, gradle.properties, jme3-bullet-native-android/src/native/android/Android.mk, jme3-bullet-native/build.gradle
Update MacOS build: removed 32 bit support (since deprecated by apple). Update bullet library to the current master branch (needed for compatibility patch with recent clang).
=> Fix macos build.

jme3-core/src/main/java/com/jme3/renderer/Caps.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/renderer/opengl/TextureUtil.java
This pr overrides modifyTexture with a new method that allows to specify which part to copy from the source image. A workaround is implemented for gles, that doesn't provide GL_UNPACK_ROW_LENGTH.
The old method is kept for backward compatibility but deprecated in favor of the new one.
=> Improve support for subimage copying.

build.gradle
So we need to depend on the assemble target, as build only happens when the project is additionally tested, which it might be for CI, but not when including as a subproject (like the SDK did) and also not when calling `gradlew run`, which one would do when executing the jme tests.
I've taken the freedom to run an auto formatter on that snippet as well to fix whitespaces, I hope you don't mind. It just looked like minified js to me ;)
=> Fixes Bullet-Native Artifacts not containing natives when not building from cpp source and not using the build target.

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md, jme3-core/src/main/resources/Common/MatDefs/Shadow/PostShadowPBR.frag, jme3-core/src/main/resources/Common/MatDefs/Shadow/PreShadowPBR.frag
Added a PreShadowPBR.frag and PostShadowPBR.frag shader to support shadows for PBR materials with transparency, and updated techniques in PBRLighting.j3md to use them, as discussed in this thread
https://hub.jmonkeyengine.org/t/simarboreal-pbr-shaders-shadow-issue/42766/8
=> PreShadow & PostShadow Support for PBRLighting.j3md

jme3-core/src/main/java/com/jme3/system/AppSettings.java
Same policy here, especially since nobody commented on #1241 - Going to merge in 7 days.
I've also fixed a javadoc warning in the surrounding code, sorry for that :D
=> Fixes #1241 - Add a convenient Graphics Debug Option for the AppSettings

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
Should address issue #1267 
See forum discussion page : https://hub.jmonkeyengine.org/t/pbrlighting-has-two-postshadow-techniques/42778
=> Fixes #1267 - Removed extra PostShadow Technique from PBRLighting.j3md

jme3-niftygui/src/main/java/com/jme3/cinematic/events/GuiEvent.java, jme3-niftygui/src/main/java/com/jme3/cinematic/events/GuiTrack.java, jme3-niftygui/src/main/java/com/jme3/niftygui/InputSystemJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/JmeBatchRenderBackend.java, jme3-niftygui/src/main/java/com/jme3/niftygui/NiftyJmeDisplay.java, jme3-niftygui/src/main/java/com/jme3/niftygui/RenderDeviceJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/RenderFontJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/RenderImageJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/SoundDeviceJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/SoundHandleJme.java
One file was reformatted completely, sorry about that. It was so weirdly indented. Better to ignore white spaces.
Added Override annotations, finals, some cleanup and better null checks (getCurrentScreen in couple of files caused a warning).
=> Added Override annotations, finals, some cleanup and better null checks

jme3-core/src/main/java/com/jme3/system/AppSettings.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Same rules apply here: No answer after 7 days, I'll merge it.
Do note that JOGL has it's own Renderer and thus this AppSettings does not affect it (which is something I'd love to address).
Also the VR backend only supports two specific versions, be it because of specific requirements or because of not having the code written dynamically for this, so this remains untouched.
Also please watch the AppSettings file itself and not the diff: I've dragged LWJGL_OPENGL3 above OPENGL30 and then added 31 as a copy, thus it looks like changing OPENGL3 to 31.
=> Fixes #1251 - Support OpenGL3.1 on LWJGL2 and LWJGL3

jme3-core/src/main/java/com/jme3/system/AppSettings.java
This is much like the previous PR #1256 but this time it adds another two gems.
For platforms where a dedicated profiler isn't available or for a quick look, we actually already have a timing code, it was just hidden behind an AppSetting.
Might again be something for @mitm001 
I didn't try these settings out yet, but in #1278 there are a few potential problems on non lwjgl platforms, which will be fixed, though.
Edit: For the curious, here is a print out of the blue quad with Graphics Timing:
```
Feb 02, 2020 8:40:45 PM com.jme3.system.JmeDesktopSystem initialize
INFORMATION: Running on jMonkeyEngine 3.3.0-SNAPSHOT
* Branch: fix-lwjgl3-key-input
* Git Hash: 68fb1af
* Build Date: 2019-12-28
Feb 02, 2020 8:40:46 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFORMATION: LWJGL …
```
=> Add two convenience flags to AppSettings: GraphicsTrace and GraphicsTiming

jme3-core/src/main/java/com/jme3/asset/ImplHandler.java, jme3-core/src/main/java/com/jme3/system/JmeVersion.java
Sorry for that catchy PR title, but it's really just minor things I stumbled upon while working on these classes.
Talking about JmeVersion: When the file cannot be found, props.load(null) is called which throws a NPE, so the IOException only happens when reading is not possible for some reason, a very rare case.
=> Fix small things

jme3-examples/src/main/java/jme3test/niftygui/TestIssue1013.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Fixes the input issue mentioned in issue #1013 . It of course happens on LWJGL3 universally. Not a Nifty thing.
The inputs are very much tied to the window context.
=> Lwjgl3 restart input handle

jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Ok, sorry for the branch name, it was intended to fix issue #893 but it really doesn't. But it does make that issue better actually. Only the starting status (camera) is broken anymore there.
So what this does is:
- Fixes #1191 
- The fix is to add the callbacks later that they don't trigger on window creation process, there should be no need as it looks that we actually have the correct resolution and even the correct size canvas on HDPI situations, so everything should be fine
- Fixes the resizing altogether for LWJGL 3, it wasn't really working at all. At least for some configurations the window size callback doesn't seem to trigger at all... Windows 10 with NVIDIA seems to be at least said configuration
This is made in accordance of …
=> Fix for resizing the window (issue 1191)

jme3-core/src/main/java/com/jme3/environment/EnvironmentCamera.java
This commit allows EnvironmentCamera users to access the ViewPorts used
for rendering the snapshots. This allows incorporating screenspace and other
SceneProcessor-based effects into the snapshots as well as the scene geometry.
=> Expose ViewPorts

jme3-core/src/main/resources/Common/ShaderLib/GLSLCompat.glsllib, jme3-core/src/main/resources/Common/ShaderLib/PBR.glsllib
- GLSLCompat now implements mat3(mat4) and determinant() and inverse() for mat2 and mat3
- PBR.glslib uses this functions again instead of one-off workarounds
=> Fixing PBR on <= GLSL 130:

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
Background: https://github.com/MeFisto94/test-spotbugs/runs/560327969?check_suite_focus=true#step:5:1490
On MESA with Debug Mode or Assertions on, we get a GL_INVALID_ENUM at Line 510 (`getInteger(GL_MAX_GEOMETRY_SHADER_...)`).
I assume this is because this device supports SSBOs as an extension while still being on OpenGL 3.1. For most non-strict-real-gpus, SSBOs are only available with a much higher GL Version.
Anyway, this is my blind poke at this, I will re-run the above test, but I'd appreciate if someone finds some official source about when the Integers can be `getted`. 
Also note the `GL_ARB_geometry_shader_4`, I hope I did it right, it's not a `core extension` but an `extension` and I've read some stuff that those `_4` usually had a completely different API.
=> Fixes SSBO causing GL_INVALID_ENUM in Debug Mode

jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglAbstractDisplay.java
Sorry, I couldn't resist but to format the nearby code a bit, specifically the missing braces around Display.isCreated.
Sorry for the Review Request, Paul, but together with the issue, it should just be a matter of a few minutes.
=> Fixes #1319 - LWJGL2: start(true) should not freeze when context could not be initialized

jme3-examples/src/main/java/jme3test/bullet/TestQ3.java, jme3-examples/src/main/java/jme3test/post/TestMultiplesFilters.java, jme3-examples/src/main/java/jme3test/scene/TestSceneLoading.java, jme3-examples/src/main/java/jme3test/water/TestPostWaterLake.java, jme3-examples/src/main/java/jme3test/water/TestSceneWater.java
It fixes error of loading assets in examples.
=> Fixes error of loading assets

jme3-examples/src/main/java/jme3test/model/anim/TestSpatialAnim.java
Remove all deprecated class and migrate to the new animation system.
=> Migrate TestSpatialAnim to the new Anim class

jme3-core/src/main/resources/Common/ShaderLib/PBR.glsllib, jme3-examples/src/main/java/jme3test/light/pbr/TestIssue1340.java
fixes #1340 
Check if the NB_PROBES identifier is set, if not set a default value of 0.
If needed I can remove the test class as I don't think it's really 'helpful' in this case, as it only loads and displays a model.
=> Add check for NB_PROBES identifier and set default value

jme3-core/src/main/java/com/jme3/audio/AudioBuffer.java
See forum topic: 
https://hub.jmonkeyengine.org/t/solved-playing-audio-from-audiobuffer-in-audionode-causes-jre-to-die/43091/12
=> Fixes #1341: AudioBuffer.updateData only allows direct buffers

jme3-examples/src/main/java/jme3test/material/TestGeometryShader.java, jme3-examples/src/main/java/jme3test/material/TestTessellationShader.java
=> Set the minimum required OpenGL profiles for the geometry and tessellation shader test cases

jme3-core/src/main/java/com/jme3/system/AppSettings.java, jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java
This PR restores the "hooks" for using JOGL/JOAL as JMonkeyEngine's backend (instead of, say, LWJGL).
Said hooks were deleted when jme3-jogl was removed from the Engine by PR #1339. However, the situation has changed. As discussed [at the Forum](https://hub.jmonkeyengine.org/t/merged-dropping-jogl/43046/16), jme3-jogl could be hosted in JogAmp’s repository and maintained by the JogAmp community. Restoring the hooks should enable them to do so without forking JMonkeyEngine.
=> restore the JOGL/JOAL hooks

jme3-core/src/main/java/com/jme3/renderer/Camera.java
I've caught unpredictable behavior, when tried to use `Camera.contains`, then checked javadoc and found the reason why.
But javadoc is a bit outdated. This PR updates javadoc according observable behavior.
Old javadoc:
New javadoc:
Discussion: https://hub.jmonkeyengine.org/t/camera-contains-javadoc-outdated/43320
=> Camera#contains javadoc updated

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java
- add getters and setters that should be there just for symmetry reasons
- add missing javadoc (also on existing methods)
=> Adding getters/setters to AnimComposer

jme3-core/src/main/java/com/jme3/font/ColorTags.java
**Forum Discussion:** https://hub.jmonkeyengine.org/t/bitmaptext-colortags-negativearraysizeexception/43357
~~~
// just for this micro-demo.
BitmapFont font = new BitmapFont();
font.setCharSet(new BitmapCharacterSet());
font.setPages(new Material[0]);
//  in game it's loaded with AssetManager, of course
BitmapText text = new BitmapText(font);
text.setText("\\#FFF#");
~~~
Exception in thread "main" java.lang.NegativeArraySizeException
at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
at java.lang.StringBuilder.<init>(StringBuilder.java:101)
at com.jme3.font.ColorTags.setText(ColorTags.java:80)
at com.jme3.font.Letters.setText(Letters.java:68)
at com.jme3.font.BitmapText.setText(BitmapText.java:181)
~~~
// ColorTags.java:80
StringBuilder builder = new …
=> avoid NegativeArraySizeException if input string is "\\#FFF#"

jme3-core/src/main/java/com/jme3/scene/Mesh.java
This PR adds the ability to remove MorphTargets from Mesh. 
It also adds a helper function to get a single MorphTarget. 
~Trevor
=> Add ability to remove morph targets from mesh

jme3-core/src/main/java/com/jme3/input/event/KeyInputEvent.java
`repeating` flag still used and work well.
Discussion: https://hub.jmonkeyengine.org/t/keyinputevent-isrepeating-not-used-anymore/43318
=> KeyInputEvent javadoc corrected

jme3-core/src/main/java/com/jme3/math/Easing.java
The inputs supplied to InOut were unused, previously it always used the Quad ease functions declared earlier in the file.
=> Actually use ease functions input to InOut when applying

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
This is a fix for the GltfLoader to properly decode the percent-format uri references in the gltf model file. 
See https://hub.jmonkeyengine.org/t/jme-not-decoding-gltf-uri/43619/12 for discussion. 
Thanks,
Trevor
=> GltfLoader decodes file path uri

jme3-core/src/main/java/com/jme3/post/FilterPostProcessor.java, jme3-core/src/main/java/com/jme3/post/HDRRenderer.java, jme3-core/src/main/java/com/jme3/renderer/Renderer.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/system/NullRenderer.java, jme3-core/src/main/java/com/jme3/texture/FrameBuffer.java, jme3-effects/src/main/java/com/jme3/post/filters/TranslucentBucketFilter.java, jme3-vr/src/main/java/com/jme3/post/PreNormalCaching.java
This pr allows to exclude color copy when using Renderer.copyFrameBuffer. 
The old method is deprecated and redirected to the new one.
=> Allow depth-only copy with Renderer.copyFrameBuffer

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/texture/FrameBuffer.java, jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget.java
All the old methods are kept but deprecated.
=> Refactoring of framebuffer: Unified way to set render targets, added level field.

common.gradle
Set manifest automatic module name.
See: https://hub.jmonkeyengine.org/t/modularize-engine/43578
=> [fix]: add automatic module names to manifest

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
Updated frag shader to support reading the AmbientOcclusion value from the Red channel of the packed MetallicRoughness map. 
Adds a single boolean define that does this when set to true, so long as a metallic roughness map is also defined.
In response to this open issue: 
https://github.com/jMonkeyEngine/jmonkeyengine/issues/999
=> Packing AO in the metallic roughness map

.gitignore, .vscode/JME_style.xml, .vscode/settings.json
This PR adds the formatter settings discussed here https://github.com/jMonkeyEngine/jmonkeyengine/issues/1098 for vscode.
The xml file is also compatible with eclipse. I think we could add configurations for more common IDEs  (idea?) as long as they are self contained in identifiable folders (eg no .settings)
=> Add vscode config & formatter

build.gradle, license.txt
Since you have been adding those IDE specific settings... here is one from the home team :)
This re-adds the once deleted license.txt and adds it as the project license in Gradle properties. This works in Netbeans (jME SDK). Probably not in any other IDE. Whenever you add a new class file to any of the jME projects in NB, this license header will be added on top of the class.
=> Add project license header information

jme3-core/src/main/java/com/jme3/app/state/BaseAppState.java
The `terminate()` method does not exist, the correct one is `cleanup()`
=> Javadoc update, proposed fix for issue #1428

jme3-core/src/main/java/com/jme3/scene/mesh/IndexBuffer.java, jme3-core/src/main/java/com/jme3/scene/mesh/IndexByteBuffer.java, jme3-core/src/main/java/com/jme3/scene/mesh/IndexShortBuffer.java
Issue #1382 provides an example of how sloppy `IndexBuffer` allocations can cause bugs. To help uncover such bugs, this PR adds assertions to the `put()` methods of `IndexByteBuffer` and `IndexShortBuffer` in order to detect attempts to write out-of-range indices. (See the discussion at issue #1382 .)
I also modified the `createIndexBuffer()` method to record the expected number of vertices. This enables the assertions to test against the expected number of vertices (instead of 128 or 65536) for stronger checking.
=> add range-check assertions to the IndexBuffer.put() methods

jme3-core/src/plugins/java/com/jme3/export/binary/BinaryExporter.java
Ah, sorry for the white space changes.
Well, I was heavily optimizing our OpenKeeper's file operations. Basically trying to convert it to NIO world instead of the old I/O libraries. The results are stunning. There was still this place where I was relying on jME to write out the converted assets. And here it is.
We are writing 2015 files (615 MB) of j3o models with this BinaryExporter. Files range from few kilobytes to anywhere around 8 megabytes.
**Before: 110 seconds
After: 23 seconds**
The time includes a lot of stuff really, but this is the effect of this little change. This is not NIO, instead the old I/O. Still the fastest way to write a file in Java. See for example https://www.happycoders.eu/java/how-to-write-files-quickly-and-easily/#Performance_overview_writing_files.
Dunno what …
=> Use BufferedOutputStream to achieve maximum throughput

jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MExporter.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MOutputCapsule.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MRenderStateOutputCapsule.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MRootOutputCapsule.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/materialdef/J3mdExporter.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/materialdef/J3mdMatParamWriter.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/materialdef/J3mdTechniqueDefWriter.java
Related to: https://github.com/jMonkeyEngine/jmonkeyengine/pull/1434
These we write 1100 files (namely the Material files, j3m). The speedup is on the error margin of the measurement. The reason being that the usage really limits to these really small files (500 bytes...). It still should be less writes on the disk.
=> Use BufferedWriter

jme3-core/src/main/java/com/jme3/util/SkyFactory.java, jme3-core/src/main/resources/Common/MatDefs/Misc/SkyNonCube.j3md
A solution using 2 different material definition assets:
+ "Common/MatDefs/Misc/Sky.j3md" for cube-mapped skies (tested using `TestHoveringTank`)
+ "Common/MatDefs/Misc/SkyNonCube.j3md" for sphere-mapped skies (tested using `TestEverything`) and equirect-mapped skies (tested using `RefEnv`)
=> resolve issue #1414 (checkSetParam warning while creating sky)

jme3-lwjgl/src/main/java/com/jme3/audio/lwjgl/LwjglALC.java
This adds a series of retries (with increasing delays) in case the first attempt to `AL.create()` throws an `LWJGLException`.
=> mitigate issue #1383 (Could not locate OpenAL library) for LWJGL v2

jme3-core/src/plugins/java/com/jme3/export/binary/BinaryInputCapsule.java, jme3-core/src/plugins/java/com/jme3/export/binary/BinaryOutputCapsule.java
Fix the code error when checking UTF-8 data
let content = [0xE4, 0x8A, 0xBC], let `b = 0xE4` (1110 0100)
See this part:
````java
if (b < 0x80) {
// good
}
else if ((b & 0xC0) == 0xC0) {//   (0xE4 & 0xC0) == 0xC0     =====>  true
utf8State = UTF8_2BYTE;
}
else if ((b & 0xE0) == 0xE0) {//   (0xE4 & 0xE0) == 0xE0      =====>  true
utf8State = UTF8_3BYTE_1;
}
else {
utf8State = UTF8_ILLEGAL;
}
````
3 bytes UTF-8 data while always be treated as 2 bytes UTF-8 data.
=> [M]Fix issue#1436

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-plugins/src/test/java/com/jme3/scene/plugins/gltf/GltfLoaderTest.java, jme3-plugins/src/test/resources/gltf/box/boxWithEmptyScene.gltf
This is a fix for when the gltf exporter creates an empty scene node from blender. For example:
```json
"scenes" : [
{
"name" : "KB3D_NeoShanghai-Native",
"nodes" : [
5
]
},
{
"name" : "Scene"
}
],
```
This will make the exporter skip attempting to read the nodes from the empty scene, as there are no nodes in the scene.
=> Fix for gltf empty scene

jme3-lwjgl3/src/main/java/com/jme3/util/LWJGLBufferAllocator.java
Reported by Codacy
Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.
=> Move fields to the top in LWJGLBufferAllocator

jme3-core/src/main/java/com/jme3/light/LightProbe.java
When setting the type of a light probe to spherical, previously the center of the area wasn't set to the probe's position.
The code is untested, as I can't currently build the engine locally, so someone testing it would be welcome. The changes are minimal though, so chances of something breaking are small.
=> Fix spherical light probes always starting at 0,0,0

jme3-core/src/main/resources/Common/MatDefs/Light/Glow.frag
In the case of grayscale GlowMap, GlowColor can be used for changing color without manipulating glow texture.
Forum topic: https://hub.jmonkeyengine.org/t/glowcolor-unused-if-a-glowmap-is-specified/44002
=> Allow use of a GlowColor with GlowMap

jme3-core/src/main/resources/Common/MatDefs/Misc/Unshaded.frag, jme3-core/src/main/resources/Common/MatDefs/Misc/Unshaded.j3md
I added a small amount of code to the Unshaded.j3md and Unshaded.frag files to allow for desaturating the material's output color based on a float value, specifically for use in GUIs. 
Nearly all our GUI libraries use the Unshaded matdef for elements that are attached to the GUI node, and any custom gui elements will typically start from extending Unshaded if they need to do something in the shader, so adding this to Unshaded would alow all of our existent gui libraries to have desaturation functionality.
This should also not break any existing code, as nothing happens with this code unless the float value for desaturation gets defined for the material.
Following up on this thread https://hub.jmonkeyengine.org/t/how-to-desaturate-gui-element/43963
=> Add desaturation functionality to Unshaded.j3md

jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.vert
Fix for lighting vertex shader compile error when used with Fog and InstancedNode.  All credit to sailsman63 for the actual fix.  
More info:  https://hub.jmonkeyengine.org/t/shader-compile-error-with-instancednode-lighting-material-and-linearfog/44124/2
=> Fix for lighting vertex shader when used with Fog and InstancedNode.

jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java
This should fix the raycasting issue reported on the forum: https://hub.jmonkeyengine.org/t/npe-when-ray-casing-with-instancednode/44135
=> Ignore collision with InstancedGeometry

.github/workflows/main.yml
This came out of some of the testing I did regarding the [failing Github Actions builds.](https://hub.jmonkeyengine.org/t/jme-github-actions-failing/44180?u=sailsman63)
Hopefully, these changes will make troubleshooting such issues a little simpler in the future:
- The original failure erroneously seemed to be originating in the "Build Natives" step, though it was actually an error the Java build step. It is *not* necessary to build the full engine at this stage, as the result was merely discarded and then repeated during the OS matrix phase a little further down. I suspect that the line that caused this to happen was not intentional in the first place.
- When a single part of a build matrix fails, we really should let all variants complete, rather than bailing early. This allows us to …
=> Workflow updates

jme3-core/src/main/java/com/jme3/renderer/Camera.java, jme3-vr/src/main/java/com/jme3/app/VRApplication.java, jme3-vr/src/main/java/com/jme3/app/VREnvironment.java
Protect the no-arg constructor and use a different constructor to instantiate dummy cameras in jme3-vr.
=> resolve issue #1461 (protect no-arg Camera constructor)

jme3-core/src/main/java/com/jme3/material/logic/DefaultTechniqueDefLogic.java, jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java, jme3-core/src/main/java/com/jme3/scene/instancing/InstancedNode.java, jme3-examples/src/main/java/jme3test/scene/instancing/TestInstancedNodeAttachDetachWithPicking.java, jme3-examples/src/main/java/jme3test/scene/instancing/TestInstancedNodeAttachDetachWithShadowFilter.java
This should fix the issues with using InstancedGeometry and shadow filter reported on the forum: https://hub.jmonkeyengine.org/t/npe-with-instancednode-and-shadow-filter/44240
- Now if all instances of an InstancedGeometry are removed the InstancedGeometry will be properly detached as well and its internal buffer will be cleared.
- Instead of returning a null bound in InstancedGeometry (when it is empty) it will return a bounding box with zero extents. (following the same approach in Node class)
- Renamed `getActualNumInstances` to a more meaningful name `getNumVisibleInstances`
- Fixed a bug in visible instances count calculation that was causing `com.jme3.renderer.RendererException: Attempting to upload empty buffer (limit = 0), that's an error` when used with shadow filter.
- Two test …
=> Improve & bug fix InstancedGeometry and add new tests.

jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java, jme3-terrain/src/test/java/com/jme3/terrain/TestTerrainExporting.java
After loading a terrain from j3o, calling `TerrainQuad.getPatchSize()` will return 0, because "patchSize" is ignored when writing to file. This patch should fix it.
=> TerrainQuad: serialize "patchSize" field.

jme3-core/src/main/java/com/jme3/environment/EnvironmentCamera.java
Previously `EnvironmentCamera` didn't copy the default viewport's background color, but kept an alias to the pre-existing object. To avoid unintentionally altering the default viewport, it is necessary to clone the object.
`EnvironmentCamera` overrides the `backGroundColor` field during initialization, so setting it any sooner would have no effect. I decided to throw an `IllegalStateException` in that situation, to avert puzzling logic errors in apps.
=> resolve issue #1447 (no setter for EnvironmentCamera background color)

jme3-core/src/main/java/com/jme3/math/Quaternion.java, jme3-core/src/test/java/com/jme3/math/TestIssue1388.java
This PR corrects the documentation for 4 methods in `com.jme3.math.Quaternion`:
1. `fromAngles(float, float, float)`
2. `fromAngles(float[])`
3. the `Quaternion(angles)` constructor
4. `toAngles(float[])`
It also adds a test case which provides strong evidence that all 4 methods implement X-Z-Y rotation order.
=> testcase and fix for issue #1388 (Quaternion javadoc is misleading)

jme3-core/src/main/java/com/jme3/renderer/Renderer.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/system/NullRenderer.java
Added 2 methods to the `Renderer` interface to test whether a renderer is implementing gamma correction.
=> resolve issue #1074 (Renderer lacks getters for sRGB properties)

jme3-core/src/main/java/com/jme3/app/state/AppStateManager.java
Added profile tracking to AppStateManager for render and post render.
If the community thinks this is useful, feel free to merge, otherwise just close. I found it very helpful when tracing which app state was impacting my fps.
=> AppStateManager profiler for render and post render

jme3-core/src/main/java/com/jme3/scene/control/LightControl.java, jme3-examples/src/main/java/jme3test/light/TestLightControl2Directional.java, jme3-examples/src/main/java/jme3test/light/TestLightControl2Spot.java, jme3-examples/src/main/java/jme3test/light/TestLightControlDirectional.java, jme3-examples/src/main/java/jme3test/light/TestLightControlSpot.java
As @tlf30, @pspeed42 and I were working on #1443, it became apparent that the LightControl class wasn't entirely functional, particularly when it came to spot lights. This PR not only fixes that (including filling out the missing spotlight code in the lightToSpatial method), but also replaces some legacy code relating to directional lights from before version 3.
https://hub.jmonkeyengine.org/t/gltf-unlit-material-and-punctual-light-extensions/44132/29?u=markil3
Note that, when dealing with "world" coordinates when moving the spatial to the light, the rotations aren't always entirely accurate (the distance between the vectors can be as much as 4 units during testing). However, they appear close enough in debugging that I'm not concerned (Line 141 of TestLightControl2Spot).
=> Light control fix

jme3-core/src/main/java/com/jme3/anim/tween/action/Action.java
Sometimes (as in PR #1487) it would be convenient to directly alter the duration of an Action.
=> Action: publicize the setLength() method

jme3-networking/src/main/java/com/jme3/network/serializing/serializers/FieldSerializer.java
This patch allows serializing final fields for sending over the network.
Note this is possible due to obtaining reflection access to the final field otherwise it will throw IllegalAccessException.
https://github.com/jMonkeyEngine/jmonkeyengine/blob/c3e06bd507cb22de81cf91e095dca4ca2f29b4e1/jme3-networking/src/main/java/com/jme3/network/serializing/serializers/FieldSerializer.java#L104
=> FieldSerializer: do not ignore final fields.

jme3-core/src/main/java/com/jme3/input/FlyByCamera.java, jme3-core/src/main/java/com/jme3/renderer/Camera.java, jme3-examples/src/main/java/jme3test/renderer/TestAspectFov.java
As discussed in https://hub.jmonkeyengine.org/t/getter-setter-methods-for-attribute-fieldofview-in-the-class-camera-java-in-jme-3-4/44426/9 and mentioned in #1491, I added getter and setter methods for the field of view for perspective cameras (calling these methods on an orthogonal camera has no effect). These can be easily tested on any example that uses the FlyByCamera (i.e., 90% of them), but I added a new test for it just the same that actually displays the current FOV.
=> Adds getters/setters for Camera field of view and aspect ratio

jme3-core/src/main/java/com/jme3/app/state/ConstantVerifierState.java, jme3-core/src/main/java/com/jme3/font/BitmapFont.java, jme3-core/src/main/java/com/jme3/input/JoystickCompatibilityMappings.java, jme3-core/src/main/java/com/jme3/scene/instancing/InstancedNode.java, jme3-core/src/plugins/java/com/jme3/export/binary/BinaryExporter.java, jme3-examples/src/main/java/jme3test/gui/TestBitmapFontLayout.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/material/FbxMaterialProperties.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Or as the Netbeans inspector puts it, "Having private or package private types in a package API is useless."
Some instances were resolved simply by reducing the visibility of the field or method. In one instance, a field was only assigned once, so the assignment was made final. In a few instances, the field or method could never be used anywhere, so it was deleted.
=> visible methods and fields shouldn't depend on invisible classes

jme3-examples/src/main/java/jme3test/bullet/TestWalkingChar.java
This addresses another piece of issue #1452.
Once #1499 is fixed, we can replace
```java
ArmatureMask walkingMask = new ArmatureMask();
walkingMask.addBones(armature, "head", "spine", "spinehigh");
walkingMask.addFromJoint(armature, "hip.left");
walkingMask.addFromJoint(armature, "hip.right");
walkingMask.addFromJoint(armature, "uparm.left");
```
with something like
```java
ArmatureMask walkingMask = new ArmatureMask(armature)
.remove(shootingMask);
```
=> convert TestWalkingChar to the new animation system

jme3-android/src/main/java/com/jme3/app/state/VideoRecorderAppState.java, jme3-core/src/main/java/com/jme3/app/state/ScreenshotAppState.java, jme3-core/src/main/java/com/jme3/post/HDRRenderer.java, jme3-core/src/main/java/com/jme3/shadow/BasicShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/PssmShadowRenderer.java, jme3-desktop/src/main/java/com/jme3/app/state/VideoRecorderAppState.java, jme3-desktop/src/main/java/com/jme3/system/AWTFrameProcessor.java, jme3-effects/src/main/java/com/jme3/water/ReflectionProcessor.java, jme3-effects/src/main/java/com/jme3/water/SimpleWaterProcessor.java, jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget.java, jme3-examples/src/main/java/jme3test/post/TestRenderToMemory.java
When a `SceneProcessor` doesn't implement profiling, delete the unused private `prof` field and document the empty code block in the `setProfiler()` method.
=> cleanup of scene processors that don't implement profiling

jme3-examples/src/main/java/jme3test/model/anim/TestAttachmentsNode.java
This addresses another piece of issue #1452.
=> convert TestAttachmentsNode to the new animation system

jme3-core/src/main/java/com/jme3/input/InputManager.java, jme3-core/src/main/java/com/jme3/input/KeyInput.java, jme3-core/src/main/java/com/jme3/input/dummy/DummyKeyInput.java, jme3-desktop/src/main/java/com/jme3/input/AWTKeyInput.java, jme3-desktop/src/main/java/com/jme3/input/awt/AwtKeyInput.java, jme3-lwjgl/src/main/java/com/jme3/input/lwjgl/LwjglKeyInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyMap.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/Sync.java, jme3-lwjgl3/src/main/java/com/jme3/util/LWJGLBufferAllocator.java, jme3-vr/src/main/java/com/jme3/input/lwjgl/GlfwKeyInputVR.java
In this PR i am going to address the issues that are still stopping us from using lwjgl3 as default backend.
I'll report important changes below:
Ported the Sync class from lwjgl2 to provide a more accurate fps limiter
Fix for #1455
Workaround for #942
-------------------
The following will be addressed in a future PR
##~~Removed AWT calls from the core~~
~~The AWT context causes glfw to behave weirdly or break in some platforms. 
I moved all the classes that need an awt context into a dedicated package to be adapted for lwjgl3 or outright removed in the future. I removed the SettingsDialog calls from the core, and refactored it to be self contained in its own class. 
Now the splash screen needs to be launched manually after creating the AppSettings, to reproduce the old jme behaviour the …
=> Lwjgl3 impl patches

jme3-bullet/src/common/java/com/jme3/bullet/control/KinematicRagdollControl.java, jme3-core/src/main/java/com/jme3/cinematic/events/AnimationEvent.java, jme3-examples/src/main/java/jme3test/animation/TestCinematic.java, jme3-examples/src/main/java/jme3test/helloworld/HelloInput.java, jme3-examples/src/main/java/jme3test/input/TestCameraNode.java, jme3-examples/src/main/java/jme3test/input/TestChaseCamera.java, jme3-examples/src/main/java/jme3test/input/TestJoystick.java, jme3-examples/src/main/java/jme3test/post/TestDepthOfField.java, jme3-examples/src/main/java/jme3test/water/TestPostWaterLake.java
As NetBeans likes to point out, "Java language allows access to static fields thru instance variables, however this is often misleading and harder to read."
=> avoid accessing static fields through instance variables

jme3-core/src/main/java/com/jme3/animation/Bone.java, jme3-core/src/main/java/com/jme3/light/LightProbe.java, jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/main/java/com/jme3/renderer/RenderContext.java, jme3-core/src/main/java/com/jme3/scene/Mesh.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java, jme3-core/src/main/java/com/jme3/texture/Image.java, jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java, jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowFilterVR.java, jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowRendererVR.java
Many classes, fields, and methods were deprecated in v3.3 and earlier releases. Few (if any) of them have been deleted.  Many deprecated classes and method still work, so developers may be tempted to ignore deprecation warnings.
This PR deletes previously deprecated *setter* methods that are currently no-ops. Such methods are hazards because they fail silently. Developers might use them without realizing they are no longer implemented.
=> delete deprecated setters that are currently no-ops

jme3-core/src/main/java/com/jme3/cinematic/events/AnimEvent.java, jme3-examples/src/main/java/jme3test/animation/TestCinematic.java, jme3-examples/src/main/java/jme3test/animation/TestJaime.java
In the course of wrapping this up, I fixed a couple bugs in the very new `AnimEvent` class.
=> resolve issue #1452 (convert jme3-examples to new system)

jme3-effects/src/main/resources/Common/MatDefs/Post/FXAA.frag
Forum post: https://hub.jmonkeyengine.org/t/fxaa-filter-removes-transparency/42577/4
=> FXAA.frag: read alpha value from texture instead of passing constant 1

jme3-core/src/main/java/com/jme3/anim/tween/Tweens.java, jme3-core/src/main/java/com/jme3/app/state/BaseAppState.java, jme3-core/src/main/java/com/jme3/app/state/ConstantVerifierState.java, jme3-core/src/main/java/com/jme3/util/clone/Cloner.java, jme3-networking/src/main/java/com/jme3/network/base/DefaultClient.java, jme3-networking/src/main/java/com/jme3/network/base/DefaultServer.java, jme3-networking/src/main/java/com/jme3/network/base/KernelAdapter.java, jme3-networking/src/main/java/com/jme3/network/base/MessageListenerRegistry.java, jme3-networking/src/main/java/com/jme3/network/kernel/AbstractKernel.java, jme3-networking/src/main/java/com/jme3/network/kernel/tcp/SelectorKernel.java, jme3-networking/src/main/java/com/jme3/network/kernel/udp/UdpKernel.java, jme3-networking/src/main/java/com/jme3/network/message/SerializerRegistrationsMessage.java, jme3-networking/src/main/java/com/jme3/network/serializing/serializers/FieldSerializer.java, jme3-networking/src/main/java/com/jme3/network/service/AbstractHostedConnectionService.java, jme3-networking/src/main/java/com/jme3/network/service/ServiceManager.java, jme3-networking/src/main/java/com/jme3/network/service/rmi/RmiHostedService.java, jme3-networking/src/main/java/com/jme3/network/service/rmi/RmiRegistry.java, jme3-networking/src/main/java/com/jme3/network/service/rpc/RpcConnection.java, jme3-networking/src/main/java/com/jme3/network/service/rpc/RpcHostedService.java, jme3-networking/src/main/java/com/jme3/network/service/serializer/ClientSerializerRegistrationsService.java, jme3-networking/src/main/java/com/jme3/network/util/AbstractMessageDelegator.java, jme3-networking/src/main/java/com/jme3/network/util/SessionDataDelegator.java
Many JME loggers are declared package-private (with no access modifier). Probably these should all be `public`, `protected`, or `private`. Of these choices, `public` seems the safest.
In a few cases, I added the `final` modifier as well.
=> privatize package-private loggers

jme3-core/src/main/java/com/jme3/anim/AnimClip.java, jme3-core/src/main/java/com/jme3/anim/AnimComposer.java, jme3-core/src/main/java/com/jme3/anim/AnimTrack.java, jme3-core/src/main/java/com/jme3/anim/AnimationMask.java, jme3-core/src/main/java/com/jme3/anim/Armature.java, jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java, jme3-core/src/main/java/com/jme3/anim/Joint.java, jme3-core/src/main/java/com/jme3/anim/MatrixJointModelTransform.java, jme3-core/src/main/java/com/jme3/anim/MorphControl.java, jme3-core/src/main/java/com/jme3/anim/MorphTrack.java, jme3-core/src/main/java/com/jme3/anim/SkinningControl.java, jme3-core/src/main/java/com/jme3/anim/TransformTrack.java, jme3-core/src/main/java/com/jme3/anim/util/JointModelTransform.java
I left the `Weights` class unchanged on the assumption that it will soon be deleted.
=> jme3-core: add missing javadoc to the com.jme3.anim package

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
This attempts to avoid the `NullPointerException` reported by Pavl_G at the Forum:
https://hub.jmonkeyengine.org/t/engine-v3-4-0-beta-testing/44507/9
Since this appears to be related to #1408, I'd appreciate a review from @riccardobl
Stack trace from the reported crash:
```text
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
java.lang.NullPointerException
at com.jme3.renderer.opengl.GLRenderer.clearVertexAttribs(GLRenderer.java:2855)
at com.jme3.renderer.opengl.GLRenderer.renderMeshDefault(GLRenderer.java:3188)
at com.jme3.renderer.opengl.GLRenderer.renderMesh(GLRenderer.java:3219)
at com.jme3.material.logic.DefaultTechniqueDefLogic.renderMeshFromGeometry(DefaultTechniqueDefLogic.java:72)
at com.jme3.material.logic.SinglePassAndImageBasedLightingLogic.render(SinglePassAndImag …
```
=> GLRenderer: avoid NPE reported by Pavl_G

jme3-core/src/main/java/com/jme3/system/JmeSystemDelegate.java, jme3-core/src/main/java/com/jme3/system/Platform.java
We want to be able to distinguish ARM Macs from X86/PPC Macs so that, as soon as LWJGL v3.3 released, JME can also support such platforms.
=> address issue #1528 (distinguish ARM macOS/Windows from other platforms)

jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
As noted [at the Forum](https://hub.jmonkeyengine.org/t/question-about-new-animation-system-part-3-engine-v-3-4-0-beta1/44546/9), it's easy to create a `TransformTrack` without any translations or rotations. Since there are null checks in `getDataAtTime()`, such tracks can be useful. However, the `getTranslations()` and `getRotations()` methods lack null checks, leading to NPEs when applied to such tracks.
This PR would avoid NPEs on tracks without any translations or rotations.
=> TransformTrack: add null checks to getTranslations() and getRotations()

jme3-core/src/main/java/com/jme3/anim/Joint.java
Based on a proposal by Pavl_G at the Forum: https://hub.jmonkeyengine.org/t/question-about-new-animation-system-part-3-engine-v-3-4-0-beta1/44546/22
This makes `getAttachmentsNode()` and `getOffsetTransform()` accessible to subclasses. Currently these methods are used only in `SkinningControl` and `Armature` respectively.
=> Joint: make 2 methods accessible to subclasses

jme3-core/src/main/java/com/jme3/anim/TransformTrack.java, jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/SkeletonLoader.java
Even though Nehon's documentation made it clear that the no-arg constructor for `TransformTrack` was ONLY for serialization, he used it anyway in the Ogre XML loader. Owing to this contradiction, PR #1228 skipped this class.
After studying `TransformTrack` more closely, I'm convinced that the no-arg constructor is needed ONLY for serialization. In the spirit of PR #1228, this PR would protect it against accidental misuse.
Forum discussion at https://hub.jmonkeyengine.org/t/question-about-new-animation-system-part-3-engine-v-3-4-0-beta1/44546/9
=> TransformTrack: protect the no-arg constructor

jme3-core/src/main/java/com/jme3/app/SimpleApplication.java, jme3-examples/src/main/java/jme3test/renderer/TestContextRestart.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglDisplay.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
https://hub.jmonkeyengine.org/t/white-screen-on-context-restart/43866/28?u=markil3
Now most of the code that goes into initializing the renderer is now repeated every time. This is accomplished by moving most of the logic from the initContextFirstTime() methods into a new initContext(boolean) method. On the first boot, the code ultimately executes the same way. However, every context restart calls initContext(false) now as well. This will repeat all the code from before save for the creation of the GL and Renderer instances as well as input initialization.
At the moment, SimpleApplication now has a new default binding for the TAB key that restarts the context. This is to make it easier to test various examples, and I plan on removing it before we actually merge it.
This should solve …
=> Refactors the context restart code.

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java, jme3-core/src/main/java/com/jme3/cinematic/events/AnimEvent.java, jme3-examples/src/main/java/jme3test/animation/TestJaime.java
This solves a bug seen in `TestJaime` where anim events in the `Cinematic` were occasionally suppressed. This happened when 2 events were scheduled to play consecutively on the same layer and the later event's `onStart()` was invoked before the earlier event's `onStop()`. In this situation `onStop()` would remove the wrong action from the layer.
=> AnimEvent: solve bug where onStop() kills prior event on the same layer

jme3-examples/src/main/java/jme3test/app/state/TestAppStates.java, jme3-examples/src/main/java/jme3test/niftygui/StartScreenController.java, jme3-testdata/src/main/resources/Interface/Nifty/HelloJme.xml
Several things were broken here.
It was inappropriate for `TestAppStates` to use a default screen controller with "HelloJme.xml", because of course that screen controller does not implement the "quit()" method referenced in "HelloJme.xml". Also, "HelloJme.xml" specifies that the controller for its "start" screen should be an instance of `TestNiftyGui`. Furthermore, the "end" screen of "HelloJme.xml" is empty and therefore useless.
In order for `TestAppStates` and `TestNiftyGui` to cleanly share "HelloJme.xml", I added a class `StartScreenController` to serve as a screen controller for both apps.
I also deleted the "end" screen and re-purposed `quit()` to cleanly terminate the application.
=> solve issue #1542 (crash in TestAppStates)

jme3-examples/src/main/java/jme3test/asset/TestManyLocators.java
The new wiki uses different URLs than the old one, of course. But even with the correct URL (https://wiki.jmonkeyengine.org/docs/3.4/tutorials/_images/beginner/beginner-physics.png), it sends a 403 to Java's `URLConnection.getInputStream()`. A security feature of some kind?
So I decided to pick on github.com instead.
Also I found the inline comments confusing, so I re-phrased them.
=> solve issue #1543 (crash in TestManyLocators)

jme3-examples/src/main/java/jme3test/audio/TestMusicPlayer.java
I didn't figure out how to remove the horizontal slider. I simply disabled it by turning `sldBarStateChanged()` into a no-op. That fixed the `UnsupportedOperationException`.
To fix the `IllegalStateException`, I configured the `AudioNode` to be in ambient mode instead of positional mode.
=> solve issue #1544 (diagnostic messages from TestMusicPlayer)

jme3-core/src/main/java/com/jme3/math/Matrix4f.java
Much of the javadoc for the `Matrix4f` class is ambiguous, confusing, or downright incorrect. This PR attempts to specify, clarify, and correct it.
=> Matrix4f: improve the javadoc

jme3-examples/src/main/java/jme3test/collision/TestMousePick.java, jme3-examples/src/main/java/jme3test/model/shape/TestDebugShapes.java
+ Removed uses of `setLineWidth()` from `TestDebugShapes` and `TestMousePick`.
+ Privatized methods with no uses outside those classes.
+ Corrected misleading comments and updated the copyright dates.
=> resolve issue #1551 (OpenGLExceptions in jme3-examples)

jme3-core/src/main/java/com/jme3/anim/MorphControl.java
See: 
https://hub.jmonkeyengine.org/t/morphcontrol-question/44599?u=ali_rs & https://github.com/jMonkeyEngine/jmonkeyengine/issues/1548#issuecomment-839956156
=> MorphControl: serialize target list & add minor cleanups

jme3-examples/src/main/java/jme3test/bullet/TestAttachDriver.java
If you run the `TestAttachDriver` app (in jme3-examples) and press the spacebar twice, a diagnostic is issued:
```text
May 15, 2021 9:53:30 AM com.jme3.bullet.PhysicsSpace removeJoint
WARNING: Joint com.jme3.bullet.joints.SliderJoint@799f10e1 does not exist in PhysicsSpace, cannot remove.
```
The diagnostic indicates a bug in the app. This PR fixes the bug.
=> TestAttachDriver: don't remove the SliderJoint more than once

jme3-core/src/main/java/com/jme3/math/FastMath.java, jme3-core/src/test/java/com/jme3/math/FastMathTest.java
This pull request is to solve the issue #1349.
According to the definition of each axis and the process to get x, y, and z of Spherical coordinates from the method cartesianZToSpherical, the method sphericalToCartesianZ should be modified.
=> Fix the issue #1349

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/main/java/com/jme3/material/logic/SinglePassAndImageBasedLightingLogic.java, jme3-core/src/main/java/com/jme3/renderer/RenderContext.java, jme3-core/src/main/java/com/jme3/renderer/Renderer.java, jme3-core/src/main/java/com/jme3/renderer/TextureUnitException.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/system/NullRenderer.java, jme3-examples/src/main/java/jme3test/renderer/TestIssue37.java, jme3-examples/src/main/resources/jme3test/materials/TestIssue37.j3md
Instead of issuing a warning, a runtime exception is thrown, in order to avoid subsequent errors that might confuse diagnosis.
=> test and fix for issue #37 (warn when >16 textures are used)

jme3-core/src/main/java/com/jme3/audio/openal/ALAudioRenderer.java, jme3-core/src/main/java/com/jme3/audio/openal/ALC.java
Okay, finally something that it is worthy in my mind; recovering from audio failure! The implementation is based on: http://forum.lwjgl.org/index.php?topic=7081.msg37006#msg37006. Tested on Linux & Windows and seems to work.
To try it out:
- Use i.e. headphones when launching a jME app
- Disconnect headphones
New behavior in this case:
- The disconnection is detected fairly soon, audio renderer is re-created, creates some noise on the log
- Lost bytes in the buffer are not recovered :(
- New audio goes to the new default device
Old behavior in this case:
- No sound, ever, again
- Our app plays background tunes -> CPU spikes permanently as we start feeding audio to void
- Behavior of disconnected device is documented here: https://javadoc.lwjgl.org/org/lwjgl/openal/EXTDisconnect.html
- It …
=> Restart audio context if current device is "disconnected"

jme3-desktop/src/main/java/com/jme3/app/state/MjpegFileWriter.java
This optimizes the VideoRecorderAppState video file writing.
- The old version writes really small chunks, 4 bytes, even 1 byte chunks at times, PER FRAME!
- The new version uses buffer (8192 bytes) to write bigger chunks
- In reality much of the data written at a time (the individual frames) is a bigger chunk than 8192 -> written at one go
- Implements AutoCloseable, in my mind this is logical. Like writing a ZIP file etc. similar API
Basically this improves performance by eliminating some of the system calls.
New:
Old:
=> Buffered mjpeg file writer

jme3-core/src/main/java/com/jme3/math/Quaternion.java
Adds a small note to the javadoc for Quaternion.lookAt, to explain that the method may produce invalid results under some circumstances.
=> Add note to javadoc for Quaternion lookAt method

jme3-android-examples/src/main/java/org/jmonkeyengine/jme3androidexamples/MainActivity.java, jme3-core/src/main/java/com/jme3/animation/Pose.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL.java, jme3-desktop/src/main/java/jme3tools/converters/ImageToAwt.java, jme3-ios/src/main/java/com/jme3/renderer/ios/IosGL.java, jme3-lwjgl/src/main/java/com/jme3/opencl/lwjgl/LwjglContext.java, jme3-lwjgl/src/main/java/com/jme3/renderer/lwjgl/LwjglGLExt.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/MeshLoader.java
This PR renames method arguments in Java code, in order to clarify the purposes of those arguments. Mostly just better use of camelCase to indicate word boundaries.
There's plenty of room for further work along these lines.
=> rename some method arguments for clarity

jme3-core/src/main/java/com/jme3/scene/mesh/VirtualIndexBuffer.java, jme3-core/src/test/java/com/jme3/scene/mesh/VirtualIndexBufferTest.java
To be technical, there were actually 2 bugs:
+ The number of virtual indices for `LineLoop` mode should've always been even, but it was odd.
+ The last virtual index for `LineLoop` mode should've been 0 (the wrap-around), but that 0 was misplaced.
=> solve issue #1603 (incorrect VirtualIndexBuffer for a LineLoop mesh)

jme3-core/src/main/java/com/jme3/anim/MorphTrack.java, jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
The MorphTrack's current API has some inconsistencies with TransformTrack's API and some limitations as well (no ability to get/set the desired number of morph targets). This patch makes MorphTrack's API consistent with TransformTrack's API and adds a getter/setter for the number of morph targets.
=> Improve MorphTrack API

jme3-examples/src/main/java/jme3test/model/TestGltfLoading.java
in order to render the entire model without requiring the user to reposition the camera.
Requested in this comment: https://github.com/jMonkeyEngine/jmonkeyengine/issues/1089#issuecomment-929926676
=> TestGltfLoading: scale down Zophrac model

jme3-desktop/src/main/java/com/jme3/texture/plugins/AWTLoader.java
Introducing buffered stream for the ImageIO. Otherwise it reads in very small chunks and this is not desirable. Lots of calls. This is a performance improvement.
Old (starts with very small, and then proceeds with 512, maybe strides, dunno, variable read lengths):
New:
=> Wrap the input stream in BufferedInputStream

jme3-core/src/main/java/com/jme3/anim/MorphControl.java, jme3-core/src/plugins/java/com/jme3/export/binary/BinaryExporter.java, jme3-jbullet/src/test/java/com/jme3/jbullet/test/PreventBulletIssueRegressions.java
Reducing the number of expected warnings increases the chances that new warnings will be noticed.
=> suppress some warnings about unchecked conversions

jme3-core/src/main/java/com/jme3/util/SkyFactory.java
I was contacted privately about improving the readability of SkyFactory.java .
This PR attempts to apply standard Java formatting as discussed in PR #1098. Specifically:
+ single space before { and surrounding ?:
+ no line longer than 110 characters
+ 4-space indentation
+ blank line between methods
It also cleans up some other readability issues:
+ remove some excess whitespace
+ delete 2 stray asterisks
=> reformat source code of the SkyFactory class

jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
`jme3.anim.TransformTrack` throws generic runtime exceptions in 7 places. This PR changes those exceptions to more specific types, as recommended by Codacy and other static analysis tools.
This PR also checks for null arguments that would otherwise cause NPEs.
It also tries to make the exception message clearer.
=> throw better exceptions in TransformTrack

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
null pointer exception if the GLTF file references a node that doesn't exist.
I got this problem while tring to convert my GLTF file, i got 440 animations on the file with 3 animation that have joint index missmatch.
Maybe it's better to log the errors detail so the user have all the information to correct the error
=> avoid an NPE in GltfLoader.findChildren()

jme3-examples/src/main/java/jme3test/animation/TestJaime.java, jme3-examples/src/main/java/jme3test/model/anim/TestAttachmentsNode.java
Our best guidance for how to use `AnimMigrationUtils` is found in 5 example apps in jme3-test. However, 2 of those apps ( `TestJaime` and `TestAttachmentsNode`) assign return values from `migrate()` to local variables, giving the impression that the model might be converted by creating a new `Spatial`. 
In fact, `migrate()` converts models in place. Its return value is simply the argument. The assignments are redundant and also misleading, so this PR removes them from `TestJaime` and `TestAttachmentsNode`.
=> ignore return values from AnimMigrationUtils.migrate()

jme3-core/src/main/java/checkers/quals/DefaultLocation.java, jme3-core/src/main/java/com/jme3/bounding/BoundingSphere.java, jme3-core/src/main/java/com/jme3/effect/ParticleEmitter.java, jme3-core/src/main/java/com/jme3/input/Input.java, jme3-core/src/main/java/com/jme3/math/FastMath.java
Most of the javadoc in the Engine was written for old JDKs, resulting in warnings and errors when it is built using newer ones. Some sub-projects (such as "jme3-lwjgl3" and "jme3-networking") work around this by disabling doclint for JDK8+. Others, including "jme3-core", don't disable doclint.
This PR solves the 3 warnings and 7 errors that JDK 11 currently reports for jme3-core.
=> jme3-core:  solve 10 javadoc diagnostics from JDK 11

jme3-effects/src/main/java/com/jme3/post/filters/CartoonEdgeFilter.java, jme3-effects/src/test/java/com/jme3/post/filters/CartoonEdgeFilterTest.java
this PR solve issue [#1640](https://github.com/jMonkeyEngine/jmonkeyengine/issues/1640)
- remove unused import and extra empty lines from CartoonEdgeFilter
- add test case for CartoonEdgeFilter save and load
=> solve issue 1640 (CartoonEdgeFilter failing to override read() and write())

jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java
This addresses the issue by returning `null` if the key is unknown.
=> solve issue #1696 (missing check for GLFW_KEY_UNKNOWN)

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
This addresses issue #1612, a `NullPointerException` that occurs while importing a model from an invalid glTF file.
The proposed fix detects that the model's `SkinningControl` isn't added to any `Spatial`. In that case, it logs a warning and adds the control to the model's root node. This allows the import to proceed. However, the resulting model may be incorrect.
=> solve issue #1612 (NPE while importing from erroneous glTF)

jme3-android/src/main/java/com/jme3/renderer/android/AndroidGL.java, jme3-core/src/main/java/com/jme3/renderer/Renderer.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/system/NullRenderer.java, jme3-examples/src/main/java/jme3test/renderer/TestLineWidth.java, jme3-ios/src/main/java/com/jme3/renderer/ios/IosGL.java, jme3-ios/src/main/java/com/jme3/renderer/ios/JmeIosGLES.java, jme3-lwjgl/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java
This PR adds a `getMaxLineWidth()` method to the `Renderer` interface. It also adds a test to jme3-examples.
=> solve issue 1555 (add API to determine max line width)

jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
The javadoc for the `TransformTrack` class is confusing because it implies that the track is a "joint track" and also that the target is a "bone". But the track's target might actually be a `Spatial`, and (in the new animation system) bones are called "joints".
The javadoc is also padded with low-value information such as "a float array" and "of this track".
The javadoc also fails to document some important details:
+ which arguments can be null,
+ which getter returns an internal array, and
+ which setter creates an alias, 
This PR attempts to remedy these defects. Aside from rearranging fields, only comments are affected.
=> improve the TransformTrack javadoc

jme3-core/src/test/java/com/jme3/material/MaterialTest.java, jme3-core/src/test/java/com/jme3/material/plugins/J3MLoaderTest.java, jme3-core/src/test/java/com/jme3/material/plugins/LoadJ3mdTest.java
While reviewing some deprecation warnings, I discovered that 3 tests in jme3-core were using a deprecated version of `MockitoJUnitRunner`.
See https://stackoverflow.com/questions/41909538/mockitojunitrunner-is-deprecated
This PR corrects the issue.
=> jme3-core/src/test:  upgrade MockitoJUnitRunner from deprecated version

common.gradle, jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVR.java
@stephengold I have resolved the compilation issue with OpenVR inside jme-vr module, and updated the lwjgl version to 3.3.0.
I apologize, IDEA is trying to trim trailing whitespace, and no matter what I hit, I cannot get it to leave it alone. All other changes are whitespace changes, the only change is on line 233 (and the imports, which again IDEA does on its own...)
I guess this is a step in the right direction for the new style guide 🤣
=> Upgraded to LWJGL 3.3.0

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java, jme3-core/src/main/java/com/jme3/anim/AnimLayer.java
This PR consists mainly of refactoring to address issue #1566:
+ All the functionality of the `Layer` class was moved to a new top-level class named `AnimLayer`.
+ Functionality from `AnimComposer.controlUpdate()` was combined with `Layer.advance()` to create a new `AnimLayer.update()` method, resulting in a cleaner interface between the 2 classes.
+ The `AnimLayer` constructor takes 2 arguments instead of one, avoiding the need for an `AnimLayer.setMask()` method.
In addition to `AnimComposer.getLayer()`, some new capabilities were added:
+ `AnimComposer.getLayerName()` to find the name of a specified layer,
+ `AnimComposer.getLayerNames()` to enumerate all layer names, and
+ `AnimLayer.getMask()` to access a layer's mask.
`AnimComposer` is shorter and simpler now, but still more complex …
=> convert inner class Layer to a top-level class

jme3-examples/src/main/java/jme3test/bullet/TestAttachDriver.java, jme3-examples/src/main/java/jme3test/bullet/TestFancyCar.java, jme3-examples/src/main/java/jme3test/bullet/TestPhysicsCar.java
Static analysis by IntelliJ IDEA flagged this weird code. This PR makes the examples a tiny bit more readable.
=> jme3-examples:  simplify 6 unnecessary uses of unary minus

jme3-core/src/main/java/com/jme3/scene/Node.java
=> fix issue 1672 (inefficient logging in Node.java)

jme3-android/build.gradle, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnExceptionThrown.java, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnLayoutDrawn.java, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnRendererStarted.java
A maintenance PR for the `JmeSurfaceView`.
1) Optionally  binding the jmeSurfaceView to the android activity life cycle, it helps in `pausing`, `resuming` game and openGL context, and also helps in releasing memory when the game is destroyed.
2) Added new Listeners events : `OnLayoutDrawn()`, `OnRendererStarted()`.
4) Added a `DestructionPolicy` flag, which uses a static game state `GameState` to determine whether to destroy the game with the activity on exiting the activity or to keep it for a second use.
https://youtu.be/NBWyBzr_YXU
5) Optimizations to the `ErrorDialog` includes : showing a full error stack and `Copy crash log` button.
6) Added other flags such as : `showErrorDialog`, `exitOnEscPressed`, `showEscExitPrompt`.
7) Added a getter field for gl_es version.
8) Documentations …
=> SurfaceView Maintenance

jme3-core/src/plugins/java/com/jme3/export/binary/BinaryExporter.java
While investigating issue #1597, I uncovered inaccuracies in the definition of JMonkeyEngine's native binary format (J3O) presented in the class javadoc for `BinaryExporter`. Perhaps the format was modified at some point without updating the javadoc.
This PR corrects the inaccuracies. It also reformats and simplifies the class javadoc. It also adds comments to the `save()` method to match format items in the documentation with `write()` invocations.
=> clarify and update the J3O format description

CONTRIBUTING.md
The instructions in “CONTRIBUTING.md” say to “run ‘gradle build’”, which only works if you’ve installed particular versions of Gradle. Those instructions date back to 2014.
No instructions are ever foolproof. However, this PR tries to improve the odds of success for new users.
=> document the correct build procedure

jme3-vr/src/main/java/com/jme3/scene/CenterQuad.java
This addresses issue #1677, correcting the glaring inaccuracies and adding some useful details:
+ The resulting Mesh is indexed.
+ The resulting Mesh is in `Triangles` mode.
+ The resulting Mesh is static.
+ The resulting mesh includes normals.
+ The rectangle is axis-aligned.
+ Explain how `CenterQuad` differs from `Quad`.
=> CenterQuad:  new class javadoc

jme3-core/src/main/java/com/jme3/util/mikktspace/MikktspaceTangentGenerator.java
We just took this to use and what we use this for is to generate tangents for thousands of geometries. This said batch also gives out 300 lines of log... This particular line. So this is a small optimization. Follows the standard jME logging style.
=> Use static final logger

jme3-core/src/main/java/com/jme3/animation/AudioTrack.java, jme3-core/src/main/java/com/jme3/animation/CompactArray.java, jme3-core/src/main/java/com/jme3/animation/EffectTrack.java, jme3-core/src/main/java/com/jme3/asset/CloneableSmartAsset.java, jme3-core/src/main/java/com/jme3/effect/influencers/DefaultParticleInfluencer.java, jme3-core/src/main/java/com/jme3/effect/influencers/EmptyParticleInfluencer.java, jme3-core/src/main/java/com/jme3/effect/influencers/NewtonianParticleInfluencer.java, jme3-core/src/main/java/com/jme3/scene/instancing/InstancedNode.java, jme3-examples/src/main/java/jme3test/asset/TestAssetCache.java, jme3-plugins/src/main/java/com/jme3/scene/plugins/IrBoneWeightIndex.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/lodcalc/DistanceLodCalculator.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/lodcalc/PerspectiveLodCalculator.java
This addresses issue #1676, changing the return types of 13 `clone()` methods to the class in which they're declared.
This is technically an API change. The most likely breakage would be if external code extended one of these classes and overrode `clone()` with a method returning a supertype (such as `Object`). That would lead to a compile-time error due to incompatible return types.
=> more precise return types for 13 clone() methods

jme3-core/src/main/java/com/jme3/math/Vector3f.java
`Vector3f` may be the most crucial class for newcomers to learn, but unfortunately its javadoc is often vague, inconsistent, or even misleading.
This PR tries to raise the javadoc to a higher standard:
+ explicitly indicate which methods modify the current instance and which arguments are modified
+ explicitly indicate which methods return a new instance and which can return null
+ document which arguments cannot be null and what effect null arguments have
+ consistently refer to X, Y, and Z as "components" instead of "values" or "fields"
+ in cross-product methods, distinguish the right factor from the left factor
+ don't refer to calculations that modify the current instance as "internal"
+ don't refer to a fraction as a "percentage"
+ don't constantly tout the benefits of chaining
=> new javadoc for Vector3f

jme3-core/src/main/java/com/jme3/math/Quaternion.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxToJmeTrack.java
The `negate()` function in `Quaternion` doesn't follow the JME naming conventions. The other math functions that modify the current instance have "Local" in their names, but `negate()` doesn't.
Since this inconsistency could lead to buggy code, the old method is being deprecated, and a new method `negateLocal()` is being added. Unlike the old method, the new one returns `this` to allow function chaining.
=> deprecate Quaternion.negate()

jme3-core/src/main/java/com/jme3/math/Transform.java
This PR tries to raise the javadoc of `com.jme3.math.Transform` to a higher standard:
+ explicitly indicate which methods modify the current instance and which arguments are modified
+ explicitly indicate which methods return a new instance
+ document which arguments cannot be null and what effect null arguments have
+ consistently refer to `translate`, `rot`, and `scale` as "components"
=> new javadoc for Transform

jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget.java, jme3-examples/src/main/resources/TestMRT/MatDefs/ExtractRGB.frag, jme3-examples/src/main/resources/TestMRT/MatDefs/ExtractRGB.j3md, jme3-examples/src/main/resources/TestMRT/MatDefs/ExtractRGB.vert
Color Targets to render a scene separated by R, G and B values. It leaves out the complexity of the original test that was rendering a scene deferred.
As discussed in #1361 
Edit: Note to myself - I should remove the random color and disable the flyCam, so this can be asserted via [jme3-testing](https://github.com/MeFisto94/jme3-testing)
=> Rework Test MultiRenderTarget to actually show how to use multiple

jme3-core/src/main/java/com/jme3/math/Rectangle.java, jme3-core/src/main/java/com/jme3/scene/shape/RectangleMesh.java, jme3-examples/src/main/java/jme3test/input/TestCameraNode.java, jme3-examples/src/main/java/jme3test/input/TestChaseCamera.java, jme3-examples/src/main/java/jme3test/light/TestTransparentShadow.java, jme3-examples/src/main/java/jme3test/material/TestParallax.java, jme3-examples/src/main/java/jme3test/material/TestParallaxPBR.java, jme3-examples/src/main/java/jme3test/post/TestTransparentCartoonEdge.java, jme3-examples/src/main/java/jme3test/post/TestTransparentSSAO.java, jme3-examples/src/main/java/jme3test/texture/TestAnisotropicFilter.java, jme3-examples/src/main/java/jme3test/water/TestSceneWater.java
This RectangleMesh class was created based on the idea proposed at https://hub.jmonkeyengine.org/t/next-release-of-the-engine/44988/170
=> New RectangleMesh shape class

jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/WindowSizeListener.java
Added a `WindowSizeListener` for lwjgl3 which can be registered in `LwjglWindow` also refactored GlfwMouseInput to use this listener instead of directly registering a callback on GLFW as GLFW does not support multiple callbacks.
Also, we need to test to see if this possibly solves issue #1710.
=> jme3-lwjgl3: add a WindowSizeListener

jme3-core/src/main/java/com/jme3/math/Quaternion.java
Despite previous efforts, the `Quaternion` javadoc leaves much to be desired. I plan to clarify what the components represent, what the methods do, which methods modify the object, which arguments can be null, and so on, similar to what I did in PRs #1689 and #1706.
=> new javadoc for Quaternion

jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/test/java/com/jme3/material/RenderStateTest.java
The solves issue 1723 and adds a JUnit test to check for similar bugs in `RenderState` serialization and/or cloning.
=> fix and test for issue 1723 (more serialization bugs in RenderState)

jme3-core/src/main/java/com/jme3/math/Matrix3f.java
The `Matrix3f` javadoc used to be good for a few laughs:
+ "Matrix data is maintained internally"
+ referring to "the provided axis" when 3 axes are provided
+ referring to the current instance as "this matrix4f" and "this instance of Matrix4f"
+ a method claiming to return a null matrix in situations where it actually throws an NPE
+ failing to document the order of the factors for matrix multiplications
+ the `transpose()` method that modifies the current instance
+ the `multLocal()` method that doesn't modify the current instance
I've tried to make the javadoc less ridiculous and more informative.
Future work will include renaming some method arguments.
The good news is that `Matrix3f` isn't used much...
=> new javadoc for Matrix3f

jme3-core/src/main/java/com/jme3/anim/AnimLayer.java
```
java.lang.NullPointerException: Cannot invoke
"com.jme3.anim.tween.action.Action.setMask(com.jme3.anim.AnimationMask)"
because "this.currentAction" is null
at com.jme3.anim.AnimLayer.update(AnimLayer.java:209)
at com.jme3.anim.AnimComposer.controlUpdate(AnimComposer.java:391)
at com.jme3.scene.control.AbstractControl.update(AbstractControl.java:118)
at com.jme3.scene.Spatial.runControlUpdate(Spatial.java:743)
at com.jme3.scene.Spatial.updateLogicalState(Spatial.java:890)
at com.jme3.scene.Node.updateLogicalState(Node.java:228)
at com.jme3.scene.Node.updateLogicalState(Node.java:239)
```
Edit:
Link to the forum post: https://hub.jmonkeyengine.org/t/v3-5-0-beta-testing/45209/17
Edit 2:
To facilitate the understanding of the problem I also add the explanation of the fix discussed on the …
=> Fix NullPointerException in AnimLayer.update()

jme3-vr/src/main/java/com/jme3/app/VRConstants.java, jme3-vr/src/main/java/com/jme3/app/VREnvironment.java, jme3-vr/src/main/java/com/jme3/input/vr/AnalogActionState.java, jme3-vr/src/main/java/com/jme3/input/vr/DigitalActionState.java, jme3-vr/src/main/java/com/jme3/input/vr/VRInputAPI.java, jme3-vr/src/main/java/com/jme3/input/vr/VRInputType.java, jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVRAnalogActionData.java, jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVRDigitalActionData.java, jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVRInput.java
This leaves all the old stuff there (the oculus, osvr & other openvr) but focusses on the LWJGL openvr for the short term future (I guess OpenXR later on as the more long term future). I have ended up with a bit of a leaky abstraction where VRInputAPI wants to talk about openVr specific stuff like action manifests but I couldn't avoid that without requiring users to cast to LWJGLOpenVRInput which feels equally as bad (especially as LWJGLOpenVRInput is probably the only one that's going to be usable till OpenXR comes along)
This allows Jmonkey VR to use the actions manifest style VR (which is the non deprecated openVr api for mapping button presses to "stuff" in game).
An example action manifest might look like
```
{
"default_bindings": [
{
"controller_type": "oculus_touch",
"binding_url": …
```
=> #1734 actions based vr input

jme3-core/src/main/java/com/jme3/audio/openal/ALAudioRenderer.java
This attempts to solve issue #1699 by updating OpenAL's direct-filter parameter whenever the `DryFilter` changes, even if the filter itself has already been initialized.
I rearranged the `DryFilter` logic to make it slightly more readable.
=> AlAudioRenderer: update OpenAL state when dry filter is re-applied

jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglCanvas.java
Fixing OpenCL context null issue with LwjglCanvas. It is important that for Swing applications and with this fix, OpenCL won't be available in "simpleInitApp" and everything needs to be initialized inside the "simpleUpdate" with a boolean variable.
The discussion is in the following post:
https://hub.jmonkeyengine.org/t/opencl-context-for-lwjglcanvas-is-always-null/45213/3
=> LwjglCanvas: initialize OpenCL for LWJGL2

jme3-core/src/main/java/com/jme3/math/Vector2f.java
+ Explain what the class is used for.
+ Consistently refer to its "values" as "components".
+ Conform the javadoc to the project's preferred Java style.
+ Clarify which methods modify the current instance and which don't.
+ Clarify which arguments can be null and which can't.
+ Clarify the order of the factors in cross products.
+ Add javadoc to methods that lacked it.
+ Don't refer to fractions as percentages, which implies they go from 0 to 100!
=> new javadoc for Vector2f

jme3-examples/src/main/java/jme3test/renderer/TestBlendEquations.java, jme3-jbullet/src/main/java/com/jme3/bullet/util/DebugShapeFactory.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQuery.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQueryInt.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQueryObject.java
Starting with JDK 8, javadoc regards self-closing HTML tags as errors. This PR corrects 17 such errors.
=> avoid self-closing HTML tags in javadoc

jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java, jme3-core/src/main/java/com/jme3/bounding/BoundingBox.java, jme3-core/src/main/java/com/jme3/material/Technique.java
In javadoc, an unresolved cross reference (`@see` or `@link`) is an error that may suppress javadoc output.
This PR attempts to clear up the remaining unresolved refs. In most cases, I could guess what the author intended. In one case, I deleted the offending reference.
=> deal with unresolved references in javadoc

jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java
Fixes issue in setNormalRecalcNeeded() method where the bounding box containing recently changed points was always located with the assumption that the terrain's world location is 0,0,0 regardless of the terrain's actual world translation.
=> account for world transform in TerrainQuad.setNormalRecalcNeeded()

jme3-core/src/main/java/com/jme3/math/Vector2f.java
This greatly improves the efficiency of a method ... which is rarely used.
=> Vector2f: save 2 trig calculations in rotateAroundOrigin()

common.gradle
This solves an issue with eclipse based IDEs (eg. vscode with redhat's java plugin) that might mark circular dependencies as errors and stop the project from being imported. 
See image below:
=> Configure circular deps as warning on eclipse

jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
=> GlfwMouseInput:  scale mouse coords only if Retina AppSetting is true

jme3-core/src/main/java/com/jme3/asset/AssetKey.java, jme3-core/src/main/java/com/jme3/export/SavableClassUtil.java, jme3-core/src/plugins/java/com/jme3/material/plugins/ShaderNodeDefinitionLoader.java, jme3-core/src/tools/java/jme3tools/optimize/LodGenerator.java, jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java, jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsRigidBody.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglOffscreenBuffer.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-terrain/src/main/java/com/jme3/terrain/heightmap/FluidSimHeightMap.java, jme3-terrain/src/main/java/com/jme3/terrain/heightmap/HillHeightMap.java
This PR improves the readability of some logger and exception messages, mainly by separating words that were runtogether.
=> correct typos in diagnostic messages

jme3-core/src/main/java/com/jme3/system/AppSettings.java
This is the best GL version for compatibility and features, pretty much every system supports it now, so i think it should become the default.
The primary reason for this change is that by doing so we enforce by default a core profile that is supposed to respect the opengl standards and implement all its features, contrary to the compatibility profile (what we have now by default) that is implementation specific and might not respect standards, also it is not always in sync with the core profile in drivers, eg. the compatibility profile might stop at opengl 3.1 while the same driver might be opengl4 capable if the core profile is used.
This solves the issue of PBRLighting not working in MacOS due to missing textureCubeLod in the compat profile.
=> Use OpenGL 3.2 as default

jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Fix issue https://github.com/jMonkeyEngine/jmonkeyengine/issues/1745
=> Cross-platform fix for issue 1745 (mouse input scaling)

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/system/Platform.java
The line `getBoolean(GLExt.GL_FRAMEBUFFER_SRGB_CAPABLE_EXT)` in GLRenderer throw an opengl error 1280 (invalid enum) when the GL debugger is enabled. 
I am not sure why this is the case, however i believe it is safe to assume that every modern macos device is sRGB capable.
=> Fix error 1280 in MacOS when querying GL_FRAMEBUFFER_SRGB_CAPABLE_EXT

jme3-android/src/main/java/com/jme3/input/android/AndroidSensorJoyInput.java, jme3-core/src/main/java/com/jme3/animation/AnimControl.java, jme3-core/src/main/java/com/jme3/audio/AudioKey.java, jme3-core/src/main/java/com/jme3/font/BitmapText.java, jme3-core/src/main/java/com/jme3/font/Letters.java, jme3-core/src/main/java/com/jme3/math/Quaternion.java, jme3-core/src/main/java/com/jme3/math/Transform.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/scene/VertexBuffer.java, jme3-core/src/main/java/com/jme3/scene/control/CameraControl.java, jme3-core/src/main/java/com/jme3/util/BufferUtils.java, jme3-core/src/main/java/com/jme3/util/mikktspace/MikkTSpaceContext.java, jme3-core/src/main/java/com/jme3/util/mikktspace/MikktspaceTangentGenerator.java, jme3-examples/src/main/java/jme3test/light/TestLightControlDirectional.java, jme3-examples/src/main/java/jme3test/light/TestLightControlSpot.java, jme3-examples/src/main/java/jme3test/model/anim/TestAnimationFactory.java, jme3-examples/src/main/java/jme3test/post/TestSSAO2.java, jme3-examples/src/main/java/jme3test/stress/TestBatchLod.java, jme3-examples/src/main/java/jme3test/stress/TestLodStress.java, jme3-examples/src/main/java/jme3test/terrain/TerrainTestAndroid.java, jme3-examples/src/main/java/jme3test/tools/TestSaveGame.java, jme3-networking/src/main/java/com/jme3/network/kernel/udp/UdpKernel.java, jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/MeshLoader.java, jme3-terrain/src/main/java/com/jme3/terrain/heightmap/FaultHeightMap.java, jme3-vr/src/main/java/com/jme3/app/VREnvironment.java, jme3-vr/src/main/java/com/jme3/input/vr/AbstractVRMouseManager.java
Similar to #1712 and #1713, this addresses comments and javadoc that might be confusing due to issues such as words run together or missing punctuation.
=> clarify comments and javadoc

jme3-core/src/main/java/com/jme3/math/Vector3f.java
I've added these convenience multiplication and division methods that were missing from the Vector3f class, and did my best to also follow the same javadoc formatting that the rest of the similar methods have. 
Let me know if this looks alright and then I will do the same for Vector2f and Vector4f. And should I make the changes to Vector2f and Vector4f in this PR or should I make a new PR for each?
=> Add simple math methods to Vector3f

jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java
Per discussion at the Hub/Forum:  https://hub.jmonkeyengine.org/t/normalrecalccontrol-not-working-outside-of-sdk/44140/6
This makes the `fixNormals()` method public.
=> TerrainQuad:  publicize fixNormals()

jme3-core/src/main/java/com/jme3/scene/debug/SkeletonInterBoneWire.java, jme3-core/src/main/java/com/jme3/scene/debug/SkeletonPoints.java, jme3-core/src/main/java/com/jme3/scene/debug/SkeletonWire.java, jme3-core/src/main/java/com/jme3/scene/debug/custom/ArmatureInterJointsWire.java, jme3-core/src/main/java/com/jme3/scene/shape/Surface.java, jme3-core/src/test/java/com/jme3/scene/debug/TestCloneMesh.java, jme3-vr/src/main/java/com/jme3/scene/CenterQuad.java
This adds no-arg constructors to 6 `Mesh` subclasses and implements `read()` and `write()` methods as needed.
A few `final` fields had to be made non-final in order for reads to work.
In addition, the automated tests for skeleton-debug mesh serialization (in `TestCloneMesh`) were enabled.
=> Fix issue 1705 (serialize 6 mesh subclasses)

jme3-android/src/main/java/com/jme3/renderer/android/AndroidGL.java, jme3-bullet/src/common/java/com/jme3/bullet/control/KinematicRagdollControl.java, jme3-core/src/main/java/com/jme3/audio/Environment.java, jme3-core/src/main/java/com/jme3/bounding/BoundingBox.java, jme3-core/src/main/java/com/jme3/environment/util/EnvMapUtils.java, jme3-core/src/main/java/com/jme3/util/mikktspace/MikktspaceTangentGenerator.java, jme3-desktop/src/main/java/com/jme3/app/state/MjpegFileWriter.java, jme3-desktop/src/main/java/com/jme3/cursors/plugins/CursorLoader.java, jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/MeshLoader.java
=> rename more method arguments for clarity

jme3-core/src/main/java/com/jme3/math/ColorRGBA.java
I've noticed that ColorRGBA has a very useful .toVector4f() method (and also toVector3() method), which are great for instances where you need to do math with a ColorRGBA value returned from an ImageRaster, but there is no equally convenient method to convert that Vector back into a color afterwards, so I thought these 2 methods could be useful (specifically for Vector4f, but I added one for Vector3f too since there was also a toVector3f() method)
I initially thought of adding a new toColorRGBA() method to the Vector classes, but it seemed more appropriate to put this functionality into the ColorRGBA class here with set methods the way I did.
Any thoughts on this addition?
=> Add set methods and constructors to ColorRGBA that take in a Vector param

jme3-android/src/main/java/com/jme3/app/AndroidHarness.java, jme3-android/src/main/java/com/jme3/app/AndroidHarnessFragment.java, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java, jme3-core/src/main/java/com/jme3/app/LegacyApplication.java, jme3-core/src/main/java/com/jme3/post/SceneProcessor.java, jme3-core/src/main/java/com/jme3/renderer/RenderManager.java, jme3-core/src/main/java/com/jme3/system/AppSettings.java, jme3-core/src/main/java/com/jme3/system/SystemListener.java, jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanelsContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
This pr makes AppSettings.getWidth/Height return the size of the default framebuffer that is usually what is expected by user code. New methods to set and get window size are added.
The change is backward compatible.
The PR removes also a workaround that caused the engine to be aware of high DPI resolution after the second frame, in my tests waiting two frames has proven to be unnecessary.
EDIT: added rescale listener that propagates the high dpi scaling. Can be used for example to multiply the size of GUI elements.
=> Separate concept of window size from default framebuffer size

jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsCharacter.java
Discussion at https://github.com/jMonkeyEngine/wiki/pull/144 highlighted a need for javadoc to document the sign convention of `PhysicsCharacter.setGravity()`, which is perhaps non-intuitive.
=> PhysicsCharacter:  add javadoc for the setGravity() method

jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java, jme3-core/src/plugins/java/com/jme3/shader/plugins/GLSLLoader.java, jme3-core/src/test/java/com/jme3/shader/GLSLPreprocessorTest.java, jme3-core/src/test/resources/GLSLPreprocessorTest.testFOR.validOutput, jme3-core/src/tools/java/jme3tools/shader/Preprocessor.java
This can be used in shaders that need to repeat some code where loops cannot be used (eg. uniforms declaration).
See for example 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/ceb356462aeedf7769dced52e1d5572b01deca31/jme3-terrain/src/main/resources/Common/MatDefs/Terrain/TerrainLighting.frag#L20-L56
This code can be rewritten like so
```java
#for i=0..12 (#ifdef DIFFUSEMAP_$i $0 #endif)
uniform sampler2D m_DiffuseMap_$1;
#endfor
```
*Note: the first diffuse map (m_DiffuseMap) will be renamed in m_DiffuseMap0*
As you can see, it makes code much more readable and maintainable.
=> Add FOR macro to GLSL preprocessor and J3MD

jme3-core/src/main/java/com/jme3/input/controls/JoyButtonTrigger.java
The sourcecode for the `JoyButtonTrigger` class in jme3-core is confusing because it refers to the 2nd argument of the constructor as an axis ID. It is actually a button ID.
This PR corrects the javadoc and renames the method argument.
=> JoyButtonTrigger:  clarify that the constructor arg is not an axis ID

jme3-niftygui/src/main/java/com/jme3/cinematic/events/GuiEvent.java, jme3-niftygui/src/main/java/com/jme3/niftygui/InputSystemJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/JmeBatchRenderBackend.java, jme3-niftygui/src/main/java/com/jme3/niftygui/NiftyJmeDisplay.java, jme3-niftygui/src/main/java/com/jme3/niftygui/RenderFontJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/RenderImageJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/SoundDeviceJme.java, jme3-niftygui/src/main/java/com/jme3/niftygui/SoundHandleJme.java
similar to #1760, this PR brings the "jme3-niftygui" library closer to conformity with JME's preferred java style. Changes are limited to whitespace only.
=> whitespace changes in jme3-niftygui

jme3-examples/src/main/java/jme3test/animation/TestCinematic.java, jme3-examples/src/main/java/jme3test/app/state/TestAppStates.java, jme3-examples/src/main/java/jme3test/niftygui/TestIssue99.java, jme3-examples/src/main/java/jme3test/niftygui/TestNiftyExamples.java, jme3-examples/src/main/java/jme3test/niftygui/TestNiftyToMesh.java, jme3-niftygui/src/main/java/com/jme3/niftygui/NiftyJmeDisplay.java, jme3-niftygui/src/main/java/com/jme3/niftygui/RenderDeviceJme.java
This solves an issue with jme3-nifty not taking gamma correction into account. Nifty UIs specify colors by their red, green, and blue components. In order for jme3-nifty to display these colors property, it needs to know whether gamma correction is enabled or not.
If gamma correction is enabled, the application should specify `ColorSpace.sRGB`, in which case `ColorRGBA.setAsSrgb()` will be used to convert Nifty colors to JME colors.
If gamma correction is not enabled, the application should use the old constructor or specify `ColorsSpace.Linear`, in which case `ColorRGBA.set()` will be used to convert Nifty color to JME colors.
=> jme3-nifty should account for gamma correction

jme3-examples/src/main/java/jme3test/water/TestPostWater.java
Somehow `TestPostWater` was missed when updating jme3-examples to use the new `BitmapText` constructor.
=> TestPostWater:  avoid using the deprecated BitmapText constructor

jme3-core/src/main/java/com/jme3/effect/ParticleEmitter.java
```java
switch (meshType) {
case Point:
particleMesh = new ParticlePointMesh();
this.setMesh(particleMesh);
break;
case Triangle:
particleMesh = new ParticleTriMesh();
this.setMesh(particleMesh);
break;
default:
throw new IllegalStateException("Unrecognized particle type: " + meshType);
}
```
This piece of code is repeated 3 times in `ParticleEmitter` class, violating the DRY programming rule. So I encapsulated it in a separate method.
Fixed typo compatability -> compatibility
=> Refactoring of the initialization code of the 'particleMesh' variable.

jme3-core/src/main/java/com/jme3/system/AppSettings.java
AppSettings.java contains 2 javadoc tags referencing methods that don't exist. This PR corrects the references.
=> AppSettings:  solve 2 javadoc diagnostics

jme3-core/src/main/java/com/jme3/app/SimpleApplication.java
In both cases, "applications" is in the possessive case, so an apostrophe is required for clarity.
=> SimpleApplication:  correct 2 typos in the javadoc

jme3-android/src/main/java/com/jme3/app/AndroidHarness.java, jme3-android/src/main/java/com/jme3/app/AndroidHarnessFragment.java, jme3-core/src/main/java/com/jme3/anim/Armature.java, jme3-core/src/main/java/com/jme3/animation/CompactArray.java, jme3-core/src/main/java/com/jme3/asset/ImplHandler.java, jme3-core/src/main/java/com/jme3/cinematic/events/SoundEvent.java, jme3-core/src/main/java/com/jme3/math/Spline.java, jme3-core/src/main/java/com/jme3/shader/Uniform.java, jme3-core/src/main/java/com/jme3/system/AppSettings.java, jme3-core/src/main/java/com/jme3/system/JmeSystem.java, jme3-core/src/main/java/com/jme3/util/BufferAllocatorFactory.java, jme3-core/src/tools/java/jme3tools/optimize/TextureAtlas.java, jme3-desktop/src/main/java/com/jme3/app/AppletHarness.java, jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java, jme3-examples/src/main/java/jme3test/TestChooser.java, jme3-examples/src/main/java/jme3test/awt/AppHarness.java, jme3-examples/src/main/java/jme3test/awt/TestApplet.java, jme3-examples/src/main/java/jme3test/awt/TestCanvas.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-networking/src/main/java/com/jme3/network/message/SerializerRegistrationsMessage.java, jme3-networking/src/main/java/com/jme3/network/serializing/serializers/CollectionSerializer.java, jme3-networking/src/main/java/com/jme3/network/serializing/serializers/MapSerializer.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Removes deprecated code and some warnings.
Compiled with JDK 11 (-Xlint:deprecation)...
- Class.newInstance() was deprecated in Java 9, I replaced it with Class.getDeclaredConstructor().newInstance(); (get empty constructor and call it)
- new Float() is deprecated, unnecessary boxing
- new JsonParser() is deprecated, use the static methods instead
=> avoid use of deprecated methods (mostly Class.newInstance())

jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxAnimCurveNode.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxToJmeTrack.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/node/FbxNode.java
This changes a print statement in `FbxAnimCurveNode.java` to a logger call so it doesn't contaminate output.
=> Remove print statements from FBX plugin

jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyQuad.frag, jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyQuad.j3md, jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyQuad.vert, jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyQuadGrad.frag, jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyQuadGrad.j3md, jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyQuadGrad.vert, jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyTex.frag, jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyTex.j3md, jme3-niftygui/src/main/resources/Common/MatDefs/Nifty/NiftyTex.vert, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/HeightBasedTerrain.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/HeightBasedTerrain.j3md, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/HeightBasedTerrain.vert, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/SPTerrainLighting.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/SPTerrainLighting.vert, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/Terrain.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/Terrain.j3md, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/Terrain.vert, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/TerrainLighting.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/TerrainLighting.j3md, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/TerrainLighting.vert, jme3-vr/src/main/resources/Common/MatDefs/VR/OpenVR.frag, jme3-vr/src/main/resources/Common/MatDefs/VR/OpenVR.vert, jme3-vr/src/main/resources/Common/MatDefs/VR/OpenVR15.frag, jme3-vr/src/main/resources/Common/MatDefs/VR/OpenVR15.vert, jme3-vr/src/main/resources/Common/MatDefs/VR/PostShadowFilter.frag
Added "GLSL150" to matdefs and `#import "Common/ShaderLib/GLSLCompat.glsllib"` to shaders. Not certain I got them all.
=> solve issue #1780 (built-in matdefs/shaders lack core-profile support)

jme3-core/src/main/java/com/jme3/renderer/RenderContext.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
This is an issue in the way glDrawBuffer/glReadBuffer are used in the engine: the state is cached as if it was a global state change, while they actually [change the current bound framebuffer's state ](https://www.khronos.org/opengl/wiki/Framebuffer#Draw_color_buffers).
The issue prevents FrameBuffer.setTargetIndex(int) from working correctly in some circumstances. 
I am leaving this open for a while to make sure this patch doesn't have any weird side effect before merging it.
=> Fix draw/read buffer selection for framebuffers (FrameBuffer.setTargetIndex(int))

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/texture/FrameBuffer.java
This PR solves the issue #1788 by adding a way to hint the renderer to generate or not generate mipmaps for a specific framebuffer by using:
`FrameBuffer.setMipMapsGenerationHint(true);`
`FrameBuffer.setMipMapsGenerationHint(false);`
If no hint is given it will fallback to the default that is configurable with
`GLRenderer.setGenerateMipmapsForFramebuffer(boolean)`
and is true by default.
Leaving everything to its default will maintain the current behavior.
=> Add toggleable framebuffer mipmaps generation. Fix #1788

jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Based on the observations documented in #1793, the key issue is that transitions between windowed mode and fullscreen mode in LWJGL v3 don't always generate `reshape()` callbacks. This spoils GUI layouts that need updating each time the dimensions of the graphics context change. The user sees a layout generated for a different-sized framebuffer.
(There's also an issue with the initial `reshape()` callback, which occurs on Windows, but not Linux, when the initial context is created. However, that's an easy issue for apps to work around.)
The key issue manifests differently on Linux than on Windows:
+ On Linux LWJGL v3, windowed-to-fullscreen causes a callback, but not fullscreen-to-windowed.
+ On Windows LWJGL v3, neither transition causes a callback.
This PR proposes that jme3-lwjgl3's …
=> work around missing reshape() callbacks from LWJGL v3 (issue #1793)

jme3-core/src/main/java/com/jme3/app/LegacyApplication.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-vr/src/main/java/com/jme3/app/VRApplication.java, jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglContextVR.java
Invoking `AppSettings.getBoolean()` directly is error-prone. Ideally, its use would be limited to custom settings.
This PR refactors some invocations to use special-purpose methods already defined in the `AppSettings` class.
=> refactor to avoid invoking AppSettings.getBoolean() directly

jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java
This exception is an android native exception issue #1804 , raised due to trying to use the nullified object before being recycled : 
```java
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.jme3.hellojmesurfaceview, PID: 12825
java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
at android.view.ViewGroup.addView(ViewGroup.java:4994)
at android.view.ViewGroup.addView(ViewGroup.java:4976)
at com.jme3.app.jmeSurfaceView.JmeSurfaceView.addGlSurfaceView(JmeSurfaceView.java:551)
at com.jme3.app.jmeSurfaceView.JmeSurfaceView$RendererThread.run(JmeSurfaceView.java:207)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at …
```
=> JmeSurfaceView: Removed explicit nullifying GlSurfaceView onDestroy

jme3-core/src/main/java/com/jme3/post/FilterPostProcessor.java
I've verified this fix on Linux using the `TestIssue1798` app in jme3-examples. I also tested with no filters in the FPP and without the FPP to ensure I did not break those situations.
=> solve issue #1798 (filtered scenes are squeezed)

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
In order to ensure initialization of the `defaultMaterialAdapters` map, I created a no-arg constructor for the loader. Otherwise this is a straightforward fix.
=> solve issue #1809 (GltfLoader is not thread-safe)

jme3-core/src/main/java/com/jme3/material/MatParam.java, jme3-core/src/main/java/com/jme3/shader/VarType.java
This PR adds the matching java types to VarTypes and uses them to perform runtime type checks on MatParam.setValue().
Should be merged after https://github.com/jMonkeyEngine/jmonkeyengine/pull/1759
=> Add java types to VarType and type checks to MatParam

jme3-core/src/main/java/com/jme3/post/FilterPostProcessor.java
History: https://hub.jmonkeyengine.org/t/possible-to-use-stencil-buffer-with-filterpostprocessor/45840
In 2016, [Tiatin added the setFrameBufferFormat method to FilterPostProcessor.](https://hub.jmonkeyengine.org/t/ability-to-change-image-format-for-filterpostprocessor/36379)  This allows different formats to be used for the color render buffer.  I think the depth buffer needs the same treatment so that stencil operations can be performed while filters are in use.
This is the first PR I've made, so please let me know if I've done something wrong, thanks!
=> Added setter for FilterPostProcessor.depthFormat

jme3-desktop/src/main/java/com/jme3/app/SettingsDialog.java
Fixed issue #1824  swing look and feel to be defaulted to swing LAF, if you want to change the LAF on your own use this at your `SimpleApplication`: 
```java
static {
try {
UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
} catch (Exception e) {
Logger.getLogger(MyClass.class.getName()).severe("Cannot set the LAF, defaulting back to System LAF");
}
}
```
This is a test for this PR: 
When setting the LAF at the static initializer (as a user code):
=> SettingsDialog: LAF fix

jme3-core/src/plugins/java/com/jme3/asset/plugins/HttpZipLocator.java
Fix #1843
Reported on the forum: 
https://hub.jmonkeyengine.org/t/httpziplocator-questions/45859
```
com.jme3.asset.AssetLoadException: An error occurred loading Walk.gltf
at com.jme3.scene.plugins.gltf.GltfLoader.loadFromStream(GltfLoader.java:181)
at com.jme3.scene.plugins.gltf.GltfLoader.load(GltfLoader.java:106)
at com.jme3.asset.DesktopAssetManager.loadLocatedAsset(DesktopAssetManager.java:272)
at com.jme3.asset.DesktopAssetManager.loadAsset(DesktopAssetManager.java:388)
at com.jme3.asset.DesktopAssetManager.loadModel(DesktopAssetManager.java:439)
at asset.TestHttpLocator.simpleInitApp(TestHttpLocator.java:33)
at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:240)
at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:548)
at …
```
=> Fix #1843 (java.util.zip.ZipException in HttpZipLocator)

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java, jme3-core/src/main/java/com/jme3/anim/AnimLayer.java, jme3-core/src/main/java/com/jme3/anim/tween/action/BaseAction.java, jme3-core/src/main/java/com/jme3/anim/tween/action/BlendableAction.java, jme3-examples/src/main/java/jme3test/model/anim/TestAnimMigration.java
Including:
* Option to enable/disable animation mask propagation to child actions.
* Option to control max transition weight. For example useful for controlling smooth animation transition when an animation is removed from an upper layer.
* Added animation loop support in AnimLayer.
* AnimLayer can now also keep the action name, so one can easily look up the currently playing action name in a specific layer.
=> Some enhancement to new animation system

jme3-core/src/main/java/com/jme3/anim/tween/Tweens.java, jme3-examples/src/main/java/jme3test/model/anim/TestAnimMigration.java
Cycle tween is used for running delegate tween back and force and Invert tween is used to run delegate tween backward.
=> Added Tweens.cycle() and Tweens.invert() methods

jme3-core/src/main/java/com/jme3/anim/tween/action/BlendAction.java, jme3-examples/src/main/java/jme3test/model/anim/TestAnimMigration.java
This resolves slow-motion side effects caused by BlendAction stretching any animation that doesn't have the same length. It generates speed factors for each child animation that are dynamically interpolated and applied to base speed based on the blend weight taken from blend space.
This is a breaking change, as the speed returned by `BlendAction.getSpeed()` used to be a static value but now it returns a dynamic value that is changed as blend weight is changed. Unless `speedFactors` is cleared out or factors are equal. (i.e. clips have the same length).
=> BlendAction: resolve slow-motion side effect caused by stretching actions

README.md
* Fixed broken link in the `README.md` file.
Related issue: #1857
Closes: #1857
If possible I would like to do this here fix as part of the "Hacktoberfest".  I guess that we need to add a tag that it is accepted as such if that is ok?
=> docs(README) - fix: broken link in README.md

jme3-desktop/src/main/java/com/jme3/app/SettingsDialog.java
Heh, I had this sitting locally for some time. Might as well turn it in.
Basically it is cleanup. Changed loops to modern for each loops. Avoids some unnecessary string concatenations and other unnecessary operations especially when trying to get the depths. And changes the toArray calls to _faster_ one (https://shipilev.net/blog/2016/arrays-wisdom-ancients/).
In all the data handled is so minuscule that I doubt there is anything noticeable in performance. But code might be a bit more readable with less nesting and using DisplayMode.BIT_DEPTH_MULTI instead of magically discarding "-1" from the depths...
=> Clean up the display modes parsing

jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java
By default, InstancedGeometry was culling instances that were outside camera frustum and this was causing the shadow to disappear on instances away from the camera. See https://hub.jmonkeyengine.org/t/shadow-disapeared-on-instanced-objects-away-from-camera/46174
I introduced an instance culling function that can be switched or unset. The default implementation checks against camera frustum and does not consider shadow at all. Users wanting proper shadows would have to implement a function that took shadow light frustums into account before culling or otherwise they can unset the function to disable instance culling and it will resolve the shadow issue.
=> Add instance culling function in InstancedGeometry

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfUtils.java
Fixes #1871
With @Ali-RS doing the heavy lifting, this was very trivial to figure out. We just read the wrong amount of bytes when reading as float from arrays of short. Tested with the Duck and the Girl supplied in the issue. Both still work. Only the Girl has these normalized ushort float buffers though.
=> Fix #1871 (vertex colors not loaded in gltf models)

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/CustomContentManager.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/TextureTransformExtensionLoader.java
Implementation of a glTF extension loader for KHR_texture_transform, which allows for UV coordinates to be scaled/rotated/translated based on transformation properties from textures in the glTF model.
The extension will avoid the following warning messages:
Extension KHR_texture_transform is not supported, please provide your own implementation in the GltfModelKey
Extension KHR_texture_transform is mandatory for this file, the loaded scene result will be unexpected.
Could not find loader for extension KHR_texture_transform
=> Implementation of a glTF extension loader for KHR_texture_transform

jme3-core/src/main/java/com/jme3/anim/tween/action/BlendableAction.java
I happened to spot a small mistake in the following commit: https://github.com/jMonkeyEngine/jmonkeyengine/commit/9d5eeee8923c27495c948be7e7c91276e739da51
Based on the assertion in the method and the fact that the default value is 1, it's clear that the 0 and 1 bounds are inclusive.
=> BlendableAction: Fix JavaDoc for setMaxTransitionWeight & replace assert with IllegalArgumentException

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
This is an update for the glTF loader to be able to detect that an occlusion texture is packed in the metallic-roughness texture, so the loader can enable the `AoPackedInMRMap` parameter from the material and avoid double-loading the same texture.
The update consists of few lines added to `GltfLoader` that retrieve the `index` (if any) of each texture from the glTF model and compare them: if they exist and are the same, `AoPackedInMRMap` will be enabled and no texture will be loaded for occlusion. 
See for example the WaterBottle test model:
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/WaterBottle/glTF/WaterBottle.gltf
```
"materials": [
{
"pbrMetallicRoughness": {
"baseColorTexture": {
"index": 0
},
"metallicRoughnessTexture": {
"index": 1
}
},
"normalTexture": { …
```
=> Fix #1412 (GltfLoader does not support AO packed in MetallicRoughnessMap)

jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java, jme3-core/src/test/java/com/jme3/material/plugins/J3MLoaderTest.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MOutputCapsule.java, jme3-plugins/src/test/java/com/jme3/material/plugin/TestMaterialWrite.java
Updated J3MLoader to read texture mips generation flag from MinFilter. If no min filter is specified, texture will use the `BilinearNoMipMaps` by default.
Fixes #1882
=> Fix #1882 (J3MLoader always generates mips ignoring MinFilter)

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/CustomContentManager.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Now each GltfLoader instantiated via ThreadLocal will have its own instances of extension loaders.
=> Made Gltf extension loaders non-static to avoid concurrency issues

jme3-core/src/main/java/com/jme3/texture/Image.java
If we pass null for `int[] mipMapSizes` argument in the second constructor, this will wrongly set `mipsWereGenerated` flag to true. Fixed it to behave like the first constructor.
Fixes #1883
=> Fix #1883 (Image class wrongly setting GL mips flags inside the constructor)

jme3-core/src/main/java/com/jme3/scene/control/AreaUtils.java, jme3-core/src/main/java/com/jme3/util/AreaUtils.java
This PR includes: 
- Migrating the `AreaUtils` class from `com.jme3.scene.control` to `com.jme3.util`.
- Deprecating `com.jme3.scene.control.AreaUtils`.
- Jme3 copyright update.
EDIT: 
- Targeting this issue #1825
=> AreaUtils: Migrated package to `com.jme3.util`

jme3-examples/src/main/java/jme3test/TestChooser.java
Happens that java 8 adds "/" at the end of the directory name when reading from the jar filesystem. This patch checks if there is a "/" appended at the end of the directory name and removes it!
Resolves issue #1892
=> Fix #1892 (TestChooser does not show classes list when run with java 8)

jme3-core/src/main/java/com/jme3/effect/ParticleEmitter.java, jme3-examples/src/main/java/jme3test/effect/TestIssue1773.java
Fix the wrong particle position when using the `EmitterMeshVertexShape` or `EmitterMeshFaceShape` and `worldSpace` flag equal to true. The old code was interpolating particles' position toward the emitter world position and this was only working fine for EmitterPointShape but in the other shapes, this was causing particles to not keep the shape because they were being dragged toward the emitter position. The new code calculates the distance vector from the emitter's last location to the current emitter location and subtracts it from the particle's position to generate a hypothetical position that is used for interpolation. 
Resolves issue #1773
=> Fix #1773 (Wrong particle position when `worldSpace` flag equals to true)

jme3-niftygui/src/main/java/com/jme3/niftygui/NiftyJmeDisplay.java
I've tested this with windowed and full-screen contexts, with LWJGL v2 and v3.
=> jme3-niftygui:  solve issue #1891 (incorrect fullscreen layout)

jme3-lwjgl/build.gradle
We now maintain our own lwjgl2 repo: https://github.com/jMonkeyEngine/lwjgl2
See the release page for what is changed in v2.9.4
Fixes #1247, #1215, and partially https://github.com/jMonkeyEngine/jmonkeyengine/issues/947
=> jme3-lwjgl:updated to lwjgl v2.9.4 hosted by org.jmonkeyengine.

jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglDisplay.java
It fallback to standard 60Hz fullscreen display mode if the specified frequency in the AppSettings is not available and logs a warning when using jme3-lwjgl.
This is a shallow fix to just get rid of the preventing exception and let the app continue running.
Partially address #1890 , #947
=> Fix #1890 (crashes attempting to run example apps in fullscreen with LWJGL v2)

jme3-jbullet/build.gradle, jme3-jbullet/src/main/java/com/jme3/bullet/debug/BulletDebugAppState.java, jme3-vr/src/main/java/com/jme3/app/VRAppState.java
This ensures they show up correctly, as the VRAppState uses totally separate cameras and viewports to the normal JME flow
Resolves issue [#1795](https://github.com/jMonkeyEngine/jmonkeyengine/issues/1795)
=> When in VR attach the debug scene to the two eye's scenes. Fix #1795 

jme3-terrain/src/main/resources/Common/MatDefs/Terrain/PBRTerrain.frag
Drastically reduced code by utilizing JME's new potential for define-compatible for-loops in shaders. Also cleaned up some other little things like indentations, comments, and code placement so that the code is much more organized and easier to understand. And this should also fix this issue: https://github.com/jMonkeyEngine/jmonkeyengine/issues/1785
I tested the updated shader in the PBR Terrain test case as well as my main project, and encountered no errors or framerate drops. But I have not tested it on a Mac device to personally ensure it fixes issue 1785, although I expect that this PR should resolve it.
If everything looks good, I will go ahead and make a second PR with the same changes applied to the other version of the PBR terrain shader that uses TextureArrays …
=> Refactored PBR Terrain to use new for-loops. Fix #1785

jme3-core/src/main/java/com/jme3/scene/Spatial.java, jme3-core/src/test/java/com/jme3/scene/SpatialTest.java
The order of scene-graph controls within a `Spatial` is significant because it determines the order in which their logical state is updated. Update order is particularly important in animation: trouble would ensue if `AnimComposer` came after `SkinningControl`.
To arrange controls in a particular order, currently you must add them in that order. Sometimes this is inconvenient, so (for example) `DynamicAnimControl` uses weird tricks (including reflection) to arrange controls.
This PR adds a method to the `Spatial` class to insert a control at a particular position in a spatial's control list. This is a basic building block for arranging controls.
=> add the Spatial.addControlAt() method

jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java, jme3-core/src/main/java/com/jme3/system/JmeContext.java, jme3-core/src/main/java/com/jme3/system/NullContext.java, jme3-desktop/src/main/java/com/jme3/system/AWTContext.java, jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanelsContext.java, jme3-ios/src/main/java/com/jme3/system/ios/IGLESContext.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglContextVR.java
When implementing a graphical user interface, it's sometimes necessary to send notifications to the system listener. However, there is no API to access the listener.
This PR adds a getter, allowing applications to access the listener.
=> JmeContext:  add a getSystemListener() method

common.gradle
This will keep java 8 compatibility when it is compiled with newer java versions.
Fix #1896
=> common.gradle: set class files compatible with Java 8 using "release" option

jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java, jme3-core/src/main/java/com/jme3/system/JmeContext.java, jme3-core/src/main/java/com/jme3/system/NullContext.java, jme3-desktop/src/main/java/com/jme3/system/AWTContext.java, jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanelsContext.java, jme3-ios/src/main/java/com/jme3/system/ios/IGLESContext.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java, jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglWindowVR.java
This addresses issue #1900.
The most important implementations are those for LWJGL, which are straightforward. However, there are many other implementations of `JmeContext`, and I couldn't figure out how to obtain the desired information from all of them; exceptions are thrown in those cases.
=> add 4 getters to JmeContext for screen position and frame-buffer size

jme3-core/src/main/java/com/jme3/util/mikktspace/MikkTSpaceImpl.java, jme3-core/src/test/java/com/jme3/util/TestIssue1909.java
The solution is to generate a virtual index buffer if the mesh lacks an actual index buffer.
=> test and fix for #1909 (NPE while generating tangents)

jme3-lwjgl/build.gradle
It added the missing natives for windows and mac.
Fix #1908
=> jme3-lwjgl: bump to lwjgl 2.9.5 

jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java
Fixed `JmeDesktopSystem` to duplicate the imageData buffer before converting to AWT image so changes to buffers' position, limit, and mark values will be independent.
Fix #1917
=> Fix #1917 (RendererException in ScreenshotAppState: Attempting to upload empty buffer)

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
Updated a comment about the MetallicRoughness map that previously said the Red channel is unused - changed to instead say that the red channel of MR map can store the AO value if AoPackedInMRMap is true.
=> PBRLighting: fix comment describing packed MetallicRoughnessMap

jme3-core/src/main/java/com/jme3/util/mikktspace/MikktspaceTangentGenerator.java, jme3-core/src/test/java/com/jme3/util/TestIssue1919.java
When generating tangents, silently skip any meshes that do not contain triangles.
Meshes whose modes are `Hybrid` or `Patch` throw an appropriate exception.
=> solve issue #1919 (underflow while generating tangents)

.github/workflows/main.yml
This should not break java 8 compatibility because of the "release = 8" compile option specified in the Gradle build. I hope!
=> main.yml: deploy with jdk17

.github/workflows/main.yml
Deploy OSSRH artifacts with jdk17.
Fix #1923
=> Fix #1923 (OSSRH artifacts are build with different java version)

jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/file/FbxFile.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/file/FbxReader.java
Here's a proposed fix for issue #1928.
+ The constants for `BLOCK_SENTINEL_LENGTH` and `BLOCK_SENTINEL_DATA` were removed, since these values are no longer constant.
+ Two new methods were added to `FbxFile` to provide values that depend on the FBX file version.
+ An `FbxFile` instance was added to the arguments of `readFBXElement()`, giving the method access to the values.
+ A utility method was added, to test whether a byte array contains all zeroes.
=> solve issue #1928 (OutOfMemoryError in FBX importer)

jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/mesh/FbxLayerElement.java
Skip the copy if `dataIndices` is null.
This enables import of 2 models that used to crash due to issue #1930:
+ "Old_house_block_01.fbx"  (file version 7400) and
+ "Urban_communications.fbx" (file version 6100)
=> solve issue #1930 (NPE in FbxLayerElement)

jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxBindPose.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxCluster.java
Added code to the FBX importer to handle both array properties *and* multiple properties when importing:
+ a bind-pose matrix
+ the indices of a cluster
+ the weights of a cluster
=> solve issue #1932 (class cast exceptions in FBX importer)

jme3-core/src/main/java/com/jme3/math/Matrix4f.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/node/FbxNode.java
Added the `isSimilar()` method to `Matrix4f` since that seems the best place for it. The implementation is closely based on that of `Vector3f.isSimilar()`.
Hardcoded the tolerance to `1e-6f`, even though the largest difference seen so far was `< 1e-19`. I suspect that differences smaller than `1e-6f` will be imperceptible.
=> solve issue #1933 (unsupported operation in FbxNode)

jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/FbxLoader.java
The solution avoids the immediate crash and logs a warning with clues to the cause.
=> solve issue #1937 (NPE in FbxObject)

jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/FbxLoader.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxCluster.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxToJmeTrack.java
Cleanly handle the absence of animation data in 2 places:
+ in `FbxCluster.fromElement()`, create empty arrays of weights and indices
+ in `FbxLoader.constructAnimations()`, skip over any animations without keyframes
=> solve issue #1939 [NPE in FbxMesh.applyCluster()]

jme3-core/src/main/java/com/jme3/app/Application.java
Updated Application.start Javadoc to respect this change: https://github.com/jMonkeyEngine/jmonkeyengine/pull/1690/files
=> Update Application.start javadoc

jme3-core/src/main/java/com/jme3/material/RenderState.java
Added the required documentation for issue #1946
=> Update RenderState.setLineWidth javadoc

jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanelsContext.java
Log a "not supported" error on AwtPanelsListener.reshape/rescale method instead of throwing an exception. 
Fix #1945
=> Fix #1945 (IllegalStateException when running TestAWTPanels with LWJGL 3)

jme3-core/src/main/resources/Common/ShaderLib/Skinning.glsllib
A straightforward fix for issue #1879, rotating tangents using the same matrix that's used to rotate normals.
I've run "TestJaime.java" as a sanity check, however I don't see a way to test this fix. That's because I don't see how the `#if NUM_WEIGHTS_PER_VERT == 1` code in "Skinning.glsllib" ever gets compiled.
@zzuegg could you please test this fix or explain how it should be tested?
=> solve issue #1879 (compile-time error in Skinning.glsllib)

jme3-examples/src/main/java/jme3test/awt/TestAwtPanels.java
This resolves the JVM crash happening when running TestAWTPanels on Linux and LWJGL 3. Seems setting the Look And Feel on Swing UIManager prevents the crash.
Fix #1558 
Still need to figure out a solution for IllegalStateException happening on JME 3.6.0-beta1. See https://github.com/jMonkeyEngine/jmonkeyengine/issues/1558#issuecomment-1423951041 
But I think this should be in a separate PR.
=> Fix issue #1558 (TestAWTPanels crashes with LWJGL v3 on Linux)

jme3-core/src/main/java/com/jme3/anim/MorphTrack.java, jme3-core/src/main/java/com/jme3/anim/TransformTrack.java, jme3-core/src/main/java/com/jme3/anim/interpolator/FrameInterpolator.java
Instead of a `FrameInterpolator` instance for each `AnimComposer`/`SkinningControl`, this solution provides an instance for each thread. The per-thread instances are allocated using `ThreadLocal.withInitial()`.
To maximize compatibility with JME v3.5, the public `FrameInterpolator.DEFAULT` field is retained, however it is deprecated and no longer used in the Engine.
Similarly, the `setFrameInterpolator()` methods in `MorphTrack` and `TransformTrack` are retained. However, a `null` interpolator now has special meaning to these classes, namely that the per-thread default instance should be used.
=> solve issue #1806 (global FrameInterpolator violates threading model)

jme3-effects/src/main/java/com/jme3/water/WaterFilter.java
I use this to grab and hook the water reflection ViewPort into SkyControl for automatically updating the day/night color.
```
WaterFilter water = fpp.getFilter(WaterFilter.class);
if (water != null) {
skyControl.getUpdater().addViewPort(water.getReflectionView());
}
```
What do you think, is this a good addition? 
Edit:
In my case, I am setting an empty node as a "reflection scene" (I am doing a cartoon-style water and realistic reflection is not needed also it is a bit expensive) but I still need to be able to reflect the day/night color which I control by the viewport color via SkyControl.
=> Add WaterFilter.getReflectionView method

jme3-android-native/src/native/jme_decode/com_jme3_audio_plugins_NativeVorbisFile.c, jme3-android/src/main/java/com/jme3/audio/plugins/NativeVorbisFile.java, jme3-android/src/main/java/com/jme3/audio/plugins/NativeVorbisLoader.java
=> resolve issue #1955 (Can not play vorbis audio on Android API 31+)

jme3-jogg/build.gradle
The jme3-jogg library currently depends on the open-source j-ogg-all library. In turn, j-ogg-all depends on the Java Media Framework (JMF), which is large (about 1.9 MBytes), unmaintained, not open-source, and not available for all platforms.
In fact, jme3-jogg uses just a fraction of the j-ogg-all functionality: specifically, the Ogg-container reader and the Vorbis decoder.
Version 1.0.3 of the j-ogg-all project includes a new library ("j-ogg-vorbis") without decoders for the FLAC and Theora formats. This PR substitutes "j-ogg-vorbis" for "j-ogg-all", which should result in more compact applications with fewer dependencies.
=> jme3-jogg: remove dependency on Java Media Framework

jme3-android/src/main/resources/com/jme3/asset/Android.cfg
This PR takes use of `OGGLoader` from `jme3-jogg` instead of `NativeVorbisLoader` for loading ogg audio. The `jme3-jogg` uses a pure java decoder and supports `streamCache`.
Solve #1960
=> solve issue #1960 (use jme3-jogg for loading ogg files on android)

jme3-examples/src/main/java/jme3test/audio/TestMusicPlayer.java
In the case of lwjgl2, natives are loaded when LwjglContext is started but in the TestMusicPlayer test we do not create a LwjglContext, so we should handle loading natives ourselves.
Fix #1963
=> solve issue #1963 (TestMusicPlayer fails to load AL library on lwjgl2)

jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainPatch.java
PR following up on the discussion in this thread:  https://hub.jmonkeyengine.org/t/terrain-collision-exception/46491/6
=> Replace Exception with warning in TerrainPatch

jme3-examples/src/main/java/jme3test/bullet/TestAttachDriver.java
Zeroing the linear and angular velocities of the bridge solves issue #1975. (I tested it.)
This PR also simplifies `Quaternion.DIRECTION_Z.toRotationMatrix()`, which turns out to be an obscure (and perhaps misleading) way to generate an identity matrix.
=> solve issue #1975:  TestAttachDriver doesn't reset properly

jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java, jme3-desktop/src/main/java/com/jme3/system/NativeLibraries.java, jme3-desktop/src/main/java/com/jme3/system/NativeLibrary.java, jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java, jme3-examples/src/main/java/jme3test/audio/TestMusicPlayer.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglContextVR.java
Solves https://github.com/jMonkeyEngine/jmonkeyengine/issues/1968, https://github.com/jMonkeyEngine/jmonkeyengine/issues/1422 and https://github.com/jMonkeyEngine/jmonkeyengine/issues/1971
@stephengold and @Scrappers-glitch please feel free to review this and let me know what do you think
=> Improve NativeLibraryLoader

.github/workflows/main.yml, common.gradle
In response to this discussion:
https://hub.jmonkeyengine.org/t/adding-nightly-builds-to-engine/46560
This is mostly just a copy-paste of the relevant parts of the existing release deployment mechanism. It should not require manual intervention at any step.
I do not have a deployment account for Sonatype, so this branch is only partially tested. (The gradle script call returns "401: Unauthorized" when run from the command line. This is what I would expect without an account.)
Users who want to use the snapshot will need to add `https://oss.sonatype.org/content/repositories/snapshots/` to their build scripts' repository list, and then target version `<Major_Version>-SNAPSHOT`. Not sure where to document that.
=> Deploy master branch commits as snapshot

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag
Similar to PR #1444 but for PBR.
Issued on the forum: https://hub.jmonkeyengine.org/t/khr-transform/46524/37?u=ali_rs
=> Allow use of Emissive color as a multiplier with EmissiveMap in PBRLighting

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/MaterialAdapter.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java
Based on Gltf specs 
https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/material.normalTextureInfo.schema.json
and as issued on the forum https://hub.jmonkeyengine.org/t/khr-transform/46524/39?u=ali_rs 
I added a `NormalScale` factor in PBRLighting. The scalar parameter is applied to each normal vector of the normal map. This value scales the normal vector in X and Y directions using the formula: `scaledNormal = normalize((<sampled normal texture value> * 2.0 - 1.0) * vec3(<normal scale>, <normal scale>, 1.0))`. (from the above gltf spec)
and updated GltfLoader to support this.
=> Add support for NormalScale in PBRLighting & GltfLoader

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java
Added a scalar multiplier controlling the amount of occlusion applied and updated GltfLoader to read it if present on "occlusionTexture".
Based on specs https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/material.occlusionTextureInfo.schema.json
the formula should be for final occlusion value as: `1.0 + strength * (<sampled occlusion texture value> - 1.0)` but in JME I used `ao *= strength` based on forum suggestion.
Forum topic: https://hub.jmonkeyengine.org/t/gltf-ao-strenght/46553
=> Add support for AoStrength in PBRLighting & GltfLoader

jme3-android/src/main/java/com/jme3/audio/plugins/NativeVorbisFile.java, jme3-vr/src/main/java/com/jme3/input/vr/VRInputAPI.java
The first two commits fix some issues that were actually interfering with correct rendering in the javadoc.
The third really is just some typo and reflow to be more compliant with project code standards. Note that the file in question has several comment blocks that are still too long, (~125 characters average) but I didn't feel like messing with them on an API that is not really currently maintained. I only picked the truly low-hanging fruit.
=> Some javadoc cleanup

jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglDisplay.java
[Like LWJGL 3](https://github.com/jMonkeyEngine/jmonkeyengine/blob/29e07614ec8d10ebc90f1a997382a267b6667e04/jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java#L252), this re-initializes the renderer on context restarts on LWJGL 2, otherwise changing DepthBits or BitsPerPixel won't take effect and will result in a blank window after context restart (no spatial is rendered in the viewport).
I made a test case, it starts the app with BitsPerPixel=16 and after pressing key P on the keyboard it changes BitsPerPixel to 24 and restarts context. You will notice the stats view will be disappeared.
```
public class TestContextRestart extends SimpleApplication {
public static void main(String[] args) {
TestContextRestart app = new TestContextRestart();
AppSettings settings = new …
```
=> LwjglContext: re-initialize renderer on context restart (lwjgl 2)

jme3-core/src/main/java/com/jme3/audio/AudioBuffer.java, jme3-core/src/main/java/com/jme3/audio/AudioStream.java, jme3-core/src/main/java/com/jme3/audio/LowPassFilter.java, jme3-core/src/main/java/com/jme3/scene/VertexBuffer.java, jme3-core/src/main/java/com/jme3/shader/BufferObject.java, jme3-core/src/main/java/com/jme3/shader/Shader.java, jme3-core/src/main/java/com/jme3/texture/FrameBuffer.java, jme3-core/src/main/java/com/jme3/texture/Image.java
As I mentioned at issue #1982, one issue with negative native IDs is the encoding scheme used to implement `NativeObject.getUniqueId()`. To generate a unique ID, the object type is stored in the upper 32 bits. For a negative ID, sign extension during conversion from `int` to `long` obliterates the type information.
This PR masks off the upper 32 bits before adding the object type. It is merely the first of *many* changes that will be needed to handle negative native IDs in JMonkeyEngine.
=> correctly handle negative IDs in getUniqueId() methods

jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java
This PR attempts to address issue #1999 by changing the `Exception` thrown in `NativeLibraryLoader.computeNativesHash()` (when there's an I/O error) to match that thrown in `NativeLibraryLoader.loadNativeLibrary()`.
=> NativeLibraryLoader:  more detailed exception in computeNativesHash()

jme3-terrain/src/main/java/com/jme3/terrain/heightmap/ParticleDepositionHeightMap.java
As issue #2003 says, there's no reason for `load()` to return `false` in this case.
One reason the issue went undetected so long:  all uses of the `load()` method in jme3-terrain and jme3-examples ignore the return value. However, Minie (taking the javadoc literally) *does* check the value, so returning the correct value is important.
I quickly checked the other known implementations of `load()` and none of them seemed to have similar issues.
=> solve issue #2003 (ParticleDepositionHeightMap.load return value)

jme3-examples/src/main/java/jme3test/terrain/TerrainGridTileLoaderTest.java
=>  solve issue #2002 (TerrainGridTileLoaderTest fails to load tiles)

jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Solves #2011 
This PR is based on the JME hub thread :
[this](https://hub.jmonkeyengine.org/t/shadow-maybe-failed-in-gles2-and-appsetting-failed-to-choose-gl-version/46759/2#:~:text=Contributor-,2,choose%20version%20below%203.2%3A%0Asee%20this%20in%20stackoverflow%20and%20GLFW%20guide,-GLFW_OPENGL_PROFILE**%20specifies%20which)
It added a if branch to set GLFW to GLFW_OPENGL_ANY_PROFILE for there is no CORE-PROFILE below 3.2
=> solve issue #2011 (app crashes when using OpenGL version 3.0 and 3.1 with LWJGL 3)

jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java, jme3-core/src/main/java/com/jme3/scene/instancing/InstancedNode.java, jme3-examples/src/main/java/jme3test/scene/instancing/TestInstancingWithWaterFilter.java
Solves https://github.com/jMonkeyEngine/jmonkeyengine/issues/2007
The issue is that InstancedGeometry uses the wrong camera for "instance culling" check when rendering the scene from multiple viewports (e.g. main viewport and water reflection viewport) and this causes objects to get culled wrongly.
It is because `InstancedGeometry.updateInstances()` use the old camera (from the previous viewport) before it is updated in the below method:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/25a3407c9e403dbc0250430a304031c169636a03/jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java#L420-L423
this PR changed the code so it passes the camera into `updateInstances()` by the caller method.
Because `updateInstances()` is a `public` method on InstancedGeometry (not sure why …
=> solve issue #2007 (instanced objects are culled when using WaterFilter)

jme3-core/src/main/java/com/jme3/scene/Spatial.java
Assertions within the spatial class have no message associated with them. This makes them much less useful for debugging problems (they effectively just say; there is a problem, somewhere in your entire scene graph), By including the spatial name in the assertion message they will help track down the problem much quicker.
I have some of these very intermittently pop up in my own application but I can't really fix them without more information as to what spatial is causing them
=> solve issue #1992: better messages in spatial assertions

jme3-core/src/main/java/com/jme3/asset/CloneableSmartAsset.java
This is a documention-only PR.  The pre-existing javadoc for `setKey()` is confusing. I started by correcting the grammar (verb agreement) and that led to a couple more substantial clarifications.
=> CloneableSmartAsset:  clarify the setKey() javadoc

jme3-core/src/main/java/com/jme3/math/Quaternion.java, jme3-core/src/test/java/com/jme3/light/LightFilterTest.java, jme3-core/src/test/java/com/jme3/math/TestIssue2023.java
An automated testcase is included, to detect future regressions.
=> solve issue #2023 (getRotationColumn() returns wrong result)

jme3-core/src/main/java/com/jme3/math/Quaternion.java, jme3-core/src/main/java/com/jme3/math/Transform.java, jme3-core/src/main/java/com/jme3/scene/Spatial.java
The PR documents a few places where normalization is assumed.
JME assumes that the local rotations of scene-graph spatials are normalized. A violation of this assumption caused the issue @yaRnMcDonuts recently reported [at the Discourse Forum/Hub](https://hub.jmonkeyengine.org/t/solved-static-rigidbodycontrol-is-wrongly-offsetting-location-of-spatial/46792).
=> jme3-core:  document a few places where normalization is assumed

jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java
This PR makes PrimitiveAllocator the default buffer allocator due to a memory leak issue with AndroidNativeBufferAllocator.
See issue https://github.com/jMonkeyEngine/jmonkeyengine/issues/1990
In the below link you can find out why direct byte buffers allocated via JNI (`env->NewDirectByteBuffer()`) are not cleaned when GCed but the ones created with `ByteBuffer.allocateDirect()` are cleaned with GC. 
https://stackoverflow.com/a/35364247
=> By default use PrimitiveAllocator on Android

jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java
This modifies PR #2008 (including a partial revert) in order for it to be included in v3.6.1
=> InstancedGeometry:  re-implement no-arg version of updateInstances()

jme3-lwjgl/build.gradle
As mentioned [here](https://hub.jmonkeyengine.org/t/solved-failure-to-find-org-jmonkeyenginejar-2-9-5-after-upgrading-to-3-6-0/46838), the mvn package failed with the runtime dependency.
=> remove runtime dependency to lwjgl-platform:2.9.5 so mvn package does not fail

jme3-core/src/main/java/com/jme3/app/Application.java, jme3-core/src/main/java/com/jme3/app/LegacyApplication.java
This PR fixes the javadoc of the `Application#stop(boolean)` argument.
=> Application#stop(boolean): fix javadoc args issue

jme3-core/src/main/java/com/jme3/system/AppSettings.java
* Indicate the default is 0
* Ammended to explain 0 or 1 is single sampled
* Might seem odd without explaining it.
=> 1977: Fix AppSettings samples javadoc

jme3-core/src/main/java/com/jme3/export/JmeExporter.java, jme3-core/src/plugins/java/com/jme3/export/binary/BinaryExporter.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MExporter.java, jme3-plugins/src/test/java/com/jme3/export/JmeExporterTest.java, jme3-plugins/src/xml/java/com/jme3/export/xml/XMLExporter.java
Add a new save method that takes a flag to indicate if the file parent directories should be created.
Make the current save() method default in the interface and use the new method with createDirectories true.
Added tests for JmeExport using all current implementations of it.
=> Issue 1011: Make JmeExport save consistent in its path handling

common.gradle, config/checkstyle/checkstyle-suppressions.xml, config/checkstyle/checkstyle.xml, jme3-networking/build.gradle, jme3-vr/build.gradle
Add checkstyle plugin to common.gradle
Add a checkstyle.xml based on google checkstyle xml with ammendments. 
Checkstyle errors do not fail the build since everything is marked as a warning.
modules can be refined over time as per comments in #1877.
Checkstyle can be run with `./gradlew checkstyleMain` - it runs for all projects.
=> 1877: Add checkstyle to project

.github/workflows/format.yml
A github action workflow that applies [prettifier](https://prettier.io/) to pull requests (if needed) to automatically fix formatting issues.
- It is standalone
- The rules are similar to jme style but standardized (the only custom option used is tabsize=4)
- It is supported by many editors and can be used as git pre commit hook
- It supports many languages 
The goal is to make pr integration faster by resolving all sort of formatting issues automatically, since sometimes, even with a properly configured editor it is possible to miss some. (Unless you configure your editor to format on save, but can pollute the commit since most of our code was not formatted properly from the start.).
With this workflow contributors can simply pr changes  and have github action attach a formatting commit …
=> Autoformat workflow

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
These changes are intended to make the sourcecode more readable.
+ number agreement between nouns and verbs
+ punctuation to separate clauses
+ apostrophe when "let us" is contracted
+ correct glaring typos such as "MiiktSpace" and "color major"
=> GltfLoader:  copyedits to 18 inline comments

jme3-core/src/main/java/com/jme3/input/FlyByCamera.java
A proposed fix for issue #2078.
This solution enables `FlyByCamera` to zoom even when the camera is in orthographic mode.
Not exactly how it worked in JME v3.3.2, but similar.
=> bugfix: IllegalArgumentException in Camera.setFov() (issue #2078)

common.gradle
I've reviewed the release notes and begun using LWJGL 3.3.3 in my own projects, both on Linux and Windows 11. So far I haven't uncovered any regressions or new issues.
I think this change shouldn't be controversial.
I'm submitting this PR as a reminder to upgrade our Engine at some convenient time.
=> update LWJGL to v3.3.3

jme3-examples/src/main/java/jme3test/TestChooser.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglAbstractDisplay.java
I raised the same exact error at the same exact code line than the OP in the issue. That resulted in getting 2 errors. By properly using synchronized block, the other (coding error) was gone and I observed no dead locks.
The fix in TestChooser is for fixing these failed launches preventing the Chooser from shutting down properly. Failed launches cause the thread to loop in sleep waiting for some kind of confirmation I guess. Wait to stay alive to call the GC. They will stay there forever. Using `shutdownNow` interrupts the threads hanging and properly shuts them down. Note that this doesn't change the behavior otherwise. If you have a test running and close the TestChooser, the test doesn't close. Just the chooser exits and stops waiting. Also `shutdownNow` doesn't block, neither did the …
=> Prevent failed LWJGL 2 init to fail again

jme3-core/src/main/java/com/jme3/post/Filter.java, jme3-core/src/main/java/com/jme3/post/FilterPostProcessor.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
- Enable GLDebug for webgl.
- Name framebuffers in postprocessing: this is used to tag framebuffers in debuggers when GLDebug is enabled.
=> Improve GL Debug

jme3-core/src/main/java/com/jme3/util/SkyFactory.java
Set shadow mode to Off instead of Inherit for sky boxes to prevent them from messing with the shadow renderer if attached to a rootNode that has shadows enabled.
=> Disable shadows for sky

jme3-examples/src/main/java/jme3test/model/TestGltfLoading.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
This PR fixes #2092 where morph animation clips were loaded without tracks. The problem was occurs because the animation channels were assigned to a node instead of a geometry in the gltf file, which excluded those channels from being properly loaded.
My solution is if the target spatial is a node, traverse over that node's children and apply the morphs to the geometries found, otherwise apply morphs as before. This allows the engine to pass the [Morph Stress Test](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphStressTest) where it couldn't before.
=> Fixes GLTF Import of Morph Animations

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/shadow/ShadowUtil.java
Prevent updateShadowCamera from corrupting shadowCam matrix when there isn't any visible shadow caster in scene. 
Discovered in #2111
=> Prevent updateShadowCamera from corrupting shadowCam matrix.

jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java, jme3-core/src/main/java/com/jme3/scene/SceneGraphIterator.java, jme3-examples/src/main/java/jme3test/scene/TestSceneIteration.java
Small quality-of-life improvement. :)
This pull request adds a class that iterates over the scene graph with the depth-first approach. The advantage to using this over the standard scene traversal is being able to use enhanced for-loops, which allow for functionality lambdas are not capable of. I have found this to be very useful for processing scenes at runtime.
Basic usage:
```java
Spatial main = ...
for (Spatial spatial : new SceneGraphIterator(main)) {
// ...
}
```
The iterator has a couple useful methods:
```java
// makes the iterator not iterate over the children of the current spatial
iterator.ignoreChildren();
// gets the current depth (distance from the current spatial to the main spatial)
iterator.getDepth();
```
Example: count geometries
```java
int total = 0;
Spatial gameScene …
```
=> SceneGraphIterator

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-examples/src/main/java/jme3test/model/TestGltfLoading.java
This PR partially fixes #2087 by "flipping" the face cull mode as the render state is applied to the renderer if the geometry world scale is found to be negative. This does not alter the normal vectors, so shaders still receive backwards normals and models still may not appear quite right (especially with normal maps), but this fixes the face culling issue, at least.
=> Partial fix for Issue #2087 (NegativeScaleTest)

jme3-core/src/main/java/com/jme3/material/TechniqueDef.java, jme3-core/src/main/java/com/jme3/shader/DefineList.java, jme3-core/src/test/java/com/jme3/renderer/OpaqueComparatorTest.java, jme3-core/src/test/java/com/jme3/shader/DefineListTest.java
This PR re-implements the changes @yaRnMcDonuts made to `DefineList` and `Technique` in #2033.
It implements new fixes to `OpaqueComparatorTest` and `DefineListTest` that better reflect the intent of those tests.
It also updates copyright dates and improves the formatting of affected code.
=> Increase MAX_DEFINES in DefineList (re-do)

jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/AnimationList.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/SceneKey.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfModelKey.java
This commit fixes the minor #2070 asset key issue by adding equals and hashcode methods to GltfModelKey and SceneKey.
=> Fixes Issue #2070 (AssetKey overrides)

jme3-core/src/main/java/com/jme3/renderer/RenderManager.java, jme3-core/src/main/java/com/jme3/renderer/queue/RenderQueue.java
Moves the pushDebugGroup calls into RenderQueue so all call-sites are covered automatically.
And adds a ShadowQueue group for all shadow-related draw calls.
=> add debug groups for shadow draw calls

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Ok, GLB with the textures included easily causes LWJGL to run out of memory. As we might upload the same texture many times (we also read it many times...). 32Gb of RAM is nothing then. Also slowdowns and if one is into geometry batching.. no can do.
So this caches all the materials read to re-use them. Note that this affects both GLTF and GLB.
Resolves #2127
=> Solve issue #2127 (excessive memory use while loading GLB)

jme3-core/src/main/java/com/jme3/scene/Mesh.java, jme3-core/src/test/java/com/jme3/scene/mesh/MeshTest.java
Changed default values to "0" instead of "-1" and moved them to private constant class variables.
I guess "-1" was used as an fail/error-state but i didn't seen any checks besides ">=0", "!=0" and "==0".
Also after reading the request which also fixes #334 I am not sure if this a useful solution. 
Unittests -> ok
Handpicked examples(Scenes, Animation) ->  #ok
=> Mesh:  add constants for initial/default values of fields

jme3-core/src/main/java/com/jme3/texture/Texture.java, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md, jme3-core/src/main/resources/Common/ShaderLib/PBR.glsllib, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/AdvancedPBRTerrain.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/AdvancedPBRTerrain.j3md, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/PBRTerrain.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/PBRTerrain.j3md
see:http://www.jp.square-enix.com/tech/library/pdf/ImprovedGeometricSpecularAA(slides).pdf
https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@15.0/manual/Geometric-Specular-Anti-Aliasing.html
https://hub.jmonkeyengine.org/t/geometric-specular-anti-aliasing/47246/2
Usage: Simply set Material.setBoolean("SpecularAA", true);
=> Adding support for Specular-AA

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfUtils.java
Optimized version of reading bytes. Instead of reading one byte at the time... read multiple. With GLB, the whole file is in memory and with GLTF the reading is done from `BufferedReader` (meaning that there is never this catastrophic case where we would read a disk file a byte at a time). In latter case this would increase the reading speed even more than analyzed here. I just don't know does GLTF store anything in byte arrays. GLB seems to store the textures this way, which are potentially huge. So even reading from memory, calling this `readByte` billions of times causes significant overhead.
The same problem is with all the populate*Array but fixing those others is potentially more messy and yield in less gains as the units are already bigger. That being said, I only focus on this …
=> Read bytes more efficiently

jme3-core/src/main/java/com/jme3/anim/SkinningControl.java, jme3-core/src/main/java/com/jme3/animation/SkeletonControl.java, jme3-examples/src/main/java/jme3test/animation/TestIssue2076.java
This adds null checks to the software skinning code, for both the old animation system and the new one.
To catch future regressions, a test case is provided.
=> solve issue #2076 (software skinning requires vertex normals)

jme3-core/src/main/java/com/jme3/anim/MorphTrack.java, jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
This PR adds getters for the `FrameInterpolator` of a `MorphTrack` or `TransformTrack`.
The corresponding setters date back to MonkAnim, but Nehon didn't provide getters. I don't know why.
The use case is when I want to deep-clone an `AnimTrack`.  Since these classes don't implement deep cloning using `cloneFields()`, I need access to the private `interpolator` field. Currently such access is possible only by using reflection.
=> jme3-core:  add 2 getters for frame interpolators

jme3-core/src/test/resources/bad-booleans1.j3md, jme3-core/src/test/resources/bad-booleans2.j3md, jme3-core/src/test/resources/bad-booleans3.j3md, jme3-examples/src/main/resources/jme3test/materials/TestIssue37.j3md
Improve several material definitions used in tests, based on Riccardo's note at the Discourse Forum/Hub: https://hub.jmonkeyengine.org/t/porting-jmonkeyengine-to-the-browser-with-webgl2-and-teavm-sourcecode-released/47020/65
As far as I know, these material definitions aren't causing any issues. This PR is more about setting a good example.
=> in J3MD files, always list GLSL versions in descending order

jme3-examples/build.gradle
I reproduced issue #2096 using Java 11 on Mint Linux.  Adding 2 library dependencies solved it, as I suspected it might.
However, I'm not very confident this is the right solution.
I don't understand why issue #2096 doesn't occur when running examples in NetBeans.
I don't understand when/why the jme3-plugins-json and jme3-plugins-json-gson libraries are required. Is this documented anywhere?
=> solve issue #2096 (error launching examples from the dist jar)

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/MaterialAdapter.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UnlitExtensionLoader.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UnlitMaterialAdapter.java
Additional patch to #2085 that makes gltf pbr materials default EmissiveIntensity to 1.0.
=> Fixes Gltf Emissive Intensity Default

jme3-effects/src/main/java/com/jme3/water/WaterFilter.java
Material-parameter names are case-sensitive, and the actual name of the parameter is "CausticsMap".
This resolves issue #2164.
=> solve issue #2164 (setCausticsTexture() sets non-existent parameter)

jme3-core/src/main/java/com/jme3/math/Matrix4f.java, jme3-core/src/main/java/com/jme3/math/Quaternion.java, jme3-core/src/main/java/com/jme3/math/Transform.java
This PR improves the javadoc in the com.jme3.math package to document certain assumptions and limitations related to 3-D coordinate transforms.
In particular, `Matrix4f.toScaleVector()` does not capture reflection and `Quaternion.fromRotationMatrix()` fails to compensate for it. These limitations ripple outwards, affecting other `Matrix4f`, `Quaternion`, and `Transform` methods.
=> document issue #2089 (scale factors assumed positive)

jme3-core/src/main/resources/Common/MatDefs/Light/PBRGlow.frag, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
Fixes #2161 by making PBRLighting use PBRGlow.frag, which uses Emissive and EmissiveMap material parameters for calculating glow.
=> Fix PBR Support for Glow

jme3-plugins-json-gson/build.gradle
Currently the jme3-plugins-json-gson subproject depends on v2.9.1 of Google's Gson library, which was released in July 2022.
This PR updates the dependency to v2.10.1, which was released in January 2023.
For a summary of the differences between the 2 releases, see [the Gson release notes](https://github.com/google/gson/releases).
=> update the "gson" library to v2.10.1

jme3-lwjgl3/src/main/java/com/jme3/util/LWJGLBufferAllocator.java
https://github.com/jMonkeyEngine/jmonkeyengine/issues/2176
LWJGLBufferAllocator.allocate() now always returns zero-initialized buffers.
=> #2176 Make LWJGLBufferAllocator use nmemCalloc() instead of nmemAlloc()

jme3-core/src/main/java/com/jme3/util/MemoryUtils.java
The smart quotes were unnecessary and caused issues in some editors, so I removed them. This resolves issue #2184.
I also updated the copyright dates and split 2 lines that exceeded the 110-character limit.
Ready for review.
=> solve issue #2184 (smart quotes in log messages)

jme3-vr/src/main/java/com/jme3/app/VRAppState.java, jme3-vr/src/main/java/com/jme3/app/VRConstants.java, jme3-vr/src/main/java/com/jme3/app/VREnvironment.java, jme3-vr/src/main/java/com/jme3/input/vr/AnalogActionState.java, jme3-vr/src/main/java/com/jme3/input/vr/DigitalActionState.java, jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVRInput.java, jme3-vr/src/main/java/com/jme3/post/CartoonSSAO.java, jme3-vr/src/main/java/com/jme3/post/FilterUtil.java, jme3-vr/src/main/java/com/jme3/post/PreNormalCaching.java, jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowFilterVR.java, jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowRendererVR.java, jme3-vr/src/main/java/com/jme3/shadow/DirectionalLightShadowFilterVR.java, jme3-vr/src/main/java/com/jme3/shadow/DirectionalLightShadowRendererVR.java, jme3-vr/src/main/java/com/jme3/shadow/InstancedDirectionalShadowFilter.java, jme3-vr/src/main/java/com/jme3/shadow/VRDirectionalLightShadowRenderer.java, jme3-vr/src/main/java/com/jme3/util/VRGUIPositioningMode.java, jme3-vr/src/main/java/com/jme3/util/VRGuiManager.java, jme3-vr/src/main/java/com/jme3/util/VRUtil.java
Deprecate key classes in JME3-vr. This functionality is outdated (using OpenVR) and will be deleted in a future version.
User provided libraries supporting OpenXR should be used instead.
As discussed in the [thread for JME V3.7](https://hub.jmonkeyengine.org/t/jme-3-7/47390/5?u=richtea)
=> #2174 deprecate key classes in JME3-vr. 

jme3-core/src/main/java/com/jme3/renderer/opengl/GLExt.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java, jme3-core/src/main/java/com/jme3/texture/Image.java, jme3-core/src/plugins/java/com/jme3/texture/plugins/DDSLoader.java, jme3-core/src/plugins/java/com/jme3/texture/plugins/DXTFlipper.java, jme3-core/src/plugins/java/com/jme3/texture/plugins/ETCFlipper.java
This pr expand the compatible format list for gl es 3 and adds ETC2 support.
The DDS loader can now load ETC DDSs converted with [compressonator](https://gpuopen.com/compressonator/) (basically old header dds with custom pixel formats).
limitations:
- *ETC flipping is not supported*: i couldn't figure out how to flip etc compressed textures without decompressing them first, even though it is probably possible (similar to dxt flipping). I don't this this is very important, since compressed textures are usually considered in their final form and they can be flipped during compression if needed, also we didn't even had dxt flipping for a long time. I plan to open an issue for this and hopefully someone that is knowledgeable about etc formats can contribute with the missing code one day.
=> Expand support for GL ES / WebGL compatible formats.

jme3-core/src/main/java/com/jme3/anim/tween/action/Action.java
This PR adds a basic documentation for `com.jme3.anim.tween.action.Action` class.
=> com.jme3.anim.tween.action.Action: basic javadoc

jme3-core/src/main/java/com/jme3/anim/AlertArmatureMask.java, jme3-core/src/main/java/com/jme3/anim/SingleLayerInfluenceMask.java
This is my first pull request ever, so take it easy on me :)
The main element of this class (~~AlertArmatureMask~~ SingleLayerInfluenceMask) is the ability to check if a joint is currently being used by a higher layer before approving it for personal use via `contains(Object target)`. This can help smooth some interpolation issues that may arise between layers with looped/sequenced animations (see [here](https://hub.jmonkeyengine.org/t/solved-animation-transition-not-seamless-as-expected/46941/8) for more details on the problem).
This class also provides several helper methods to make mask creation easier.
=> Adds SingleLayerInfluenceMask

jme3-core/src/main/java/com/jme3/anim/tween/action/BaseAction.java
This PR provides basic javadoc for the class `com.jme3.anim.tween.action.BaseAction`.
=> com.jme3.anim.tween.action.BaseAction: basic javadoc

.github/workflows/main.yml
The continuous integration at GitHub needs a few updates to address the recent deprecation of Node.js 16.
Recent CI summaries contain annotations of the following sort:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-java@v3, gradle/wrapper-validation-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
For example, see: https://github.com/jMonkeyEngine/jmonkeyengine/actions/runs/7747717155
If left unresolved, these issues might someday cause our continuous integration to fail.
This PR should resolve all or most of those annotations.
=> update GitHub actions: setup-java to v4, wrapper-validation-action to v2

gradle/wrapper/gradle-wrapper.properties
We can't easily upgrade to Gradle 8, but at least we can use the latest release of Gradle 7.
Upgrading to 7.6.4 addresses some security vulnerabilities. See [the release notes](https://docs.gradle.org/7.6.4/release-notes.html) for details.
Upgrading is a simple matter of changing the properties file:  the upgrade does not involve any changes to the Gradle JAR. (@tonihele I ran the update command twice, just in case.)
Long-term, we should clean up the project so it can migrate to Gradle 8 ... and perhaps Kotlin-based Gradle as well, since that's where the world appears to be headed.
=> update the Gradle wrapper to v7.6.4

jme3-core/src/main/java/com/jme3/anim/tween/action/ClipAction.java
=> #2194 add ClipAction.getAnimClip() method, remove ClipAction.reset() method

jme3-core/src/main/java/com/jme3/shader/VarType.java
`VarType.Boolean`: reorder the list of `javaTypes` in accordance with `Float` and `Int`
- format code
- update License year
```java
// before
Float("float", float.class, Float.class), 
Int("int", int.class, Integer.class), 
Boolean("bool", Boolean.class, boolean.class), //<----
```
```java
// after
Float("float", float.class, Float.class), 
Int("int", int.class, Integer.class), 
Boolean("bool", boolean.class, Boolean.class), //<----
```
=> VarType: format code

jme3-core/src/main/java/com/jme3/util/MaterialDebugAppState.java
MaterialDebugAppState: format code
Update License year
=> MaterialDebugAppState: format code

jme3-core/src/main/java/com/jme3/shadow/DirectionalLightShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/PointLightShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/SpotLightShadowFilter.java
* DirectionalLightShadowFilter: format code + javadoc
* PointLightShadowFilter: format code + javadoc
* SpotLightShadowFilter: format code + javadoc
Update License year
Removed broken links to unreachable sites
=> xxxLightShadowFilter: format code + javadoc

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/main/java/com/jme3/material/RenderState.java
While testing some pbr code, i've noticed that something was off with lighting, after some convoluted debugging i've found that pr https://github.com/jMonkeyEngine/jmonkeyengine/commit/5975b3f791d18fae311a10e209b3ed40b5e5c60f introduced a bug.
The tl;dr is that copyMergedTo changes the passed state when additionalState is set, but returns `this` when it isn't, causing mergedRenderState to not be updated at all.
This PR restores the original behavior of passing the returned state to applyRenderState instead of mergedRenderState.
=> Fix render states merging when additionalState is not set

build.gradle
After PR #2197 (updating the Gradle version in gradle/wrapper/gradle-wrapper.properties) was integrated, @llzen44 pointed out that a Gradle version is also coded in the project's top-level build script.
I'm not 100% certain, but I assume this code is in case someone executes a "gradlew wrapper" command without specifying the desired version.
For the sake of consistency, this PR updates the top-level build script to specify the same version as gradle/wrapper/gradle-wrapper.properties
=> build.gradle:  update Gradle version to match gradle-wrapper.properties

jme3-core/src/main/java/com/jme3/shadow/ShadowUtil.java
Fix https://github.com/jMonkeyEngine/jmonkeyengine/issues/2209
=> Fix divide by 0 in shadow utils for some scenes #2209

common.gradle
The Engine uses Groovy solely for automated testing during builds.
This PR updates the buildscripts to use the latest release (dated 1 March 2024).
=> update Groovy to v3.0.21

build.gradle
As discussed at PR #2207, the Engine currently codes the Gradle version in 2 places (build.gradle and gradle/wrapper/gradle-wrapper.properties).
As a result:
+ The Engine's procedure for updating Gradle differs from that described in Gradle release notes, requiring an extra step.
+ It's possible for the coded versions to get out of synch with one another, causing confusion about which version is used to build the Engine.
This PR deletes the "wrapper" block from build.gradle .
As a result:
+ The Engine's Gradle version is coded in a single, central place.
+ The upgrade procedure documented in Gradle release notes will suffice, but a simple "gradlew update" will not.
=> don't code the Gradle version in build.gradle

jme3-core/src/main/resources/Common/ShaderLib/GLSLCompat.glsllib
Fix issue reported here: https://hub.jmonkeyengine.org/t/jmonkeyengine-v3-7-0-alpha2-release/47534
Some OpenGL drivers do not like precision qualifiers even if they should be supported as nop accordingly to the documentation
=> Use precision qualifiers only in GL ES shaders

jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglCanvas.java
This PR is to remove a '**redundancy'** in the size depth settings in **LwjglCanvas**
```java
...
[Line 500] glData.depthSize = settings.getBitsPerPixel();
...
[Line 504] glData.depthSize = settings.getDepthBits();
```
It doesn't cause any problems but it is better to clean it.
=> Logic code error (LwjglCanvas - LWJGL3)

jme3-core/src/main/java/com/jme3/scene/debug/SkeletonDebugger.java
Resolves #2226
Prevents NPE after deserializing SkeletonDebugger. The solution is not that pretty. But it works. The children are written/read properly, this just then finds them by the fixed names set.
=> Fix SkeletonDebugger deserializing

jme3-core/src/main/java/com/jme3/renderer/RenderManager.java
Fix bug where the clipRect would be left in the openGL state leading to surprising (clipped) results when later using GLRenderer#copyFrameBuffer
closes #2224
=> #2224 Fix bug where the clipRect would be left in the openGL state 

.github/workflows/main.yml
Recent macOS builds at GitHub Actions have been failing with the following diagnostics:
```log
##[group]Run actions/setup-java@v4
2024-04-24T01:40:44.9411640Z with:
2024-04-24T01:40:44.9411810Z   distribution: temurin
2024-04-24T01:40:44.9412020Z   java-version: 8
2024-04-24T01:40:44.9412220Z   java-package: jdk
2024-04-24T01:40:44.9412420Z   check-latest: false
2024-04-24T01:40:44.9412670Z   server-id: github
2024-04-24T01:40:44.9412880Z   server-username: GITHUB_ACTOR
2024-04-24T01:40:44.9413130Z   server-password: GITHUB_TOKEN
2024-04-24T01:40:44.9413370Z   overwrite-settings: true
2024-04-24T01:40:44.9413590Z   job-status: success
2024-04-24T01:40:44.9413870Z   token: ***
2024-04-24T01:40:44.9414030Z ##[endgroup]
2024-04-24T01:40:45.1018110Z ##[group]Installed distributions …
```
=> stop building with JDK 8 at GitHub Actions

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
I just could not figure out why the material cloning doesn't work. I mean, AssetManager does it all the time... I don't know. Anyway, this slows down 20% loading the Bistro scene as GLB on my beefy computer. However, the memory problems are still solved with the texture cache.
Partially reverts https://github.com/jMonkeyEngine/jmonkeyengine/pull/2128. But as said, the memory fix is still in and working.
As discussed in https://hub.jmonkeyengine.org/t/jmonkeyengine-v3-7-feature-freeze/47558/35.
=> Remove material cache, some materials seem not work when cloned

jme3-core/src/main/java/com/jme3/texture/Image.java, jme3-core/src/test/java/com/jme3/texture/TestIssue2250.java
This pull request adds automated tests for issue #2250.
It then solves the issue by skipping (if `multiSamples==1`) the checks that throw exceptions related to multisampling.
=> solution for issue #2250 (exceptions from Image.setMultiSamples(1))

.github/workflows/main.yml
The wrapper validation actions in the GitHub Actions CI/CD script (".github/workflows/main.yml") verify the signature of the project's Gradle wrapper JAR file ("gradle-wrapper.jar"). This helps protect the project against malware.
Currently the script specifies version 2 of the action. However, version 3 has been out since 12 April 2024. Furthermore, [the README](https://github.com/gradle/wrapper-validation-action?tab=readme-ov-file#readme) indicates that the "gradle/wrapper-validation-action" action has been superseded by "gradle/actions/wrapper-validation".
This pull request brings the jMonkeyEngine repo up-to-date in this respect.
=> main.yml:  upgrade the wrapper validation action to v3

jme3-core/src/main/java/com/jme3/material/MatParamTexture.java
This pull request addresses several issues with the `MatParamTexture` class:
* **Duplicate variable**: The `texture` variable is redundant as it's already stored in the inherited `value` variable. This PR removes the unnecessary texture field.
* **Missing Javadoc**: The class and its methods lacked proper documentation. This PR adds comprehensive Javadoc comments to improve code readability and maintainability.
* **Inconsistent null handling**: The behavior of `setValue` methods regarding null values differed. This PR modifies `setValue` to allow null values, aligning it with the behavior of `setTextureValue` and the superclass's `setValue`.
Key improvements:
* **Code simplification**: By removing the duplicate variable, the code becomes cleaner and easier to understand.
* **Improved …
=> MatParamTexture: duplicate variables, missing javadoc, exceptions

jme3-core/src/main/java/com/jme3/math/Quaternion.java, jme3-core/src/main/java/com/jme3/math/Transform.java, jme3-core/src/test/java/com/jme3/math/QuaternionTest.java
These are already caught by assertions in GLRenderer, but by that time it is unclear what call pushed in the bad values
closes https://github.com/jMonkeyEngine/jmonkeyengine/issues/2275
=> #2275 Improve assertions for invalid transforms.

jme3-core/src/main/java/com/jme3/bounding/BoundingBox.java, jme3-core/src/main/java/com/jme3/bounding/BoundingSphere.java, jme3-core/src/main/java/com/jme3/bounding/BoundingVolume.java, jme3-core/src/test/java/com/jme3/bounding/TestBoundingBox.java, jme3-core/src/test/java/com/jme3/bounding/TestBoundingSphere.java
This PR addresses the enhancements request in issue #2249.
Since the PR overrides `equals()`, it must also override `hashCode()` because the contract of `hashCode()` specifies that objects that are equal must return the same code.
The new methods intentionally ignore the `checkPlane` field, which holds auxiliary data used by the `Camera` class.
=> implement equals(), hashCode(), and isSimilar() for bounding volumes

README.md
This updates the Engine's README.md file, adding a game to the list and updating some URLs.
=> June 2024 update to README.md

jme3-examples/src/main/java/jme3test/bullet/TestIssue2282.java, jme3-jbullet/build.gradle
This PR solves issue #2282 in jme3-jbullet and adds a simple test to jme3-examples.
The solution is simply to update the jbullet library to the latest version (1.0.3).
Note that issue #2282 doesn't affect [Minie](https://stephengold.github.io/Minie/minie/overview.html).
=> test and fix for issue #2282 (VerifyError while creating AXIS_SWEEP_3 space)

jme3-examples/src/main/java/jme3test/terrain/PBRTerrainAdvancedTest.java
This test case has some noisey rendering due to not setting MipMaps on the terrain material's TextureArrays.
So I added MinFilter.Trilinear to fix this issue, and also added MagFilter.Bilinear.
I don't know much about the different MipMap settings, but MinFilter.Trilinear appeared to create the smoothest results for the terrain in this test case (and my own projects), so I went with that.
=> Add MipMaps to PBRTerrainAdvancedTest.java

jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Reverted this change from https://github.com/jMonkeyEngine/jmonkeyengine/commit/ec9c8c5efcc08afa5bb7247abe644df68ca425b2.
Also I tested the canvas and it works (mainly because it is not the same implementation as it was on the commit linked).
Setting these variables made jME think that nothing was changed and no reshape was called.
=> Setting the resolution to match the old prevents calling reshape

.github/workflows/main.yml
Use windows-latest image (windows server 2022) instead of windows 2019
=> Use windows-latest image for windows CI

.github/workflows/main.yml
As well, start deploying from java 21, bumped from java 17.
So, now we have all 3 java LTS's building, and deploy from the latest LTS.
=> Add java 21 to the CI matrix

build.gradle, jme3-android-examples/build.gradle, jme3-android-native/build.gradle
Deleting some dead code here to simplify the gradle files.
=> Remove dead comments from gradle files

common.gradle
With this change, gradle 8.8 no longer complains about using deprecated gradle features that will be removed in 9, so we will have an easier time upgrading next time.
=> Fix deprecated gradle features, prepare for gradle 9

jme3-core/src/main/java/com/jme3/scene/BatchNode.java
- There are temporary arrays that are reused to work with vertex buffers.
- Some conditions cause the arrays to be used for storing more vertices that they can hold.
- This throws the exception.
- This fix validates the arrays size before accessing them, recreating the arrays if they are too small.
Fixes #2296
=> BatchNode: Fix IndexOutOfBoundsException

README.md
This adds a link to the Engine's readme file, based on [a recent Forum post](https://hub.jmonkeyengine.org/t/high-impact-early-access/47820).
=> add a weblink to the High Impact game (at Steam)

jme3-core/src/main/java/com/jme3/collision/bih/BIHNode.java
Otherwise glancing blows can end up "happening" but at infinite distance due to numerical precision
Closes #2284
See https://hub.jmonkeyengine.org/t/picking-sometimes-returns-infinite-distances/47715/2
=> #2284 Double check the collision really has happened in world space

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java, jme3-core/src/main/java/com/jme3/anim/AnimLayer.java, jme3-core/src/main/java/com/jme3/anim/AnimationMask.java, jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java, jme3-core/src/test/java/com/jme3/anim/AnimComposerTest.java
While working on this https://github.com/jMonkeyEngine/sdk/pull/612 I found out that AnimLayers couldn't be saved.
Tested in local SDK.
I'll look it over once more before turning into a proper PR.
The tests don't explicitly test the changes, just general AnimComposer behavior.
=> Minor refactor to allow for saving AnimLayers

jme3-terrain/src/main/resources/Common/MatDefs/Terrain/TerrainLighting.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/TerrainLighting.j3md
Uses the (previously unused) SpecularMap as a gray-scale texture for painting shininess/reflectivity on the whole terrain.
=> Add reflectivity/shininess support to TerrainLighting.frag

build.gradle, common.gradle, gradle/libs.versions.toml, jme3-android-examples/build.gradle, jme3-android/build.gradle, jme3-examples/build.gradle, jme3-jbullet/build.gradle, jme3-jogg/build.gradle, jme3-lwjgl/build.gradle, jme3-lwjgl3/build.gradle, jme3-niftygui/build.gradle, jme3-plugins-json-gson/build.gradle, jme3-vr/build.gradle, version.gradle
[Starting with Gradle v8](https://gradle.org/whats-new/gradle-8/#version-catalog), the best practice for managing version numbers of external libraries is to centralize them in a TOML catalog.
This PR implements such a catalog for JMonkeyEngine. It supersedes PR #2305.
=> buildscripts:  centralize version numbers in a TOML catalog

jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-examples/src/main/java/jme3test/stencil/TestStencilOutline.java
This fixes the use of the stencil buffers. 
As reference:
https://hub.jmonkeyengine.org/t/how-to-do-outline-with-stencil-buffer/47954/5
Also added the TestStencilOutline.java to the examples. 
Note: Somehow the TestChooser app is overwriting the appsettings in the main method. 
As a fix i added a postprocessor to the example application. This is not required when running
the test directly.
=> Stencil buffer fix

jme3-core/src/main/java/com/jme3/ui/Picture.java
Removed unnecessary instantiation of 'Vector3f' objects on setWidth() and setHeight() methods.
=> Remove unecessary 'new Vector3f()' in com.jme.ui.Picture

README.md
I drafted some build instructions for the Engine and tested them on Bash/Linux.
=> add build instructions to the README (see issue #2308)

.github/workflows/main.yml, build.gradle
These changes are meant to resolve issue #2335.
The `archiveClassifer` and `archiveExtension` properties of `archiveTask` are converted to strings using `get()`.
This enables the correct JAR files to be copied to the correct "build/libDist" folders under the correct names.
Tested on both Linux and Windows. Holding 24 hours for review. If there's no substantial discussion, I will self-integrate this PR.
=> build.gradle:  use get() to convert Jar-task properties to strings

jme3-core/src/main/java/com/jme3/util/TangentBinormalGenerator.java, jme3-core/src/main/java/com/jme3/util/TangentUtils.java, jme3-core/src/main/java/com/jme3/util/mikktspace/MikktspaceTangentGenerator.java, jme3-examples/src/main/java/jme3test/batching/TestBatchNode.java, jme3-examples/src/main/java/jme3test/effect/TestEverything.java, jme3-examples/src/main/java/jme3test/helloworld/HelloMaterial.java, jme3-examples/src/main/java/jme3test/light/TestDirectionalLightShadow.java, jme3-examples/src/main/java/jme3test/light/TestShadowsPerf.java, jme3-examples/src/main/java/jme3test/light/TestSimpleLighting.java, jme3-examples/src/main/java/jme3test/light/TestSpotLight.java, jme3-examples/src/main/java/jme3test/light/TestSpotLightShadows.java, jme3-examples/src/main/java/jme3test/light/TestTangentCube.java, jme3-examples/src/main/java/jme3test/light/TestTangentGen.java, jme3-examples/src/main/java/jme3test/light/TestTangentGenBadUV.java, jme3-examples/src/main/java/jme3test/light/TestTangentSpace.java, jme3-examples/src/main/java/jme3test/light/TestTransparentShadow.java, jme3-examples/src/main/java/jme3test/light/TestTwoSideLighting.java, jme3-examples/src/main/java/jme3test/material/TestBumpModel.java, jme3-examples/src/main/java/jme3test/material/TestNormalMapping.java, jme3-examples/src/main/java/jme3test/material/TestParallax.java, jme3-examples/src/main/java/jme3test/material/TestParallaxPBR.java, jme3-examples/src/main/java/jme3test/material/TestSimpleBumps.java, jme3-examples/src/main/java/jme3test/material/TestUnshadedModel.java, jme3-examples/src/main/java/jme3test/model/anim/TestAnimationFactory.java, jme3-examples/src/main/java/jme3test/post/TestLightScattering.java, jme3-examples/src/main/java/jme3test/post/TestPostFilters.java, jme3-examples/src/main/java/jme3test/post/TestTransparentSSAO.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java
The purpose of this PR is to deprecate TangentBinormalGenerator
- Deprecate TangentBinormalGenerator in favor of MikktspaceTangentGenerator
- Add a bit more context to the comment in MikktspaceTangentGenerator 
- Remove the part about it being experimental, since at this point it has been tested and patched enought to be considered out of this stage
- Add generate(Mesh) to match TangentBinormalGenerator 
- Move debugging utils from TangentBinormalGenerator into TangentUtils to be used with MikktspaceTangentGenerator
- Replaces the usage of TangentBinormalGenerator in all the examples and tests (except the Parallel Tangent test since out mikktspace doesn't have a parallel implementation).
This PR needs to be tested
=> Deprecate TangentBinormalGenerator

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag
addresses this issue: https://github.com/jMonkeyEngine/jmonkeyengine/issues/2330
There were 2 apparent issues with our metallic calculation that were causing our PBR implementation to render different visual results compared to the khronos PBR standards:
1) fZero was being calculated incorrectly, as mentioned in the linked issue 
2) the nonMetalSpec float constant was being set incorrectly. According to what I've read, it should always be 0.08
I also checked tested changes in my own app and it appears the rendering difference is more accurate now. But I'm not an expert in lighting math like this, so let me know if anyone sees anything else that looks incorrect with the PBR shader's code.
=> Fix incorrect metallic calculations in PBRLighting.frag

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java, jme3-core/src/test/java/com/jme3/anim/AnimComposerTest.java
=> Proposed fix for Issue#2341 - Missing default layer in AnimComposer

jme3-terrain/src/main/resources/Common/MatDefs/Terrain/HeightBasedTerrain.j3md, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/Terrain.j3md
Fix for issue [2300](https://github.com/jMonkeyEngine/jmonkeyengine/issues/2300) + format code.
Tested with the latest version of the SDK.
=> Fix for issue #2300: Removed incorrect 'Technique' block in terrain j3md files.

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/main/java/com/jme3/renderer/Renderer.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL2.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL4.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/renderer/opengl/TextureUtil.java, jme3-core/src/main/java/com/jme3/shader/VarType.java, jme3-core/src/main/java/com/jme3/system/NullRenderer.java, jme3-core/src/main/java/com/jme3/texture/Image.java, jme3-core/src/main/java/com/jme3/texture/TextureImage.java, jme3-examples/src/main/java/jme3test/texture/TestShaderImage.java, jme3-lwjgl/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-testdata/src/main/resources/Materials/ImageTest.frag, jme3-testdata/src/main/resources/Materials/ImageTest.j3md
This PR enables images to be read/written in a shader using [imageLoad](https://docs.gl/sl4/imageLoad), [imageStore](https://docs.gl/sl4/imageStore), etc. This is done by calling [glBindImageTexture](https://docs.gl/gl4/glBindImageTexture) when an access flag is not null after the texture is bound with [glBindTexture](https://docs.gl/gl4/glBindTexture).
This feature is disabled by default. Unless the access flag is specifically set to not null on the image, the image will be bound normally.
=> Enables images to be read and modified per pixel in shader

jme3-core/src/main/resources/Common/ShaderLib/module/PBRSurface.glsl, jme3-core/src/main/resources/Common/ShaderLib/module/pbrlighting/PBRLightingUtils.glsllib
Updated to store tbnMat as a publicly accessible variable in the PBRSurface.glsl struct, that way tbnMat won't need recalculated anywhere else it is needed in the same shader.
=> Add tbnMat variable to PBRSurface.glsl

jme3-core/src/main/java/com/jme3/system/DisplayInfo.java, jme3-core/src/main/java/com/jme3/system/Displays.java, jme3-examples/src/main/java/jme3test/app/TestMonitorApp.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
This PR fixes issue #2345 by refactoring class `DisplayInfo` to have better encapsulation. The new changes are intended to make the class as immutable as possible for end users, except for internal JME processes.
I'd like to point out that I've renamed the variable `displayID` to `display` since that variable (`long`) is actually a pointer that lwjgl3 returns and not an identifier itself (the old name might be a bit confusing).
=> [ Fix ] Minor refactoring to DisplayInfo.class #2345

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/AdvancedPBRTerrain.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/Modular/PBRTerrainUtils.glsllib, jme3-testdata/src/main/resources/Models/Tank/tank.j3m
While preparing to cut the next alpha release, I did a final engine build and ran some important pbr engine tests/examples, and I ran into a crash with the SimplePBRTest example.
I had forgotten that riccardo had changed this tank material to test the new modular pbr shaders when the shaders were in a separate directory for preliminary testing last year.
But now the duplicated modular shaders were deleted (and have replaced the main PBR shader), so this test crashes with an assetNotFoundException, and just needed updated to point back to Common/MatDefs/Light/PBRLighting.j3md.
=> Update tank material pointing to deleted copy of PBRLighting

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.vert, jme3-core/src/main/resources/Common/ShaderLib/TangentUtils.glsllib, jme3-core/src/main/resources/Common/ShaderLib/TriPlanarUtils.glsllib, jme3-core/src/main/resources/Common/ShaderLib/module/pbrlighting/PBRLightingUtils.glsllib, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/PBRTerrain.vert
This PR attempts to fix a rendering bug that a few jme users have experienced on certain devices, as discussed in this thread: https://hub.jmonkeyengine.org/t/requesting-help-troubleshooting-pbrterrain-bug/47895
I believe the issue was due to a combination of things that were done incorrectly in the process of reading normal maps, calculating tangents, and then blending the normal values.
I believe it is also important to normalize the normal value prior to blending each layer, which I previously was not doing.
There's also some code that is necissary for putting a normal map in the proper range, and this was being done improperly for tri-planar normal mapping. It should be done 3 times (once per read) and then normalized, and this was incorrect previously.
Once this PR is done I'll post …
=> Fix Rendering Issue in PBRTerrain

LICENSE.md
This updates the copyright notice (in the project's overall license) to include the current calendar year.
=> LICENSE.md:  add 2025 to the copyright years

jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java, jme3-android/src/main/java/com/jme3/view/surfaceview/JmeSurfaceView.java
This PR introduces a fix to:
* issue #2010.
The following are introduced into this PR:
=> [Android] Fix Android JmeSurfaceView Memory Leak

jme3-core/src/main/resources/Common/ShaderLib/module/pbrlighting/PBRLightingUtils.glsllib
The wViewDir varying was changed to be stored in the surface.viewDir value, so the references to that variable needed to be updated to match this.
I also changed some floats to be in decimal format.
=> Fix missing wViewDir variable and undeclared/wrongly declared vars

jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.frag, jme3-core/src/main/resources/Common/ShaderLib/MaterialFog.glsllib
This PR addresses this issue: https://github.com/jMonkeyEngine/jmonkeyengine/issues/2363
=> Fix Fog in Lighting.frag

jme3-core/src/main/java/com/jme3/anim/tween/action/BlendSpace.java
This PR adds a basic javadoc for the BlendSpace class.
=> com.jme3.anim.tween.action.BlendSpace: basic javadoc

jme3-core/src/main/java/com/jme3/input/RawInputListenerAdapter.java
Implement `RawInputListenerAdapter` to provide default empty implementations for all listener methods.
=> Add RawInputListenerAdapter for easier listener creation

jme3-core/src/main/java/com/jme3/anim/SingleLayerInfluenceMask.java, jme3-examples/src/main/java/jme3test/model/anim/TestSingleLayerInfluenceMask.java
see https://github.com/jMonkeyEngine/jmonkeyengine/issues/2317
=> SingleLayerInfluenceMask:  fix serialization issues

gradle/libs.versions.toml, jme3-vr/src/main/java/com/jme3/input/vr/osvr/OSVR.java
Last week, in [jMonkeyEngine 3.8.0-alpha3](https://github.com/jMonkeyEngine/jmonkeyengine/releases/tag/v3.8.0-alpha3), we finally upgraded jme3-lwjgl3 and jme3-vr to use [LWJGL v3.3.4](https://github.com/LWJGL/lwjgl3/releases/tag/3.3.4).
V3.3.4 is over 6 months old. Already there are 2 newer releases out: v3.3.5 and v3.3.6. The differences between them are so slight that I propose we upgrade directly from v3.3.4 to v3.3.6. This pull request implements that upgrade.
I'm unsure whether this change should go public in JME v3.8.0-stable or in a later release. I'll leave that decision to the release manager .
Either way, we'll need someone to test on VR hardware. Currently, I don't have access to such hardware. @jseinturier and @phr00t can you help?
=> update LWJGL from v3.3.4 to v3.3.6

jme3-core/src/main/java/com/jme3/math/Spline.java, jme3-core/src/test/java/com/jme3/math/SplineTest.java
This pull request solves issue #2366 and adds an automated test to prevent regressions.
The issue of spines being loaded as the wrong type is solved by passing the same tag ("type") to `readEnum()` as was passed to `oc.write()`.
The `ClassCastException` issue is solved by converting `knots` to/from a `float[]` array and saving/loading those arrays. Compatibility with serialized data from past releases is maintained in the case where `knots` is `null`---in other words for non-NURB splines. However, past releases couldn't serialize NURB splines without crashing, so this change shouldn't cause any issues in practice.
=> solve issue #2366 (bugs related to saving/loading a Spline)

gradle/libs.versions.toml, jme3-lwjgl3/build.gradle, jme3-lwjgl3/src/main/java/com/jme3/system/lwjglx/Win32GLPlatform.java
This PR updates the lwjglx-awt library to the latest version ([V0.2.3](https://central.sonatype.com/artifact/org.lwjglx/lwjgl3-awt)). In this new version, an error that was reported in the [forum](https://hub.jmonkeyengine.org/t/failed-to-pass-test-case-jme3test-awt-testcanvas-on-jme-3-7-0-with-lwjgl3/47990?u=swiftwolf)  has been solved (correction in [lwjgl-awt](https://github.com/LWJGLX/lwjgl3-awt/pull/81))
I would like to inform you that these changes are related to PR #2371, that is; that this PR depends on PR #2371 so that AWT does not break when updating LWJGL3.
=> update LWJGLX (AWT) from 0.1.8 to 0.2.3

jme3-core/src/main/resources/Common/ShaderLib/TangentUtils.glsllib
I also added a line of code that I had previously removed from the tangent calculations that may fix some minor inaccuracies in shading and lighting direction (although it was very minor and barely noticeable).
I previously removed that line of code because it was also flipping the y component of normal map (which is better done by the NORMAL_TYPE param) but then I realized this line of code also flips the x component of the normal map which is likely important for the tangent calculation that follows. So I just updated it to only multiply the x component by -1 and will leave the y component flipping up to NORMAL_TYPE so users can change it as needed.
=> Fix non decimal format floats in TangentUtils.glsllib

jme3-core/src/main/resources/Common/ShaderLib/module/pbrlighting/PBRLightingUtils.glsllib
This PR addresses this issue: 
#2386 
And then I also found another critical logic error in the spec gloss pipeline that was likely there even before riccardo adapted the shader to use structs:
It looks like the specular and glossiness value taken from specularMaps was being totally ignored and the glossiness value was not being accounted for in the final roughness calculation. The code further down in the shader was calculating the roughness solely based on m_Glossiness with no regard for the glossiness scalar read from texture maps, which is incorrect.
The logic error and exception should all be fixed in this PR now, but it will need testing from a spec gloss model with packed specularGlossinesMap as well as a model with seperate specular and glossiness maps in order to ensure …
=> Fix logic errors and exception in SpecGloss pipeline

jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.vert, jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.vert
The fog code in PBRLighting.j3md is encountering the same issue that was reported before with Lighting.j3md : https://github.com/jMonkeyEngine/jmonkeyengine/pull/1458
This PR should fix the issue.
=> Fix exception when using Instancing with Fog in PBR

jme3-core/src/main/java/com/jme3/renderer/Camera.java, jme3-core/src/test/java/com/jme3/renderer/Issue2333Test.java
This PR attempts to address issue #2333 by adding runtime checks to the `Camera` class. 
The new checks throw `IllegalArgumentException` and affect 5 setters:
+ `setViewPort(float, float, float, float)`
+ `setViewPortBottom(float)`
+ `setViewPortLeft(float)`
+ `setViewPortRight(float)`
+ `setViewPortTop(float)`
For ease of maintenance, the checks are actually centralized in `onViewPortChange()`. This assumes `onViewPortChange()` isn't called often enough for this to cause a measurable performance impact.
In addition to testing for negative widths and heights, I decided to also test for zero-width viewports and zero-height viewports. I found at one instance of division by height, and I can't think of a use case for a zero-width viewport.
Automated tests (using JUnit4) are included in the …
=> solve issue #2333 (Camera viewport dimensions not checked)

jme3-core/src/main/java/com/jme3/cinematic/MotionPath.java, jme3-core/src/main/java/com/jme3/cinematic/events/MotionEvent.java, jme3-core/src/main/java/com/jme3/math/Spline.java, jme3-core/src/test/java/com/jme3/cinematic/MotionPathTest.java, jme3-core/src/test/java/com/jme3/math/SplineTest.java
=> solve issue #2370 (deeply clone MotionEvent path)

jme3-core/src/main/resources/Common/ShaderLib/module/pbrlighting/PBRLightingUtils.glsllib
Fixes this issue: https://github.com/jMonkeyEngine/jmonkeyengine/issues/2399 by reverting this block of code to its pre-for-loop state before the regression occurred. I tried fixing it without removing the for loops, but I'm not super comfortable with this light probe code so reverting this section of code seemed like the safest option.
I tested the changes and can confirm now that smooth blending between LightProbes is working again in my scenes with more than 1 LightProbe.
=> Fix LightProbe blending

jme3-core/src/main/java/com/jme3/scene/BatchNode.java
Ok, this is @pspeed42 's patch applied on top of master. I did not revert https://github.com/jMonkeyEngine/jmonkeyengine/pull/2297, I kept the good parts from the original patch. But I did not include the _fix for the symptom_ just to be sure that everything is always ok and we don't accidentally always just fallback to costly bandaid.
=> Improved fix for IndexOutOfBoundsException

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java, jme3-core/src/test/java/com/jme3/shadow/FilterPostProcessingTest.java
move the initialization of the Post Shadow Material to the `AbstractShadowFilter.init()` method
=> Fix NPE on AbstractShadowFilter deserialization

jme3-core/src/main/java/com/jme3/audio/Filter.java, jme3-core/src/main/java/com/jme3/audio/LowPassFilter.java, jme3-core/src/test/java/com/jme3/audio/AudioNodeTest.java
Fix for Issue https://github.com/jMonkeyEngine/jmonkeyengine/issues/2408
The fix is backward compatible and should not cause problems with older applications.
=> Fix #2408 - com.jme3.audio.LowPassFilter not cloneable

jme3-core/src/main/java/com/jme3/audio/Listener.java
* update License year
* add javadoc
* just a little code optimization
* Note: Renderer is also copied from Listener constructor
=> com.jme3.audio.Listener: format code + javadoc

jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.vert, jme3-examples/src/main/java/jme3test/scene/instancing/TestInstanceNodeWithPbr.java
This PR adds a new test to jme-examples that reproduces the error reported in #2435 from using pbr with instancing.
I also updated PBRLighting.vert and fixed the wPosition calculation to solve the original issue.
=> Add InstanceNode test using PBRLighting

jme3-examples/src/main/java/jme3test/audio/TestAmbient.java
Refactored the `TestAmbient` example code for improved clarity. This commit restructures the demo to explicitly highlight its individual components, making it easier to understand the flow and functionality.
=> jme3-examples: TestAmbient - test code optimization

jme3-examples/src/main/java/jme3test/audio/TestAudioDeviceDisconnect.java
This test demonstrates that destroying and recreating the `OpenAL Context` upon device disconnection is suboptimal. As evidenced, looping `AudioNode` instances stop playing after disconnection and require manual restarting. This test solely highlights this issue, which warrants a more robust solution within the `ALAudioRenderer` class in a future Git pull request.
We could look at `libGDX`'s approach to these problems
https://github.com/libgdx/libgdx/blob/master/backends/gdx-backend-lwjgl3/src/com/badlogic/gdx/backends/lwjgl3/audio/OpenALLwjgl3Audio.java#L128
Edit:
Maybe it's best to close this PR and open an Issue with the code so we can reproduce, test, and potentially fix it.
=> jme3-examples: add TestDeviceDisconnect class

jme3-core/src/main/java/com/jme3/audio/Environment.java
* Updated License year
* Added javadoc
* Added `hashCode()` method
* Refactored `equals()` method
Note:
`Math.abs(f1 - f2) < epsilon` is the more practical and recommended approach for comparing float fields in the `equals()` method of the `Environment `class because it allows for a necessary tolerance when dealing with floating-point calculations.
=> com.jme3.audio.Environment: javadoc

jme3-examples/src/main/java/jme3test/audio/TestWav.java
Refactored the `TestWav` example code for improved clarity. This commit restructures the demo to explicitly highlight its individual components, making it easier to understand the flow and functionality.
=> jme3-examples: TestWav - test code optimization

jme3-examples/src/main/java/jme3test/audio/TestDoppler.java
Refactored the `TestDoppler` example code for improved clarity. This commit restructures the demo to explicitly highlight its individual components, making it easier to understand the flow and functionality.
=> jme3-examples: TestDoppler - test code optimization

jme3-examples/src/main/java/jme3test/audio/TestAudioDirectional.java
=> jme3-examples: add TestAudioDirectional class

jme3-core/src/main/java/com/jme3/effect/influencers/DefaultParticleInfluencer.java, jme3-core/src/main/java/com/jme3/effect/influencers/NewtonianParticleInfluencer.java, jme3-core/src/main/java/com/jme3/effect/influencers/ParticleInfluencer.java, jme3-core/src/test/java/com/jme3/effect/influencers/ParticleInfluencerTest.java
This PR removes the overridden `clone()` method from the `NewtonianParticleInfluencer` class. This method duplicates functionality present in the superclass. Furthermore, the manual cloning of primitive fields is redundant as Java handles this automatically.
In addition, this PR solves the problems of cloning class variables that extend the superclass `DefaultParticleInfluencer`. The fix is backward compatible and should not cause problems with older applications.
=> DefaultParticleInfluencer: incorrect cloning of variables

jme3-core/src/main/java/com/jme3/effect/shapes/EmitterBoxShape.java, jme3-core/src/main/java/com/jme3/effect/shapes/EmitterPointShape.java, jme3-core/src/main/java/com/jme3/effect/shapes/EmitterShape.java, jme3-core/src/main/java/com/jme3/effect/shapes/EmitterSphereShape.java
This pull request introduces several enhancements to the EmitterShape class hierarchy to improve code clarity and maintainability.  The changes include:
* Removal of redundant `Cloneable `extension: The `EmitterShape `interface extends `JmeCloneable`, which itself already extends `Cloneable`. The explicit extension of `Cloneable `in `EmitterShape `is therefore redundant and has been removed.
* Improved Javadoc documentation: Comprehensive Javadoc documentation has been added to the `EmitterPointShape`, `EmitterSphereShape`, and `EmitterBoxShape `classes, including field and method descriptions, to improve class understanding and usability.
=> EmitterShape: javadoc improvements

jme3-core/src/main/java/com/jme3/audio/LowPassFilter.java, jme3-core/src/test/java/com/jme3/audio/AudioFilterTest.java
`com.jme3.audio.LowPassFilter` lacks the required no-argument constructor for jME deserialization.
```
java.lang.InstantiationException: Loading requires a no-arg constructor, but class com.jme3.audio.LowPassFilter lacks one.
at com.jme3.export.SavableClassUtil.findNoArgConstructor(SavableClassUtil.java:248)
at com.jme3.export.SavableClassUtil.fromName(SavableClassUtil.java:187)
at com.jme3.export.binary.BinaryImporter.readObject(BinaryImporter.java:332)
at com.jme3.export.binary.BinaryImporter.load(BinaryImporter.java:245)
at com.jme3.export.binary.BinaryImporter.load(BinaryImporter.java:128)
at com.jme3.export.binary.BinaryImporter.load(BinaryImporter.java:282)
at com.jme3.export.binary.BinaryExporter.saveAndLoad(BinaryExporter.java:168)
> Task :jme3-core:test FAILED
AudioFilterTest > …
```
=> com.jme3.audio.LowPassFilter lacks the required no-argument constructor for jME deserialization

jme3-core/src/main/java/com/jme3/scene/debug/WireSphere.java
This PR introduces a static `makeGeometry(BoundingSphere bsph)` method to the `WireSphere` class. This new method mirrors the existing `WireBox.makeGeometry(BoundingBox bbox)` method, providing a consistent API for creating `Geometry` instances suitable for visualizing bounding volumes. This improves usability and uniformity across the debug scene classes.
=> Add makeGeometry() method to WireSphere for consistency with WireBox

jme3-core/src/main/java/com/jme3/environment/EnvironmentProbeControl.java, jme3-core/src/main/java/com/jme3/environment/FastLightProbeFactory.java, jme3-core/src/main/java/com/jme3/environment/baker/IBLGLEnvBakerLight.java, jme3-core/src/main/java/com/jme3/environment/baker/IBLHybridEnvBakerLight.java, jme3-core/src/main/resources/Common/IBL/IBLKernels.frag
Band factors were not applies to spherical harmonic coefficients in the accelerated baker, causing bad lighting on high roughness materials.
This PR fixes that for both IBLHybridEnvBakerLight (gpu+cpu) and IBLGLEnvBaker**Light** (gpu) bakers.
This PR also clamps the luminance in the prefiltered envmap kernel, to avoid fireflies artifacts when sampling over bright areas (that could be due to artistic choice or bad tonemap).
=>  PBR Fixes: Apply band factor to spherical harmonic coefficients in accelerated baker light and prevent fireflies artifacts

jme3-core/src/main/java/com/jme3/animation/LoopMode.java
This PR reverses the deprecation of the `LoopMode` enum class. It's being undeprecated as it's still actively used and provides necessary functionality.
=> Undeprecate LoopMode

jme3-core/src/main/java/com/jme3/effect/shapes/EmitterSphereShape.java
Looks like this line was omitted when writing this class, even though all the necessary data to calculate the normal was already available.
=> Return normal of sphere shaped emitter

jme3-core/src/main/java/com/jme3/effect/ParticleEmitter.java
The current code checks if all the components are either positive or negative infinity.
This patch changes it to check component per component using the `Vector3f.isValidVector()` method, without this, some (misconfigured?) particle emitters could cause the engine to crash when assertions are enabled due to the `com.jme3.bounding.Intersection` class using the  `isValidVector()` check internally.
I've encountered this issue in my code using  the newtonian particle influencer, but i don't have the step-by-step to reproduce.
=> Fix bbox validation check in particle emitter

jme3-core/src/main/java/com/jme3/input/JoystickButton.java
Extends the `JoystickButton` interface with definitions for buttons `12` through `15`, ensuring full coverage for common joystick layouts. These buttons are needed with a Logitec F310 and `lwjgl3`.
=> Add Missing Joystick Button Definitions

jme3-core/src/main/java/com/jme3/cinematic/events/MotionEvent.java
This PR introduces a minor but impactful performance optimization within the `MotionEvent` class.
Previously, the `computeTargetDirection()` method repeatedly created new `Quaternion` objects (`q` and `q2`) on each call when handling `Path` and `PathAndRotation` direction types. This constant object allocation can lead to unnecessary garbage collection overhead, particularly in performance-critical game loops or animations.
To address this, I've refactored the method to utilize a single, reusable `Quaternion` class member variable (`tempRotation`). By reusing this existing object, we significantly reduce memory allocations and subsequent garbage collection cycles, resulting in a modest but noticeable performance improvement, especially when many MotionEvents are active or when the method …
=> Reduce object allocations in MotionEvent's direction computation

jme3-core/src/main/java/com/jme3/scene/control/LightControl.java
This PR refactors the Javadoc for the `LightControl` class to enhance clarity and completeness. It also introduces the `validateSupportedLightType()` method for robust light type validation.
1. **Class-level Javadoc**: Expanded description outlining the control's purpose and typical use cases, particularly regarding dynamic light behavior.
2. **Constructor Javadoc**: Clarified parameters and added @throws for invalid light types.
3. **Robust Light Type Validation**: Implemented the new `validateSupportedLightType()` method. This ensures that the `LightControl` only accepts `PointLight`, `DirectionalLight`, and `SpotLight` instances, providing earlier error detection and preventing unexpected behavior with unsupported light types. This method is called in relevant constructors and setters. …
=> Improve LightControl Javadoc & Add Light Type Validation

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
Recent macos don't have the GL_ARB_texture_multisample ext, but they support texture multisampling
=> Add TextureMultisample cap to macos with gl > 3.2

jme3-core/src/main/java/com/jme3/post/FilterPostProcessor.java
Without this check if the platform doesn't support TextureMultisample, the fpp isn't initialized properly and it then crashes due to `tex` being null here 
https://github.com/jMonkeyEngine/jmonkeyengine/blob/c1106983f1483707586227a7501efe67173833cd/jme3-core/src/main/java/com/jme3/post/FilterPostProcessor.java#L273
=> Fix framebuffer initialization when cap TextureMultisample is missing

jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
This PR fixes issue #2472, which relates to fullscreen on Wayland. Interestingly, the custom bar isn't automatically disabled when launching glwf in fullscreen during a Wayland session.
=> Wayland fullscreen issue fixed

jme3-core/src/main/java/com/jme3/material/Materials.java
Provides a material definition that visualizes the mesh normals, useful for debugging geometry and lighting issues.
=> Materials: new material definitions for common shaders

jme3-core/src/main/java/com/jme3/app/state/ConstantVerifierState.java
This PR enhances the `ConstantVerifierState` by expanding the set of default JME math constants that are periodically checked for drift. New `Checker` entries have been added to include comprehensive verification for `Vector2f` constants such as 
* `NAN`
* `UNIT_X`
* `UNIT_Y`
* `POSITIVE_INFINITY`
* `NEGATIVE_INFINITY`.
Additionally, the Javadoc comments for the `ConstantVerifierState` class, its `ErrorType` enum, and the `addChecker` method have been refined for improved clarity, accuracy, and overall documentation quality.
=> Feat: ConstantVerifierState - expand JME constant verification, fix logger name + javadoc

jme3-core/src/main/java/com/jme3/math/ColorRGBA.java, jme3-core/src/test/java/com/jme3/math/ColorRGBATest.java
This pull request focuses on a significant code cleanup and optimization of the `ColorRGBA` class. The primary goal is to reduce code duplication, improve readability, and lay a stronger foundation for future development.
**Key improvements:**
* **DRY Principle Adherence:** Extensively applied the "Don't Repeat Yourself" principle by refactoring constructors and various `set` methods to delegate to a single, authoritative `set(float r, float g, float b, float a)`. This ensures consistent behavior and simplifies updates.
* **Improved Bitwise Operations Readability:** Complex conversions between `float` color components and `int`/`byte` representations (`asIntARGB`, `fromIntARGB`, etc.) have been abstracted into clear, concise private helper methods (`toByte`, `fromByte`, `toInt`). This …
=> Refactor: optimize ColorRGBA class + reduce code duplication

jme3-core/src/main/java/com/jme3/anim/MatrixJointModelTransform.java
This PR updates the `MatrixJointModelTransform.java` file with the following changes:
- Adds a copyright header at the top of the file.
- Improves the class-level JavaDoc to better explain the purpose and usage of `MatrixJointModelTransform`, including details about non-uniform scaling and matrix accumulation.
- Updates field-level comments for clarity.
- Refactors code for better readability by introducing local variables for parent transforms in relevant methods.
These changes enhance code documentation and maintainability without altering functionality.
=> MatrixJointModelTransform: missing license + javadoc

jme3-core/src/plugins/java/com/jme3/audio/plugins/WAVLoader.java
Key improvements include:
* **Comprehensive Javadoc:** Detailed documentation has been added to all classes, methods, and significant fields, making the code much easier to understand and use.
* **Enhanced Readability:** Variables have been consistently renamed for better clarity and adherence to Java naming conventions .
* **Increased Robustness & Clean State:**
* The `WAVLoader`'s **instance variables are now explicitly nullified or reset after each load operation**, ensuring a clean state for subsequent uses and proper resource management. (see `ResettableInputStream`, `AudioData`, `AudioBuffer`, `AudioStream`)
* **Minor Optimizations:** Buffer reading has been optimized, and logging messages are now more efficient.
These changes collectively make the `WAVLoader` more reliable and …
=> Feat: WAVLoader: Ensures clean instance state, optimization + javadoc

jme3-core/src/main/java/com/jme3/scene/debug/custom/ArmatureDebugger.java, jme3-core/src/main/java/com/jme3/scene/debug/custom/ArmatureInterJointsWire.java, jme3-core/src/main/java/com/jme3/scene/debug/custom/ArmatureNode.java
This update refines the `ArmatureDebugger` class by optimizing its structure and adding comprehensive Javadoc documentation. The changes improve code readability, maintainability, and provide detailed explanations for class functionality making it easier for developers to understand and utilize the armature debugging tools.
This PR introduces a significant refactor and optimization of the `ArmatureNode` class, which is responsible for visualizing JME3 armatures for debugging.
Key changes include:
* **Improved Code Clarity and Maintainability:**
* Added comprehensive Javadoc comments to all classes, methods, and significant variables, explaining their purpose, parameters, and return values.
* Optimized temporary vector usage to reduce allocations during updates and picking.
* **Enhanced …
=> Feat: Improve ArmatureDebugger

jme3-core/src/main/java/com/jme3/shader/VarType.java
**Improve VarType.java documentation and fix Boolean mapping**
- Added detailed JavaDoc comments to constructors and public methods in `VarType.java` for better clarity and maintainability.
- Fixed the constructor parameter order for the `Boolean` VarType to correctly map Java primitive and wrapper classes.
- Made `javaTypes` final where appropriate to improve immutability.
- Updated copyright year.
These changes enhance code readability and correctness without altering public APIs.
=> VarType: javadoc

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java
**Refactor AbstractShadowFilter: Remove Unused Serialization and Legacy Fields**
- Removed unused imports and legacy serialization methods (`write`/`read`), simplifying the class.
- Cleaned up and clarified Javadoc comments for constructors and author attribution.
- Replaced legacy temporary variables with final temp fields for matrix and vector operations, improving consistency.
- Minor improvements in naming and parameter descriptions for clarity and maintainability.
This refactor streamlines the code, reduces clutter, and adheres to modern coding practices without affecting functionality.
=> Refactor: AbstractShadowFilter reduce object allocations

jme3-core/src/main/java/com/jme3/effect/shapes/EmitterMeshFaceShape.java
This PR introduces significant improvements to the `EmitterMeshFaceShape` class. The core change involves updating the triangle point generation algorithm to use **barycentric coordinates**, ensuring a more uniform and accurate distribution of particles across mesh faces. The barycentric coordinate method is more standard and often easier to reason about for uniform distribution within a triangle.
Additionally, this PR includes:
* **Improved Documentation:** Detailed Javadoc comments have been added throughout the class, providing clearer explanations of its functionality, constructors, and methods for better code readability and maintainability.
Red Arrow: old algorithm (linear interpolation)
Green Arrow: barycentric coordinates
=> Feat: EmitterMeshFaceShape - enhance particle emission uniformity

jme3-core/src/main/java/com/jme3/system/AppSettings.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
PR where support is implemented to change the default [GLFW](https://www.glfw.org/docs/latest/intro_guide.html#platform) platform on Linux distributions or derivatives that support Wayland to use X11 (enable GLX).
This will open the ability to reposition windows and set icons for them, as Wayland currently does not have support for this, this works if you have XWayland enabled to have a bridge.
Wayland uses EGL by default to create GL contexts, which is great, but sometimes we need to use GLX for our applications, which is very useful. XWaylanda for GLX context.
=> Support for switching platforms (from Wayland EGL to X11 GLX)

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/LightsPunctualExtensionLoader.java
I've noticed that when a spot light that points down is imported via gltf, it points up in jme.
Turns out the axis need to be inverted in the lightcontrol.
=> Fix inverted axis in gltf loader

jme3-core/src/main/java/com/jme3/shadow/PointLightShadowRenderer.java
This PR refactors the `PointLightShadowRenderer` class to improve readability and maintainability. Key changes include:
- Replaces repeated inline vector negations (e.g., `Vector3f.UNIT_X.mult(-1f)`) with clearly named constants (`X_NEG`, `Y_NEG`, `Z_NEG`).
- Updates camera axis assignments in `updateShadowCams()` to use these new constants, reducing code duplication and potential errors.
- Minor improvements to JavaDoc for clarity and consistency.
These changes make the codebase cleaner and easier to understand without altering any functionality.
=> Refactor: PointLightShadowRenderer reduce object allocations

jme3-core/src/main/java/com/jme3/effect/influencers/NewtonianParticleInfluencer.java
The proposed modification to the `NewtonianParticleInfluencer.java` file optimizes how temporary matrix objects are handled during particle tangent rotation calculations. In the original version, a new `Matrix3f` object was created inside a frequently executed code block, which could lead to unnecessary object creation and increased memory usage. 
The modified version introduces a reusable `Matrix3f` instance (`tempMat3`) as a class field, eliminating repeated allocations. This change improves performance and memory efficiency by reusing the same matrix object during tangent rotation computations.
=> Refactor: NewtonianParticleInfluencer reduce object allocations
