jMonkeyEngine/jmonkeyengine

jme3-core/src/main/java/com/jme3/renderer/opengl/GL4.java, jme3-testdata/src/main/resources/Materials/Tess/SimpleTess.tsctrl, jme3-testdata/src/main/resources/Materials/Tess/SimpleTess.tseval
Fixed the swapped bits for the shader flags and renamed the shaders for the test
=> Tessellation shader fix

build.gradle, jme3-core/src/test/java/com/jme3/SetupTest.java
previously only test as assertionEnabled = true
=> build: enable assertion for test and run

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/main/java/com/jme3/material/TechniqueDef.java, jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java
as discuss in [Ignore technique with no shader - Development - jMonkeyEngine Hub](http://hub.jmonkeyengine.org/t/ignore-technique-with-no-shader/33012/10)
I forgot that java require so many boilerplate to add a public field, since I used more sweet syntax (scala, xtend, lombock).
=> add TechniqueDef.noRender

sdk/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/tools/shortcuts/DeleteShortcut.java, sdk/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/tools/shortcuts/MoveShortcut.java, sdk/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/tools/shortcuts/RotateShortcut.java, sdk/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/tools/shortcuts/ScaleShortcut.java, sdk/jme3-scenecomposer/src/com/jme3/gde/scenecomposer/tools/shortcuts/ShortcutManager.java
smalls changes : now the DeleteShortcut cannot be activated at the same time as and other shortcutTool (prevent form miss deleting). And cleaned some code to be more functional (reduce side effects). Get involved here : http://hub.jmonkeyengine.org/t/improving-scene-composer-tools/32230/29
=> SDK SceneComposer : smalls changes and cleaner code

jme3-core/src/main/java/com/jme3/light/AmbientLight.java, jme3-core/src/main/java/com/jme3/light/DirectionalLight.java, jme3-core/src/main/java/com/jme3/light/Light.java, jme3-core/src/main/java/com/jme3/light/PointLight.java, jme3-core/src/main/java/com/jme3/light/SpotLight.java
per discussion at http://hub.jmonkeyengine.org/t/new-contributor-wants-to-submit-small-usability-tweaks/33150. The new constructors have been added in such a way as to preserve existing functionality whereby most direction and light data are copied during set* operations.
=> light constructors

sdk/jme3-materialeditor/src/com/jme3/gde/materials/multiview/widgets/TexturePanel.java
Still had that in my repo, I hope it's done the way you imagined :)
=> Fixed Issue #46 : The MaterialViewer will now simply ignore not available textures instead of crashing

jme3-core/src/main/java/com/jme3/input/FlyByCamera.java
Little docstring problem I noticed.
=> Change duplicated docstring in FlyByCamera.unregisterInput

jme3-core/src/main/java/com/jme3/light/AmbientLight.java, jme3-core/src/main/java/com/jme3/light/DefaultLightFilter.java, jme3-core/src/main/java/com/jme3/light/DirectionalLight.java, jme3-core/src/main/java/com/jme3/light/Light.java, jme3-core/src/main/java/com/jme3/light/PointLight.java, jme3-core/src/main/java/com/jme3/light/SpotLight.java, jme3-core/src/test/java/com/jme3/light/LightFilterTest.java
- implementations of intersectsSphere() for Ambient / Directional / Point / Spot  Light
(see #362)
=> Lights : added light v. sphere intersection

jme3-core/src/main/resources/joystick-mapping.properties
For both DirectInput and XInput mode. Also tentatively added support of alternate version of xbox360 controller.
=> Added support to Logitech F310

jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsVehicle.java
Hey Guys, this pull request is a bit embarassing but since this warning caught my eye during compilation I thought let's do this.
At least a tiny step towards a working javadoc :P
=> Tiny Javadoc Issue

jme3-core/src/main/java/com/jme3/material/Material.java
Yet another simple fix, but hey, atleast it's a fix :P
=> Fixes #360 : Material now serializes name

sdk/jme3-assetpack-support/src/com/jme3/gde/assetpack/browser/Bundle.properties, sdk/jme3-core/src/com/jme3/gde/core/appstates/AppStateExplorerTopComponent.java, sdk/jme3-core/src/com/jme3/gde/core/filters/Bundle.properties, sdk/jme3-core/src/com/jme3/gde/core/sceneexplorer/Bundle.properties
Yeah, really simple.
There was no comment on that Issue since May '14, but since I personally dock every window, it was annoying to scroll down, just to find the SceneExplorer.
I also tried to add more descriptive hovers (They appear when you mouseover the Window Title).
Feel free to suggest better hovers, I'll change the PR accordingly then
=> Simplify Naming of SDK Windows (#135)

jme3-core/src/main/java/com/jme3/environment/EnvironmentCamera.java
Added support of overriding for class EnvironmentCamera
=> Added support of overriding

jme3-core/src/main/java/com/jme3/scene/BatchNode.java, jme3-core/src/main/java/com/jme3/scene/Geometry.java, jme3-core/src/main/java/com/jme3/scene/GeometryGroupNode.java, jme3-core/src/main/java/com/jme3/scene/instancing/InstancedNode.java
Just corrected spelling for onGeometryUnassociated() function.
=> Corrected spelling mistake.

jme3-bullet/src/main/java/com/jme3/bullet/collision/shapes/ConeCollisionShape.java
Well, I found that I'm using this on my code with jbullet but is not present on bullet version so here it is.
=> Missing getHeight present on jbullet

jme3-core/src/main/java/com/jme3/scene/BatchNode.java
Exposed batched geometry to the users in case they need to implement their own batching or post-batch corrections.
See: http://hub.jmonkeyengine.org/t/batching-layering/35254
=> Added public method getGeometry on Batch class.

jme3-core/src/main/java/com/jme3/math/Spline.java
We allow segmentLength to be null but were calling .length(), classical NPE.
Also I fixed the typo
=> Fixed a NPE when Serializing a Spline without points.

jme3-core/src/main/java/com/jme3/app/LegacyApplication.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java
When I switched my jME3-SpaceShift-Editor to lwjgl3, I got several problems.
1. The input of chars doesn't work for UI.
2. Mouse wheel doesn't works.
3. NPE on start of application.
=> Fixes in lwjgl3

jme3-android/src/main/java/com/jme3/renderer/android/AndroidGL.java, jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/main/java/com/jme3/renderer/RenderContext.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL2.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLDebugDesktop.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLDebugES.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java, jme3-examples/src/main/java/jme3test/renderer/TestBlendEquations.java, jme3-ios/src/main/java/com/jme3/renderer/ios/IosGL.java, jme3-ios/src/main/java/com/jme3/renderer/ios/JmeIosGLES.java, jme3-jogl/src/main/java/com/jme3/renderer/jogl/JoglGL.java, jme3-lwjgl/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java
See RenderState#BlendEquation and RenderState#BlendEquationAlpha
=> Added support to glBlendEquation

jme3-bullet-native/src/native/cpp/com_jme3_bullet_objects_PhysicsRigidBody.cpp
Kirill told me to commit this.
So, I can not be considered liable for any explosion, amputation, stallmanization, injury of people or animals.
=> Fix for setAngularDamping / bullet native.

.travis.yml
without uploadArchives no more snapshots, but you can release (beta2,...)
=> travis: disable uploadArchives

jme3-core/src/main/java/com/jme3/scene/Spatial.java
Discussion about: https://hub.jmonkeyengine.org/t/userdata-map-not-going-back-to-null-value-once-any-data-is-set/36236
=> userdata to null again once all data is removed.

jme3-core/src/main/java/com/jme3/animation/SkeletonControl.java, jme3-core/src/main/java/com/jme3/material/MatParam.java
Fixes #499: Fix Hardware Skinning in 3.1
=> Also applying PR #501 on 3.1

jme3-jogl/src/main/java/com/jme3/input/jogl/NewtMouseInput.java
NewtMouseInput now handles null cursor by resetting mouse cursor to default image.
=> NewtMouseInput accepts null cursor

jme3-effects/src/main/resources/Common/MatDefs/Post/bloomExtract15.frag, jme3-effects/src/main/resources/Common/MatDefs/Post/bloomFinal15.frag
texture2D is deprecated in glsl 150
=> Use texture() instead of texture2D() in bloomExtract15 and bloomFinal15

jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanel.java
This Pull-Request fixes issue #539.
AwtPanel: Replaced console outputs by the standard java logging concept and r…emoved obsolete Sysout-Calls. No functional changes. Added missing override tags.
I also did some code formatting, like introducing missing white spaces and replacing tabs by white spaces.
=> Removed Sysout-Calls in AwtPanel (Issue #539)

jme3-ios/src/main/java/com/jme3/system/ios/IosHarness.java
just like it has been done for Android in 3c56afe
=> Using LegacyApplication in the iOS Harness

jme3-core/src/main/java/com/jme3/scene/Spatial.java
If you can't load some control, you have a message about this, but in next iteration of render, you get crash with NPE.
=> fixed the NPE with controls

jme3-core/src/main/java/com/jme3/math/Triangle.java
fixed missing Cloneable in the Triangle.
=> fixed missing Cloneable in the Triangle.

jme3-core/src/main/java/com/jme3/texture/FrameBuffer.java
This should be the fix for #502 .
I added the missing method FrameBuffer.addColorBuffer(Image.Format).
=> Fix for #502

.travis.yml, common.gradle, jme3-core/src/main/java/com/jme3/audio/openal/ALC.java, jme3-lwjgl3/build.gradle, jme3-lwjgl3/src/main/java/com/jme3/audio/lwjgl/LwjglALC.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwJoystickInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java, jme3-lwjgl3/src/main/java/com/jme3/lwjgl3/utils/APIBuffer.java, jme3-lwjgl3/src/main/java/com/jme3/lwjgl3/utils/APIUtil.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglBuffer.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglDevice.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglEvent.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglImage.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglKernel.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglPlatform.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglProgram.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/Utils.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/CLUtil.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/Info.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQuery.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQueryInt.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQueryObject.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglGLDebugOutputHandler.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
This pull request relates to issue #534. The lwjgl version was updated from 3.0.0b to 3.0.0 and all code adaptions were made.
That lwjgl update introduced many API changes, I had to rewrite a lot of the existing code. So please test it, if I missed something. (I tried many tests from the examples project, but only on my system)
=> Lwjgl3 update from 3.0.0b to 3.0.0

jme3-android/src/main/java/com/jme3/renderer/android/AndroidGL.java, jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GL3.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLDebugES.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-ios/src/main/java/com/jme3/renderer/ios/IosGL.java, jme3-ios/src/main/java/com/jme3/renderer/ios/JmeIosGLES.java, jme3-jogl/src/main/java/com/jme3/renderer/jogl/JoglGL.java, jme3-lwjgl/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java, jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MOutputCapsule.java
BlendMode.Custom allows glBlendFuncSeparate() calls.
=> Added RenderState.BlendMode.Custom

README.md
Since the selection of games in JME's README.md is a bit outdatet, I thought adding some newer games wouldn't be a bad idea.
Opinions?
=> Added LSF to showcased games

jme3-examples/src/main/java/jme3test/asset/TestOnlineJar.java, jme3-examples/src/main/java/jme3test/asset/TestUrlLoading.java, jme3-examples/src/main/java/jme3test/material/TestColoredTexture.java, jme3-examples/src/main/java/jme3test/scene/TestSceneLoading.java, jme3-examples/src/main/java/jme3test/terrain/TerrainGridAlphaMapTest.java, jme3-examples/src/main/java/jme3test/terrain/TerrainGridTest.java, jme3-examples/src/main/java/jme3test/water/TestSceneWater.java
Some problems launching examples of JmeTests (described in issue [#96](https://github.com/jMonkeyEngine/sdk/issues/96), SDK branch). Mostly dead links.
=> Fix some problems in issue #96 (SDK branch)

jme3-examples/src/main/java/jme3test/games/RollingTheMonkey.java
single class with physics marble game example.
=> New Physics based jme3 example game.

jme3-core/src/main/java/com/jme3/math/Vector3f.java, jme3-core/src/main/java/com/jme3/math/Vector4f.java
same diff I committed to 'master' on Jan 14, 2017 only without altering the line endings in Vector3f.java
Without this change, the magnitude of the project() result is incorrect unless 'other' is a unit vector.
=> fix errors in how vector projection is calculated

jme3-effects/src/main/java/com/jme3/post/filters/ColorOverlayFilter.java
Fix editing color overlay filter
=> Fix editing color overlay filter

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/DirectionalLightShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/PointLightShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/SpotLightShadowRenderer.java
Add cloneable support to shadow renderers and filters.
=> Add cloneable support to shadow renderers and filters

jme3-core/src/main/java/com/jme3/cinematic/events/MotionEvent.java
Fixed saving a spatial of a motion event control.
=> Fixed saving a spatial of a motion event control.

jme3-bullet/src/common/java/com/jme3/bullet/control/RigidBodyControl.java
Fixed saving/cloning enabled state of a RigidBodyControl.
=> Fixed saving/cloning enabled state of a RigidBodyControl.

jme3-bullet/src/common/java/com/jme3/bullet/control/CharacterControl.java, jme3-bullet/src/common/java/com/jme3/bullet/control/VehicleControl.java
The same problem for two other physics controls :)
=> Fixed cloning and saving some contorls.

jme3-bullet/src/main/java/com/jme3/bullet/collision/shapes/MeshCollisionShape.java
https://hub.jmonkeyengine.org/t/core-dump-in-libbulletjme-so-when-reading-a-saved-rigidbodycontrol/37883/
=> Fix bullet crash when MeshCollisionShape is loaded from j3o

jme3-bullet/src/main/java/com/jme3/bullet/collision/shapes/MeshCollisionShape.java
https://hub.jmonkeyengine.org/t/core-dump-in-libbulletjme-so-when-reading-a-saved-rigidbodycontrol/37883
=> Fix bullet crash when MeshCollisionShape is loaded from j3o [v3.1]

jme3-lwjgl3/src/main/java/com/jme3/util/LWJGLBufferAllocator.java
Implemented auto free LWJGL byte buffers.
=> Implemented auto free LWJGL byte buffers.

jme3-lwjgl3/src/main/java/com/jme3/util/LWJGLBufferAllocator.java
Fixed some problems with getting an address of an LWJGL buffer.
=> Fixed some problems with getting an address of an LWJGL buffer.

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java
It's just a backport changes from the master branch.
=> Backport changes from the master branch.

jme3-core/src/main/java/com/jme3/scene/shape/Cylinder.java, jme3-core/src/test/java/com/jme3/scene/ShapeGeometryTest.java
Refactored Cylinder generation to be more maintainable, readable, and fix #640.
I tested it against the former implementation, and got same results with all parameters.
=> Refactored Cylinder

jme3-core/src/main/java/com/jme3/scene/debug/SkeletonDebugger.java
Addressed issue in this comment. `https://github.com/jMonkeyEngine/jmonkeyengine/issues/660`
=> Overrode SkeletonDebugger clone method.  Ticket #660

jme3-core/src/main/java/com/jme3/shader/UniformBinding.java
Fix typo on LightPosition and LightDirection
=> Fix typo on LightPosition and LightDirection

jme3-core/src/main/java/com/jme3/renderer/Camera.java, jme3-examples/src/main/java/jme3test/renderer/TestAspectRatio.java, jme3-examples/src/main/java/jme3test/renderer/TestSplitScreen.java
Here's the fix I came up with for issue #357. See my discussion in the forum and on that issue.
=> testcases and fix for issue #357

jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanel.java
The original pull request #540 has been merged into master instead of v3.1. Cherry picked the corresponding commit from master and merged it with v3.1.
See issue #539 for further information.
=> Sysout-Calls in AWTPanel #539

jme3-terrain/src/main/resources/Common/MatDefs/Terrain/SPTerrainLighting.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/TerrainLighting.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/TerrainLighting.j3md
More information [here](https://hub.jmonkeyengine.org/t/splatting-textures-with-alpha-using-terrainlighting/38459).
=> Added alpha blending option to terrain lightings to allow alpha stencil textures.

jme3-lwjgl3/src/main/java/com/jme3/util/LWJGLBufferAllocator.java
I have found a new issue with the LWJGL buffer allocator in the case with high concurrency because I have added synchronize block only to there, but it needs to be in the deallocator as well.
=> added synchronizing during freeing memory from a deallocator.

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java, jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowRendererVR.java
The parameter renderBackFacesShadows is true by default, but it doesn't have effects because the logic of making changes is inside in the setter of this parameter. So I have added a call of the setter during initialization.
=> Fix of the one parameter of shadows render. 

jme3-effects/src/main/java/com/jme3/water/WaterFilter.java
Just extended availability to edit/save/load the water filter.
=> Update the water filter

jme3-core/src/main/java/com/jme3/environment/EnvironmentCamera.java
Added a possibility to resize env cameras.
=> added a possibility to resize env cameras.

gradle.properties, jme3-bullet-native/src/native/cpp/com_jme3_bullet_collision_PhysicsCollisionEvent.cpp, jme3-bullet-native/src/native/cpp/com_jme3_bullet_objects_PhysicsCharacter.cpp, jme3-bullet-native/src/native/cpp/com_jme3_bullet_objects_PhysicsCharacter.h, jme3-bullet/src/main/java/com/jme3/bullet/objects/PhysicsCharacter.java
Builds here:  https://riccardobl.github.io/jme3-bullet-builder/
=> Update bullet to v 2.86.1

jme3-bullet-native/src/native/cpp/com_jme3_bullet_objects_PhysicsRigidBody.cpp, jme3-bullet-native/src/native/cpp/com_jme3_bullet_objects_PhysicsRigidBody.h, jme3-bullet/src/main/java/com/jme3/bullet/objects/PhysicsRigidBody.java
because I want to get and set inertia
=> Added Inertia Manipulation Methods

.travis.yml
Caused by https://github.com/gradle/gradle/issues/2421
=> Try to fix Travis JDK7 error

jme3-core/src/main/java/com/jme3/export/SavableClassUtil.java, jme3-core/src/plugins/java/com/jme3/asset/plugins/ClasspathLocator.java
1. can't load classes from asset class loaders.
2. can't load resources from asset class loaders.
=> fixed two problems with asset manager:

jme3-core/src/main/java/com/jme3/material/ShaderGenerationInfo.java, jme3-core/src/main/java/com/jme3/material/TechniqueDef.java
Fixed NPE and ConcurrentModificationException during cloning TechniqeDef.
=> Fixed NPE and ConcurrentModificationException

jme3-core/src/main/java/com/jme3/material/ShaderGenerationInfo.java
=> Missed one collection

jme3-lwjgl3/build.gradle, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglBuffer.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/LwjglImage.java, jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/CLUtil.java
=> Support LWJGL 3.1.2

jme3-core/src/main/java/com/jme3/scene/Mesh.java, jme3-core/src/test/java/com/jme3/scene/PhantomTrianglesTest.java
Rebasing with Git was driving me crazy, so I cloned a new repo and reapplied my changes.
=> test and fix for issue #710 (phantom triangles in mesh collision)

jme3-core/src/main/java/com/jme3/input/FlyByCamera.java
In addition to correcting the cut-and-paste error referenced in issue #697, many other shortcomings of the inline documentation were corrected. Two @Overrides annotations were added. A star import was expanded into multiple statements.
=> FlyByCamera: comments, annotations, & imports; address GitHub issue #697

jme3-core/src/test/java/com/jme3/collision/CollideIgnoreTransformTest.java
I applied the patch provided by kruchinin-pavel
=> fix issue #749: NPE in CollideIgnoreTransformTest

jme3-vr/build.gradle, jme3-vr/src/main/java/com/jme3/app/VRAppState.java, jme3-vr/src/main/java/com/jme3/app/VRConstants.java, jme3-vr/src/main/java/com/jme3/app/VREnvironment.java, jme3-vr/src/main/java/com/jme3/input/vr/OculusVR.java, jme3-vr/src/main/java/com/jme3/input/vr/OculusVRInput.java, jme3-vr/src/main/java/com/jme3/input/vr/VRAPI.java, jme3-vr/src/main/java/com/jme3/input/vr/VRInputType.java, jme3-vr/src/main/java/com/jme3/util/AbstractVRViewManager.java, jme3-vr/src/main/java/com/jme3/util/VRMouseManager.java, jme3-vr/src/main/java/com/jme3/util/VRViewManager.java, jme3-vr/src/main/java/com/jme3/util/VRViewManagerOculus.java
This PR adds Oculus Rift / LibOVR support, via the LWJGL bindings.
See [the forum thread](https://hub.jmonkeyengine.org/t/libovr-oculus-rift-support/39427) for more information.
=> Add Oculus Rift support

jme3-core/src/main/java/com/jme3/asset/ImplHandler.java
Fixed NPE when you try to remove an unused asset loader.
=> fixed NPE when you try to remove an unused asset loader.

jme3-vr/src/main/java/com/jme3/input/vr/OSVR.java, jme3-vr/src/main/java/com/jme3/util/VRViewManagerOSVR.java
Comparing the classes VRViewManagerOpenVR and VRViewManagerOSVR there are some obvious refactoring possibiliets in VRViewManagerOSVR, like overridden fields and methods. This could possibly (although not likely) fix the issue described in https://hub.jmonkeyengine.org/t/official-vr-module/37830/47
=> making VRViewManagerOSVR more similar to VRViewManagerOpenVR

jme3-vr/src/main/java/com/jme3/input/vr/OSVR.java
This didn't work, so I'm reverting this change. Hopefully input from user will help.
=> reverting orientation changes.

jme3-core/src/main/java/com/jme3/scene/debug/WireSphere.java
I tested the fix in my own application. No test case provided.
=> fix issue #762 (WireSphere generates parallels with wrong radii)

jme3-core/src/main/java/com/jme3/light/LightProbe.java
Fixed the problem with saving/loading light probes.
=> fixed the problem with saving/loading light probes.

jme3-core/src/main/java/com/jme3/animation/AnimChannel.java, jme3-core/src/main/java/com/jme3/animation/AnimationUtils.java, jme3-core/src/main/java/com/jme3/cinematic/Cinematic.java, jme3-core/src/main/java/com/jme3/cinematic/KeyFrame.java, jme3-core/src/main/java/com/jme3/cinematic/events/AnimationEvent.java, jme3-core/src/main/java/com/jme3/cinematic/events/CameraEvent.java, jme3-core/src/main/java/com/jme3/cinematic/events/MotionEvent.java, jme3-core/src/main/java/com/jme3/cinematic/events/SoundEvent.java, jme3-core/src/main/java/com/jme3/scene/CameraNode.java
I believe this PR makes saving/loading of Cinematics possible. At least it works with my simple test case. I have a feeling it won't work in all cases, though. See description in c83d087 for details
This is not so large as it seems. For most classes it's just the addition of constructors. For some reason git wants to replace the whole class. I'm not sure all the changes in commit 5954822 are required when it comes to constructors.
CameraEvent is a new class derived from the anonymous inner class in Cinematic that was causing issues with serialization.
Cinematic and AnimationEvent are the two classes that have changes in them.
=> Cinematics saving/loading

jme3-blender/src/main/java/com/jme3/scene/plugins/blender/materials/MaterialContext.java
It was overriding the userDefinedUVCoords each time any one of them was used, so if different textures were depending on it, a new texCoord buffer was being created.
https://hub.jmonkeyengine.org/t/multiple-blender-importer-changes-fixes/38568
=> Fixed #642

jme3-blender/src/main/java/com/jme3/scene/plugins/blender/meshes/MeshHelper.java
https://hub.jmonkeyengine.org/t/multiple-blender-importer-changes-fixes/38568
=> Fixed a IndexOutOfBoundsException when residual weights are present

jme3-core/src/main/java/com/jme3/material/ShaderGenerationInfo.java
Fixed NPE during loading a shader node material without vertex nodes.
=> fixed NPE during loading a shader node material without vertex nodes.

jme3-core/src/plugins/java/com/jme3/material/plugins/ShaderNodeLoaderDelegate.java
Fixed finding definitions during material loading.
The problem is:
I have different shader definitions with the same name(Split/Add/Mult for different types) in my shader node material, but when I try to load it I see that loader looks at only the name of these definitions, so I have incorrect loaded material in the result.
=> Fixed finding definitions during material loading.

jme3-core/src/main/java/com/jme3/util/SafeArrayList.java, jme3-terrain/src/main/java/com/jme3/terrain/executor/TerrainExecutorService.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/MultiTerrainLodControl.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainGridLodControl.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainLodControl.java
Added a lit bit improvements for SafeArrayList:
1. improved comparing a SafeArrayList with another SafeArrayList.
2. improved the constructor by other collection
3. added a new constructor with init capacity.
Some improvements with terrain LOD control:
1. Added the new option to use camera from render view port(default false)
2. Removed unnecessary synchronize blocks
3. Replaced each control own executor to global terrain executor
4. Removed unused things
5. Reduced memory allocations
6. Fixed the issue with cloning.
Also, these changes, of course, don't break back compatibility.
=> Update terrain lod control

jme3-core/src/main/java/com/jme3/shader/Uniform.java, jme3-examples/src/main/java/jme3test/material/TestMatParamOverride.java
supposed to be an update for https://github.com/jMonkeyEngine/jmonkeyengine/pull/789
But somehow I guess I cannot override a PR from another branch
=> avoid ClassCastException in Uniform.setValue()

jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/MaterialLoader.java, jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/MeshLoader.java
The receive_shadow flag is normally interpreted.
Thoced
=> Ogre importer ignores receive_shadows  issue #647

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/DirectionalLightShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/PointLightShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/PointLightShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/PssmShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/SpotLightShadowFilter.java
I did not fix this for the deprecated Shadow Renderers because they are deprecated
=> Fix Shadow Filters not being deserializable

jme3-core/src/main/java/com/jme3/opencl/OpenCLObjectManager.java
=> Fix #694 Reduce the logging level for OpenCLObjectManager

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/DirectionalLightShadowRenderer.java
Fixed 2 parameters of shadow renderer.
=> Fixed settings of shadow render2

jme3-core/src/main/java/com/jme3/animation/Skeleton.java
=> Fix an issue with Skeleton deserializing

jme3-core/src/main/java/com/jme3/material/Materials.java
[Thread](https://hub.jmonkeyengine.org/t/suggestion-to-the-predefined-materials-and-shaders)
@Nehon
=> added class with material's constants.

jme3-core/src/main/java/com/jme3/math/Plane.java
Sorry for the multiple PR's, I'm new to the whole GitHub scene and I'm trying to gain some footing with a simplistic contribution to this great community project.
=> Add a convenience constructor to Plane

jme3-core/src/main/java/com/jme3/texture/Image.java
Javadoc on Image deprecated methods was outdated
=> Updated deprecation documentation

jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/main/java/com/jme3/renderer/RenderContext.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-examples/src/main/java/jme3test/renderer/TestBlendEquations.java
This PR fixes the problems described in issue #848.
I reworked the handling of the blend equations and blend factors in `GLRenderer` and `RenderState`.
Also reworked the existing `TestBlendEquations` example. The old example was much confusing and the lack of any documentation in the code gave me no change to understand its intention at all.
=> Fixes #848

jme3-bullet/src/common/java/com/jme3/bullet/BulletAppState.java, jme3-examples/src/main/java/jme3test/bullet/TestIssue883.java
Also changed the IF to a SWITCH and added some assertions. Note that the tickListener is added in startPhysics() only in the SEQUENTIAL case.
=> test case and fix for issue #883

jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java
When adding a vehicle to a physics space, invoke vehicle.createVehicle(this);
=> fix for issue #898

jme3-examples/src/main/java/jme3test/bullet/TestBetterCharacter.java
In addition to moving the gravity update from update() to prePhysicsTick(), I changed the copyright notice in TestBetterCharacter.java so it would conform with similar files in the project.
=> fix for issue #897

jme3-bullet-native/src/native/cpp/com_jme3_bullet_joints_PhysicsJoint.cpp
Implemented the missing Java_com_jme3_bullet_joints_PhysicsJoint_finalizeNative() method.
=> fix for issue #913

jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java, jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java
Changed the implementation of the collisionListeners list for both JBullet and native Bullet. Also organized imports and added some JavaDoc.
=> resolve issue #916

jme3-bullet/src/main/java/com/jme3/bullet/joints/HingeJoint.java, jme3-jbullet/src/main/java/com/jme3/bullet/joints/HingeJoint.java
Difficult to test, given the lack of a getter for the angularOnly flag.
=> fix for issue #917

jme3-desktop/src/main/java/com/jme3/cursors/plugins/CursorLoader.java
Potential NPE when loading animated cursors (.ani)
=> Load animated cursor NPE

jme3-bullet/src/main/java/com/jme3/bullet/objects/PhysicsRigidBody.java
I don't understand why this fixes the issue, but it does, and only for native Bullet. I tried making the analogous change to JBullet, and it had no effect.
=> fix issue #923 for native Bullet

jme3-core/src/main/java/com/jme3/math/Triangle.java, jme3-core/src/test/java/com/jme3/math/TestIssue957.java
+ Fixed the issue by nulling out both cached vectors.
+ Added an automated test for the issue.
+ Updated the copyright dates.
+ Improved the JavaDoc.
+ Added Override annotations.
=> test and fix for JME issue #957

jme3-lwjgl3/build.gradle
Just to get sure nothing is broken I ran with some of the tests in jme3-examples and everything seems running fine. 
You can take a look at changes at https://github.com/LWJGL/lwjgl3/releases
=> Bump LWJGL3 version to '3.2.1'

jme3-core/src/main/java/com/jme3/math/Quaternion.java, jme3-core/src/main/java/com/jme3/math/Vector2f.java, jme3-core/src/main/java/com/jme3/math/Vector3f.java, jme3-core/src/main/java/com/jme3/math/Vector4f.java
...that allow for comparison of values within some epsilon.
Inspired from @pspeed42 's [SimMath](https://github.com/Simsilica/SimMath) library.
=> Added isSimilar() to Quaternion, Vector2f, Vector3f and Vector4f

jme3-core/src/test/java/com/jme3/scene/TestUserData.java
Added TestUserData for PR #946
=> Added TestUserData.

jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
=> Add blend mode that sums alphas and does alpha blending for colors

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java
Now one can add own actions (ex: extend from BaseAction).
=> AnimComposer: added getAction() and addAction() methods and improved JavaDoc.

jme3-core/src/test/java/com/jme3/math/FastMathTest.java
Hi, 
I've analysed your code base and noticed that `com.jme3.math.FastMath` is not fully tested.
I've written some tests for the functions in this class with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/products). Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.
=> Add tests for com.jme3.math.FastMath

jme3-examples/src/main/java/jme3test/renderer/TestDepthStencil.java
=> Fix printing if stencil is enable or disable

jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java
Reverts jMonkeyEngine/jmonkeyengine#1054
=> Revert "Modified JmeDesktopSystem.writeImageFile() to export transparency for…"

jme3-core/src/main/java/com/jme3/shader/Uniform.java
=> fixed wrong reference check #1065

jme3-core/src/main/java/com/jme3/anim/AnimComposer.java, jme3-core/src/test/java/com/jme3/anim/AnimComposerTest.java
=> Refactor collection to set in anim composer

jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java, jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsVehicle.java, jme3-jbullet/src/main/java/com/jme3/bullet/objects/VehicleWheel.java
Just removes javadoc warnings in jme3-jbullet. 
```
> Task :jme3-jbullet:javadoc
/home/lou/git/jmonkeyengine/jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java:791: warning - invalid usage of tag >
/home/lou/git/jmonkeyengine/jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java:807: warning - invalid usage of tag >
/home/lou/git/jmonkeyengine/jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java:791: warning - invalid usage of tag >
/home/lou/git/jmonkeyengine/jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java:807: warning - invalid usage of tag >
/home/lou/git/jmonkeyengine/jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java:920: warning - invalid usage of tag &
/home/lou/git/jmonkeyengine/jme3-jbullet/src/main/java/com/jme3/bullet/objects/Physi …
```
=> #1107-Fix Javadoc warnings in OpenJDK 9+

jme3-core/src/main/java/com/jme3/audio/AudioNode.java
After reading through issue #1051 and PR #875 i removed the nullcheck from AudioNode.java.
@riccardobl is there anything else that needs to be done to resolve this?
=> Fix for 1051

jme3-examples/src/main/java/jme3test/bullet/TestIssue1120.java
Test demonstrating a GImpactCollisionShape falling through a curved mesh, when using JBullet. Native doesn't experience this issue.
=> Test for issue #1120 - JBullet GImpactShape fall-through

jme3-lwjgl3/build.gradle, jme3-vr/build.gradle
I tested on a bunch of examples from jme3-examples and works fine for me. 
Tested on Linux.
=> Bump LWJGL3 version to '3.2.3'

jme3-bullet/src/common/java/com/jme3/bullet/BulletAppState.java
Changed `BulletAppState` so it extends `AbstractAppState`.
=> fix for issue #1178 (BulletAppState violates AppState contract)

.github/workflows/main.yml, build.gradle, common-android-app.gradle, common.gradle, gradle.properties, version.gradle
=> Restore -SNAPSHOT for local builds. Add custom version name param.

jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglAbstractDisplay.java
Since this is an easy fix, I'll merge it in 7 days when there is no objection/reaction.
Otherwise we can merge it when someone "reviewed" it.
Do we want this in 3.3 as well?
=> Fixes #1249 - Don't hang up when destroy is called multiple times

jme3-core/src/main/java/com/jme3/anim/tween/AbstractTween.java, jme3-core/src/main/java/com/jme3/anim/tween/Tween.java, jme3-core/src/main/java/com/jme3/anim/tween/Tweens.java
Back in December, @pspeed42 gave permission to re-license the files @Nehon copied from Simsilica LLC, so we can address another tiny sliver of issue #1001.
=> re-assign Simsilica LLC copyrights with Paul's permission (issue #1001)

jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java
This will greatly improve performance when not all instances are inside the camera view. 
And here is a test result I did with TestInstanceNode with 3600 geometries:
Instancing Off:
All geometries inside camera view: 41 fps
Only a few objects inside camera view: 890 fps
Instancing On (no culling):
All geometries inside camera view: 210 fps
Only a few objects inside camera view: 226 fps
Instancing On (with culling):
All geometries inside camera view: 217 fps
Only a few objects inside camera view: 761 fps
See the topic on forum: 
https://hub.jmonkeyengine.org/t/question-about-geometry-instancing/43023?u=ali_rs
=> Check culling on the instanced geometries.

jme3-examples/src/main/java/jme3test/model/anim/TestBlenderAnim.java
Migrate to the new animation system, migration of old Spatial object containing animation and adding method to list all animation name in AnimComposer.
=> Migrate TestBlenderAnim to the new anim system

jme3-examples/src/main/java/jme3test/model/anim/TestOgreComplexAnim.java
Lots of code that did nothing in old test (on feet, hand). Only eft hand anim with the bone anim in simpleUpdate works. So I rework the test to do how actionSquence work and manipulate Armature and Joint with ArmatureMask apply.
So I think there is a bug in ArmatureDebugger when apply PointSize in material. In the render view all points on armature debug have same size.
=> Migrate TestOgreComplexAnim to new anim system

jme3-examples/src/main/java/jme3test/model/anim/TestOgreAnim.java
I applied some changes to have the same rendering as the original test (Add static inner class LoopAction)
=> Migrate TestOgreAnim to new anim system

jme3-examples/src/main/java/jme3test/model/anim/TestOgreAnim.java
Simplification using Tweens methods instead of NoLoopAction inner class
=> Using Tweens methods instead of the inner class

jme3-examples/src/main/java/jme3test/model/anim/TestSkeletonControlRefresh.java
Migrate SkeletonControl to new SkinningControl
=> Migrate TestSkeletonControlRefresh to new anim system

jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/lodcalc/DistanceLodCalculator.java
=> Fix for #1381

jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/LODGeomap.java
This resolves the immediate issue. I will submit additional PRs to add range-checking assertions.
=> fix issue #1382 (LODGeomap index buffers with elements too small)

jme3-android/src/main/java/com/jme3/renderer/android/RendererUtil.java, jme3-bullet/src/main/java/com/jme3/bullet/objects/PhysicsCharacter.java, jme3-core/src/main/java/com/jme3/audio/openal/ALUtil.java, jme3-core/src/main/java/com/jme3/light/OrientedBoxProbeArea.java, jme3-core/src/main/java/com/jme3/util/mikktspace/MikktspaceTangentGenerator.java, jme3-examples/src/main/java/jme3test/batching/TestBatchNode.java, jme3-examples/src/main/java/jme3test/bullet/TestIssue928.java, jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java, jme3-plugins/src/xml/java/com/jme3/export/xml/DOMSerializer.java
Info: This PR can be squashed, I mostly did over precise commits for review.
The most common change was adding a `break` to the last `case` statement of the `switch`, that's bad code that could lead to a problem, when someone adds another `case` statement overlooking the `break`.
=> Codequality Pass 1

jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainPatch.java
=> Remove unused imports in TerrainPatch.java

jme3-jogg/build.gradle
I added null checks to the j-ogg-all library, released my own v1.0.1, and changed the build script for jme3-jogg to use the new version.
=> fix issue #1244 (NPE in LogicalOggStreamImpl)

jme3-core/src/main/java/com/jme3/material/Material.java, jme3-core/src/main/java/com/jme3/scene/Geometry.java, jme3-core/src/main/java/com/jme3/scene/Node.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java, jme3-core/src/main/java/com/jme3/shadow/PssmShadowRenderer.java, jme3-core/src/main/java/com/jme3/texture/Image.java, jme3-core/src/plugins/java/com/jme3/asset/plugins/FileLocator.java, jme3-desktop/src/main/java/com/jme3/app/SettingsDialog.java, jme3-desktop/src/main/java/com/jme3/system/AWTComponentRenderer.java, jme3-niftygui/src/main/java/com/jme3/niftygui/SoundHandleJme.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/LODGeomap.java, jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java, jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowRendererVR.java
+ explicitly thrown NullPointerExceptions were converted to IllegalArgumentExceptions or (in a few cases) IllegalStateExceptions
+ where changes were made, the javadoc and copyright notices were updated as necessary
+ in some cases, exception messages were added or made more descriptive
=> resolve issue #1419 (explicitly thrown NullPointerExceptions)

jme3-core/src/main/java/com/jme3/anim/AnimFactory.java, jme3-core/src/main/java/com/jme3/animation/AnimationFactory.java, jme3-examples/src/main/java/jme3test/model/anim/TestAnimationFactory.java
1. Added a new class `AnimFactory` which does most of what `AnimationFactory` did, only for the new animation system. Much cleaner than trying to shoehorn the new system into `AnimationFactory`.
2. Modified `TestAnimationFactory` to test `AnimFactory` instead.
2. Deprecated `AnimationFactory`, which depends on the old (deprecated) animation system.
=> resolve #1453 (AnimationFactory should support the new system)

jme3-core/src/main/java/com/jme3/cinematic/events/AnimEvent.java, jme3-core/src/main/java/com/jme3/cinematic/events/AnimationEvent.java, jme3-examples/src/main/java/jme3test/animation/TestCinematic.java
This adds a new class `AnimEvent` which approximates the function of `AnimationEvent` in the old animation system. For testing, the `TestCinematic` application was modified to use `AnimEvent` in place of `AnimationEvent`.
=> add a CinematicEvent for the new animation system

jme3-core/src/main/java/com/jme3/anim/Weights.java
=> deprecate com.jme3.anim.Weights

jme3-core/src/main/java/com/jme3/scene/debug/custom/ArmatureDebugAppState.java
The proposed fix adds a `normalizeLocal()` step and improves the readability of `ArmatureDebugAppState`.
=> fix issue #1533 (failed assertion in TestAnimMigration)

jme3-core/src/tools/java/jme3tools/optimize/LodGenerator.java
Made minor documentation changes to increase the clarity when describing the purpose and use of the java file and its classes. This is a quick first change before I move back towards attempting to finish the ArrayList sort to PriorityQueue replacement.
=> LodGenerator.java: improve the javadoc

jme3-android/src/main/java/com/jme3/input/android/AndroidSensorJoyInput.java, jme3-core/src/main/java/com/jme3/anim/tween/Tweens.java, jme3-core/src/main/java/com/jme3/animation/AnimControl.java, jme3-core/src/main/java/com/jme3/audio/openal/ALAudioRenderer.java, jme3-core/src/main/java/com/jme3/cinematic/Cinematic.java, jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java, jme3-core/src/main/java/com/jme3/renderer/opengl/TextureUtil.java, jme3-core/src/main/java/com/jme3/scene/VertexBuffer.java, jme3-core/src/main/java/com/jme3/shader/Uniform.java, jme3-core/src/main/java/com/jme3/util/MaterialDebugAppState.java, jme3-core/src/main/java/com/jme3/util/TangentBinormalGenerator.java, jme3-desktop/src/main/java/com/jme3/input/AWTInput.java, jme3-examples/src/main/java/jme3test/opencl/TestContextSwitching.java, jme3-networking/src/main/java/com/jme3/network/base/DefaultClient.java, jme3-networking/src/main/java/com/jme3/network/base/DefaultServer.java, jme3-networking/src/main/java/com/jme3/network/base/KernelAdapter.java, jme3-networking/src/main/java/com/jme3/network/kernel/AbstractKernel.java, jme3-networking/src/main/java/com/jme3/network/service/rpc/RpcConnection.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/RotationOrder.java, jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/file/FbxReader.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-plugins/src/main/java/com/jme3/scene/plugins/IrUtils.java, jme3-terrain/src/main/java/com/jme3/terrain/heightmap/HillHeightMap.java, jme3-vr/src/main/java/com/jme3/app/VREnvironment.java, jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVRInput.java, jme3-vr/src/main/java/com/jme3/input/vr/oculus/OculusVR.java, jme3-vr/src/main/java/com/jme3/input/vr/openvr/OpenVRInput.java
I made this PR separate from #1581 because these corrections are slightly more risky than comments.
=> correct typos logger/exception messages

jme3-android/src/main/java/com/jme3/system/android/AndroidConfigChooser.java, jme3-core/src/main/java/com/jme3/environment/LightProbeFactory.java, jme3-core/src/main/java/com/jme3/light/SpotLight.java, jme3-core/src/main/java/com/jme3/math/MathUtils.java, jme3-core/src/plugins/java/com/jme3/texture/plugins/PFMLoader.java, jme3-examples/src/main/java/jme3test/batching/TestBatchNode.java, jme3-lwjgl/src/main/java/com/jme3/opencl/lwjgl/Utils.java, jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java, jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwKeyInput.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-terrain/src/main/java/com/jme3/terrain/noise/filter/PerturbFilter.java, jme3-vr/src/main/java/com/jme3/input/lwjgl/GlfwKeyInputVR.java, jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVRMouseManager.java
This PR renames local variables in Java code, in order to clarify the purposes of those variables.
There's plenty of room for further work along these lines.
=> rename local variables

jme3-examples/src/main/java/jme3test/bullet/TestBetterCharacter.java
=> TestBetterCharacter:  set initial camera location (issue #1630)

jme3-core/src/plugins/java/com/jme3/texture/plugins/DXTFlipper.java
Resolves #1623 
Okay, it was easy...
=> Support texture flipping for signed versions of RGTC 1 and 2

jme3-android/src/main/java/com/jme3/texture/plugins/AndroidBufferImageLoader.java, jme3-android/src/main/java/com/jme3/texture/plugins/AndroidNativeImageLoader.java
=> BufferedInputStream enhancement android

jme3-ios/src/main/java/com/jme3/input/ios/IosTouchHandler.java, jme3-ios/src/main/java/com/jme3/input/ios/TouchEventPool.java
This PR corrects the offending javadoc.
=> solve issue 1648 (jme3-ios javadoc copyied from jme3-android)

jme3-android/src/main/java/com/jme3/texture/plugins/AndroidBufferImageLoader.java, jme3-android/src/main/java/com/jme3/texture/plugins/AndroidNativeImageLoader.java, jme3-android/src/main/resources/com/jme3/asset/Android.cfg
=> Un-deprecate AndroidBufferImageLoader

CONTRIBUTING.md
This adds a new section to "CONTRIBUTION.md" as discussed at issue #1098.
=> solve issue #1098 (preferred coding style isn't documented)

jme3-core/src/main/java/com/jme3/util/TangentBinormalGenerator.java, jme3-examples/src/main/java/jme3test/stress/TestLodGeneration.java
-TangentBinormalGenerator: no changes, just remove extra empty lines and code formatting.
-TestLodGeneration: code formatting; removal of commented or deprecated code.
=> code formatting

CONTRIBUTING.md
https://hub.jmonkeyengine.org/t/how-to-create-a-pull-request-against-the-engine/45080
=> CONTRIBUTING.md:  add step-by-step instructions for submitting a PR

jme3-core/src/main/java/com/jme3/scene/Spatial.java
This corrects a typo in the jme3-core source code, making it slightly more efficient.
=> use short-circuit OR in Spatial.requiresUpdates()

.gitignore, local.properties
Prior discussion at https://hub.jmonkeyengine.org/t/local-properties-in-the-engine-repository/45196
=> remove the local.properties file

jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
=> LwjglWindow:assign new thread to `mainThread` field.

jme3-android/build.gradle, jme3-core/build.gradle, jme3-examples/build.gradle, jme3-ios/build.gradle, jme3-jbullet/build.gradle, jme3-lwjgl3/build.gradle, jme3-niftygui/build.gradle, jme3-plugins/build.gradle, jme3-terrain/build.gradle
These unnecessary dependencies were discovered with the aid of Intellij IDEA, which is an imperfect tool. So the changes will need careful review and testing.
=> downgrade or delete unnecessary library dependencies

jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwJoystickInput.java
=> NPE in reloadJoysticks() when joystick lacks buttons

jme3-core/src/main/java/com/jme3/audio/openal/ALAudioRenderer.java, jme3-examples/src/main/java/jme3test/audio/TestIssue1761.java
Delete the offending assertion, which was added in 2014 because someone thought it would be "appropriate".
I tested this fix.
=> solve issue #1761 (AssertionError in ALAudioRenderer)

jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java
=> JmeSurfaceView: Fixed duplicate app destruction.

jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnExceptionThrown.java, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnLayoutDrawn.java, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnRendererCompleted.java, jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnRendererStarted.java
Some code format and javadocs fixes
=> JmeSurfaceView: Javadocs format improves

build.gradle
I think you already upgraded Gradle to 6.9.2 but this part was left out.
=> Update the Gradle wrapper version to 6.9.2

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/TrackData.java
=> jme3-plugins:  rename the TrackData.checkTimesConsistantcy() method

README.md
Would be great to have our game Exotic Matter also mentioned as its engine is based on jME. Thanks!
=> Update README.md to include Exotic Matter

jme3-core/src/main/java/com/jme3/light/DefaultLightFilter.java
Fixes https://github.com/jMonkeyEngine/jmonkeyengine/issues/1839.
=> Fix issue #1839

jme3-android/src/main/java/com/jme3/system/android/JmeAndroidSystem.java, jme3-awt-dialogs/build.gradle, jme3-awt-dialogs/src/main/java/com/jme3/awt/AWTErrorDialog.java, jme3-awt-dialogs/src/main/java/com/jme3/awt/AWTSettingsDialog.java, jme3-awt-dialogs/src/main/java/com/jme3/system/JmeDialogsFactoryImpl.java, jme3-core/src/main/java/com/jme3/app/LegacyApplication.java, jme3-core/src/main/java/com/jme3/system/JmeDialogsFactory.java, jme3-core/src/main/java/com/jme3/system/JmeSystem.java, jme3-core/src/main/java/com/jme3/system/JmeSystemDelegate.java, jme3-core/src/test/java/com/jme3/system/MockJmeSystemDelegate.java, jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java, jme3-examples/build.gradle, jme3-ios/src/main/java/com/jme3/system/ios/JmeIosSystem.java, jme3-vr/src/main/java/com/jme3/app/VRApplication.java, settings.gradle
This integrates the changes that @riccardobl contributed in PR #1748, which unfortunately has tricky merge conflicts.
=> move SettingsDialog and ErrorDialog to new jme3-awt-dialogs module

jme3-android/src/main/java/com/jme3/view/package-info.java, jme3-android/src/main/java/com/jme3/view/surfaceview/JmeSurfaceView.java, jme3-android/src/main/java/com/jme3/view/surfaceview/OnExceptionThrown.java, jme3-android/src/main/java/com/jme3/view/surfaceview/OnLayoutDrawn.java, jme3-android/src/main/java/com/jme3/view/surfaceview/OnRendererCompleted.java, jme3-android/src/main/java/com/jme3/view/surfaceview/OnRendererStarted.java, jme3-android/src/main/java/com/jme3/view/surfaceview/package-info.java
This PR includes : 
- Migration to new `com.jme3.view.surfaceview` package.
- Addition of `package-info.java` for the new packages.
- Update of jme3-copyright.
This PR targets : 
- issue #1803.
- Parts of issue #1800.
=> JmeSurfaceView: Package migration

.github/workflows/main.yml
=> main.yml: use "temurin" openjdk. 

jme3-terrain/src/main/resources/Common/MatDefs/Terrain/AdvancedPBRTerrain.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/PBRTerrain.frag
Similar to my recent pull request doing the same for the base PbrTerrain shader (https://github.com/jMonkeyEngine/jmonkeyengine/pull/1901) this PR also adds for-loop support to the advanced version of the pbr shader that uses texture arrays
=> Refactored Advanced PBR Terrain to use new for-loops

common.gradle, jme3-examples/build.gradle, jme3-niftygui/build.gradle, jme3-testdata/build.gradle
This modifies buildscripts to dodge some unnecessary dependencies.
=> resolve issue #1926 (unnecessary dependencies)

jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java, jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglContextVR.java
=>  Cleanup NativeLibraryLoader & fix wrong library path 

jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
This PR adds the missing null check and performs some trivial refactoring.
=> solve issue #1969:  missing check in GLRenderer.clearVertexAttribs()

jme3-vr/src/main/java/com/jme3/input/vr/lwjgl_openvr/LWJGLOpenVR.java
New PullRequest as suggested in #2012
=> Variables should start with lower-case.

jme3-core/src/main/java/com/jme3/ui/Picture.java
A very straightforward implementation of the missing getters.
=> solve issue #2015 (Picture class lacks 2 getters)

jme3-core/src/main/java/com/jme3/shader/ShaderNodeDefinition.java
This implements the suggested fix and also updates the file's copyright notice.
=> solve issue 2034 (serialization of ShaderNodeDefinition)

jme3-core/src/main/java/com/jme3/anim/tween/AbstractTween.java, jme3-core/src/main/java/com/jme3/anim/tween/action/BlendableAction.java, jme3-core/src/test/java/com/jme3/anim/tween/action/ClipActionTest.java
=> 2027 - guard setters against negative values

jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java
=> solve issue #2045 (ArmatureMask.createMask() duplicate code)

jme3-core/src/main/java/com/jme3/app/AppTask.java, jme3-core/src/main/java/com/jme3/app/Application.java, jme3-core/src/main/java/com/jme3/app/BasicProfiler.java, jme3-core/src/main/java/com/jme3/app/BasicProfilerState.java, jme3-core/src/main/java/com/jme3/app/ChaseCameraAppState.java, jme3-core/src/main/java/com/jme3/app/DebugKeysAppState.java, jme3-core/src/main/java/com/jme3/app/DetailedProfiler.java, jme3-core/src/main/java/com/jme3/app/DetailedProfilerState.java, jme3-core/src/main/java/com/jme3/app/LegacyApplication.java, jme3-core/src/main/java/com/jme3/app/SimpleApplication.java, jme3-core/src/main/java/com/jme3/app/StatsView.java
One remaining issue regarding local var distance from declaration to use. 
Partial Implementation of #1877
=> 1877: Fix style issues on jme3-core/com.jme3.app package

jme3-core/src/main/java/com/jme3/export/FormatVersion.java, jme3-core/src/main/java/com/jme3/scene/UserData.java, jme3-examples/src/main/java/jme3test/export/TestIssue2068.java, jme3-plugins/src/test/java/com/jme3/export/JmeExporterTest.java, jme3-plugins/src/xml/java/com/jme3/export/xml/DOMInputCapsule.java, jme3-plugins/src/xml/java/com/jme3/export/xml/DOMOutputCapsule.java, jme3-plugins/src/xml/java/com/jme3/export/xml/XMLUtils.java
Updates the J3o version from 2 to 3 for adding "jme-" prefix to userdata maps, lists, and arrays to fix #2068 xml export issue.
=> Fixes XML Map Export

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
When a geometry is loaded by the gltf loader for the first time, the same instance that is cached is also returned, meaning that changes to the first instance will reflect also to the other instances of the same cached geometry.
This PR ensures that this never happens by returning a clone also for the first instance.
=> Fix Gltf cache leak

jme3-core/src/main/resources/Common/MatDefs/Shadow/PostShadow.vert, jme3-core/src/main/resources/Common/MatDefs/Shadow/PreShadow.vert, jme3-examples/src/main/java/jme3test/model/anim/TestGltfMorph.java
Yep, just some errors on the shaders.
I modified the TestGltfMorph to have the shadows instead of duplicating it. I hope this is ok. I can change it if not of course.
Resolves #1997
=> Fix #1997 (shadows on hardware-accelerated morph animations)

jme3-core/src/main/java/com/jme3/scene/Geometry.java
Convenient Geometry constructor with material, in order to avoid systematic subsequent setMaterial setter.
=> Geometry constructor with material.

jme3-core/src/main/java/com/jme3/texture/Texture.java
Fixes Issue #2132 
see: https://github.com/jMonkeyEngine/jmonkeyengine/issues/2132
=> Fixes Issue #2132 (Texture.load() doesn't trigger mipmap generation)

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java
=> Solve #2136 (flow-control issue with glTF alpha parameter)

jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/CustomContentManager.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfModelKey.java, jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UserDataLoader.java
Adds a default user data loader from Simsilica's JmeConvert to the GLTF loader to make it load custom properties/extras as user data.
=> Add userdata loader to gltf

jme3-core/src/plugins/java/com/jme3/scene/plugins/MTLLoader.java
=> solve issue #2135 (ClassCastException in MTLLoader)

README.md
The recent publication of ndebruyn's jam prompted me to take another look at README.md
The tone and inaccuracies of our README have irritated me for years, so I decided to refine it a bit.
=> updates to the README

jme3-core/src/main/java/com/jme3/material/RenderState.java, jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java, jme3-core/src/main/java/com/jme3/util/res/ResourceLoader.java, jme3-core/src/main/java/com/jme3/util/res/Resources.java, jme3-examples/src/main/java/jme3test/animation/TestIssue2076.java
Fixed a bunch of Javadoc errors ~that were preventing the build~.
=> Fix javadoc errors

jme3-effects/src/main/java/com/jme3/post/filters/FXAAFilter.java, jme3-effects/src/test/java/com/jme3/post/filters/FXAAFilterTest.java
A straightforward fix based on @capdevon's suggestion, plus an automated test to catch regressions.
=> solve issue #2168 (incomplete serialization of FXAAFilter)

jme3-effects/src/main/java/com/jme3/post/filters/PosterizationFilter.java, jme3-effects/src/test/java/com/jme3/post/filters/PosterizationFilterTest.java
A straightforward fix based on @capdevon's suggestion, plus an automated test to catch regressions.
=> solve issue #2167 (incomplete serialization of PosterizationFilter) #2170

jme3-effects/src/main/java/com/jme3/post/filters/DepthOfFieldFilter.java, jme3-effects/src/test/java/com/jme3/post/filters/DepthOfFieldFilterTest.java
I implemented @capdevon's suggested fix and added an automated test to catch regressions.
=>  solve issue #2166 (logic error in DepthOfFieldFilter serialization) 

LICENSE.md
This PR should be integrated as soon as any changes to the public repository are published.
=> update copyright years in the license

jme3-examples/src/main/java/jme3test/terrain/PBRTerrainTest.java
This PR implements the suggested fix for issue #2178.
Ready for review.
=> solve issue #2178 (PBRTerrainTest typo)

jme3-examples/src/main/java/jme3test/terrain/PBRTerrainAdvancedTest.java
This PR implements the suggested fix for issue #2177.
=> solve issue #2177 (PBRTerrainAdvancedTest typo)

jme3-core/src/main/java/com/jme3/environment/baker/IBLGLEnvBaker.java
This PR addresses issue #2186 and updates the copyright years for the affected source file.
=> IBLGLEnvBaker:  don't share a logger with IBLHybridEnvBakerLight

README.md
Not sure if this list is only for released games, or if a coming-soon title is allowed (feel free to deny this pr if not)
=> Add The Afflicted Forests to README.md

jme3-core/src/main/java/com/jme3/environment/util/BoundingSphereDebug.java
=> BoundingSphereDebug: removed the unused variable radius and its getter method getRadius()

jme3-core/src/main/java/com/jme3/material/MatParam.java
MatParam: format code
update License year
=> MatParam: format code

jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java, jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java
- Update License year
- AbstractShadowRenderer.setRenderBackFacesShadows(): Change input type Boolean -> boolean.
- AbstractShadowFilter.setRenderBackFacesShadows(): Change input type Boolean -> boolean.
PR for Issue [ #2203 ]
=> AbstractShadowRenderer.setRenderBackFacesShadows(): Change input type Boolean -> boolean

jme3-examples/src/main/java/jme3test/light/TestIssue2209.java
This PR adds a test for issue #2209, to help us detect regressions.
=> jme3-examples:  add the TestIssue2209 class

jme3-core/src/main/java/com/jme3/math/AbstractTriangle.java, jme3-core/src/main/java/com/jme3/math/Line.java, jme3-core/src/main/java/com/jme3/math/LineSegment.java, jme3-core/src/main/java/com/jme3/math/Rectangle.java, jme3-core/src/test/java/com/jme3/math/TestToString.java
This PR addresses the enhancements requested in issue #2246
=> override toString() in certain math classes

jme3-terrain/src/main/resources/Common/MatDefs/Terrain/AdvancedPBRTerrain.frag, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/PBRTerrain.frag
Solves the issue recently discussed in this thread:
https://hub.jmonkeyengine.org/t/pbr-terrain-in-editor-advancedpbrterrain-frag-pbrterrain-frag-errors-solved-navmesh-editing-walkable-buildings-unsolved/47619/5
=> Fix Casting error that occurred on certain GPUs

README.md
keep this important documentation up-to-date
=> update README.md to report 3.7 as the latest stable version

jme3-core/src/main/java/com/jme3/anim/Armature.java
Since PR #2154 apparently got lost, I'm submitting this new PR.
=> Armature.java:  javadoc correction (to solve issue #2142 again)

jme3-examples/src/main/java/jme3test/terrain/PBRTerrainAdvancedTest.java, jme3-examples/src/main/java/jme3test/terrain/PBRTerrainTest.java, jme3-terrain/src/main/resources/Common/MatDefs/Terrain/Modular/PBRTerrainUtils.glsllib
This PR attempts to fix the issue that my previous PR unfortunately failed to fix: https://github.com/jMonkeyEngine/jmonkeyengine/pull/2365
I have made some more minor changes to the shader code that might fix it.
And shortly I'm also going to update this PR so that the PBRTerrain tests will allow users to easily toggle the DebugValuesMode debug view of each individual pbr layer so that issues like this are easier to troubleshoot in the future.
=> Add debugging to PBRTerrainTests to troubleshoot rendering issue

jme3-core/src/main/java/com/jme3/texture/TextureArray.java, jme3-core/src/test/java/com/jme3/texture/TextureArrayTest.java
=> Fix TextureArray not exporting WrapMode

jme3-examples/src/main/java/jme3test/water/TestPostWater.java
Refactored the `TestPostWater `example code for improved clarity. This commit restructures the demo to explicitly highlight its individual components, making it easier to understand the flow and functionality.
=> jme3-examples: TestPostWater code cleanup

jme3-examples/src/main/java/jme3test/audio/TestOgg.java
* added additional parameter tests
* added GUI to display changed parameters
* added graphical visual references to 3d scene
=> jme3-examples: TestOgg - added additional parameter tests

jme3-core/src/main/java/com/jme3/material/Material.java
This PR significantly improves the Javadoc for the `Material` class, making its functionality clearer and easier to understand for developers. I've created this initial PR specifically for the Javadoc as it's a prerequisite for my next PR. 
That upcoming PR will introduce a feature that's already present in the codebase but currently disabled. To facilitate an easier review process, I've opted to split these changes into two separate PRs.
Additionally, I've repositioned the `toString()` method before the `read/write` methods for improved code readability, and I've also performed some minor code formatting in various places.
=> Enhance Material Javadoc

jme3-core/src/main/java/com/jme3/material/RenderState.java
=> Fixed stencil reference handling in RenderState #2538
